import {cp,mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url));
const out=path.join(root,'dist');await mkdir(out,{recursive:true});
for(const name of ['index.html','style.css','combat-v2.css','presentation-v3.css','quality-v4.css','update-v1.1.css','update-v1.2.css','rpg-v2.0.css','adventure-v2.2.css','mercenary-v2.3.css','remaster-v2.4.css','story-v2.5.css','mine-v2.6.css','boss-v2.7.css','collection-v2.8.css','affinity-v2.9.css','fortress-v3.0.css','chaos-v3.1.css','canyon-v3.2.css','castle-v3.3.css','battle-v3.4.css','final-v3.4.css','pov-v3.5.css','attack-s-v3.5.css','roster-v35.css','combat-rebuild-v35.css','legendary-v35.css','start-screen-v35.css','class-coop-v35.css','src','assets'])await cp(path.join(root,name),path.join(out,name),{recursive:true});
await writeFile(path.join(out,'.nojekyll'),'');
const uiPath=path.join(out,'src','UI.js'),ui=await readFile(uiPath,'utf8');
if(!ui.includes('const BUILD_DEBUG_ALLOWED=true;'))throw new Error('Missing explicit development debug guard');
await writeFile(uiPath,ui.replace('const BUILD_DEBUG_ALLOWED=true;','const BUILD_DEBUG_ALLOWED=false;'));
const html=await readFile(path.join(out,'index.html'),'utf8');if(!html.includes('src/UI.js'))throw new Error('Missing entry point');
console.log('Production static build: dist/');
