import {prepareBoss} from '../src/BossBattleSystem.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {RPGMode} from '../src/RPGMode.js';
import {RPGConfig,characterStats,createRPGContext} from '../src/RPGConfig.js';
import {validateSave,migrateSave} from '../src/SaveSystem.js';
import {QuestData,QuestTypes} from '../src/QuestData.js';
import {blankQuests,acceptQuest,progressQuests,questStatus} from '../src/QuestSystem.js';
import {rollLoot,grantLoot} from '../src/LootSystem.js';
import {LootTable} from '../src/LootData.js';
import {ForestDungeon,DungeonData} from '../src/DungeonData.js';
import {canEnterDungeon,unlockDungeon} from '../src/DungeonSystem.js';
import {ForestMonsterData} from '../src/ForestMonsterData.js';
import {enemyIntent,syncEncounter} from '../src/EncounterData.js';
import {createState} from '../src/GameState.js';
import {CombatSystem} from '../src/CombatSystem.js';
import {battleEvents} from '../src/BattleEvents.js';
import {equipmentById} from '../src/EquipmentData.js';
import {ScrollData} from '../src/ScrollData.js';
import {useScroll} from '../src/ScrollSystem.js';
import {forestSimulation} from './forest-balance.mjs';
import {enemyGesture} from '../src/VisualEffects.js';
import {renderRPGScreen} from '../src/RPGView.js';
class Storage{constructor(){this.map=new Map();}getItem(k){return this.map.get(k)||null;}setItem(k,v){this.map.set(k,v);}}
const make=(rng=()=>.99)=>{const storage=new Storage(),rpg=new RPGMode(storage,rng);rpg.create('숲의 용사');return {rpg,storage};};
function emit(rpg,type,extra={},id=crypto.randomUUID()){return rpg.dispatchEvent({id,type,dungeonId:'old-prison',...extra});}
function complete(rpg,id){rpg.acceptQuest(id);const q=QuestData.find(q=>q.id===id);for(let i=0;i<q.target;i++){const types={KILL_MONSTER:'MONSTER_DEFEATED',ATTACK_GRADE_SUCCESS:'ATTACK_SUCCESS',DEFENSE_GRADE_SUCCESS:'DEFENSE_SUCCESS',BLOCK_SPECIAL:'SPECIAL_BLOCKED',USE_DIFFERENT_SCROLLS:'SCROLL_USED',USE_SCROLL:'SCROLL_USED',CLEAR_WITH_HP:'DUNGEON_CLEARED',CLEAR_DUNGEON:'DUNGEON_CLEARED'};emit(rpg,types[q.type],{monster:q.filter.monster,grade:'S',source:'defense',scroll:['fire','ice','heal'][i%3],hpRatio:.9,defeated:false});}rpg.save();}
function unlocked(){const x=make();complete(x.rpg,'first-adventure');x.rpg.data.progress.clearedDungeons.push('old-prison');x.rpg.reportQuest('first-adventure');complete(x.rpg,'forest-road');x.rpg.reportQuest('forest-road');return x;}
function setLevel(rpg,n=4){Object.assign(rpg.character,{level:n,exp:0,...characterStats(n),hp:characterStats(n).maxHP});rpg.character.inventory.items.push('steel_sword','leather_armor');rpg.equip('steel_sword');rpg.equip('leather_armor');rpg.character.hp=rpg.character.maxHP;rpg.save();}
function forceWin(rpg,s,c){s.enemies.forEach(e=>e.hp=0);syncEncounter(s);c.win();rpg.onBattleEvent(s.events.at(-1),s);}
function chooseLoot(rpg,s,c){c.chooseReward(s.lootCandidates[0]);rpg.recordLoot(s,s.lootAcquired);}
test('original ten quests remain alongside four fortress quests',()=>{assert.equal(QuestData.filter(q=>q.dungeon!=='chaos-tower'&&q.dungeon!=='black-fortress'&&!q.id.includes("companion")&&q.id!=="perfect-team"&&!q.id.startsWith("collection-")&&!q.id.startsWith("personal-")).length,10);assert.equal(new Set(QuestData.map(q=>q.id)).size,30);assert.equal(QuestTypes.slice(0,9).length,9);});
for(const key of ['name','level','exp','gold','hp','scrolls','equipment','inventory']){
 test('v2.1 migration preserves '+key,()=>{const {rpg}=make();setLevel(rpg);rpg.character.gold=357;rpg.character.hp=81;rpg.character.inventory.items.push('life_necklace','life_necklace');const old=structuredClone(rpg.data);old.saveVersion=2;for(const k of Object.keys(blankQuests()))delete old.progress[k];delete old.progress.unlockedDungeons;delete old.progress.dungeonClearHistory;delete old.progress.lootHistory;const next=validateSave(old);assert.equal(next.saveVersion,5);assert.deepEqual(next.character[key],old.character[key]);assert.deepEqual(next.progress.unlockedDungeons,['old-prison']);});
}
test('direct v2.0 to v2.2 migration keeps clear history and resources',()=>{const {rpg}=make();const old=structuredClone(rpg.data);old.saveVersion=1;delete old.character.equipment;delete old.character.inventory;old.progress.clearedDungeons=['old-prison'];const m=validateSave(old);assert.equal(m.saveVersion,5);assert.deepEqual(m.progress.clearedDungeons,['old-prison']);assert.deepEqual(m.character.scrolls,old.character.scrolls);});
test('migration is idempotent and does not mutate old record',()=>{const {rpg}=make();const old=structuredClone(rpg.data);old.saveVersion=2;const before=JSON.stringify(old),m=migrateSave(old);assert.equal(JSON.stringify(old),before);assert.deepEqual(migrateSave(m),m);});
test('quest acceptance persists with ACTIVE status',()=>{const {rpg,storage}=make();assert.ok(rpg.acceptQuest('brain-power').ok);const next=new RPGMode(storage);next.load();assert.equal(questStatus(next.data.progress,'brain-power'),'ACTIVE');});
test('fourth active quest is refused without mutation',()=>{const {rpg}=make();for(const id of ['brain-power','perfect-math','shield-practice'])assert.ok(rpg.acceptQuest(id).ok);assert.equal(rpg.acceptQuest('goblin-hunt').ok,false);assert.equal(rpg.data.progress.activeQuests.length,3);});
test('duplicate and unknown acceptance do not create extra records',()=>{const {rpg}=make();rpg.acceptQuest('brain-power');assert.equal(rpg.acceptQuest('brain-power').ok,false);assert.equal(rpg.acceptQuest('missing').ok,false);assert.equal(rpg.data.progress.activeQuests.length,1);});
test('unaccepted quests never progress retroactively',()=>{const {rpg}=make();emit(rpg,'ATTACK_SUCCESS',{grade:'S'});rpg.acceptQuest('perfect-math');assert.equal(rpg.data.progress.questProgress['perfect-math'].count,0);});
test('monster type and dungeon filters exclude wrong kills',()=>{const {rpg}=make();rpg.acceptQuest('goblin-hunt');emit(rpg,'MONSTER_DEFEATED',{monster:'skeleton'});emit(rpg,'MONSTER_DEFEATED',{monster:'goblin',dungeonId:'cursed-forest'});emit(rpg,'MONSTER_DEFEATED',{monster:'goblin'});assert.equal(rpg.data.progress.questProgress['goblin-hunt'].count,1);});
test('A and S attack count while B and C do not',()=>{const {rpg}=make();rpg.acceptQuest('brain-power');for(const grade of ['B','C','A','S'])emit(rpg,'ATTACK_SUCCESS',{grade});assert.equal(rpg.data.progress.questProgress['brain-power'].count,2);});
test('S-only quest rejects attack A',()=>{const {rpg}=make();rpg.acceptQuest('perfect-math');emit(rpg,'ATTACK_SUCCESS',{grade:'A'});emit(rpg,'ATTACK_SUCCESS',{grade:'S'});assert.equal(rpg.data.progress.questProgress['perfect-math'].count,1);});
test('defense grade and attack events stay separate',()=>{const {rpg}=make();rpg.acceptQuest('shield-practice');emit(rpg,'ATTACK_SUCCESS',{grade:'S'});emit(rpg,'DEFENSE_SUCCESS',{grade:'C'});emit(rpg,'DEFENSE_SUCCESS',{grade:'A'});assert.equal(rpg.data.progress.questProgress['shield-practice'].count,1);});
test('special blocked by time magic does not count Defense S',()=>{const {rpg}=make();rpg.acceptQuest('iron-guardian');emit(rpg,'SPECIAL_BLOCKED',{source:'time'});emit(rpg,'SPECIAL_BLOCKED',{source:'defense'});assert.equal(rpg.data.progress.questProgress['iron-guardian'].count,1);});
test('distinct scroll quest counts a type once and completes on third type',()=>{const {rpg}=make();rpg.acceptQuest('magic-study');for(const scroll of ['fire','fire','ice','heal'])emit(rpg,'SCROLL_USED',{scroll});assert.equal(rpg.data.progress.questProgress['magic-study'].count,3);assert.equal(questStatus(rpg.data.progress,'magic-study'),'COMPLETED');});
test('clear quests use actual clear event',()=>{const {rpg}=make();rpg.acceptQuest('first-adventure');emit(rpg,'MONSTER_DEFEATED',{monster:'orc'});assert.equal(rpg.data.progress.questProgress['first-adventure'].count,0);emit(rpg,'DUNGEON_CLEARED',{hpRatio:.6});assert.equal(questStatus(rpg.data.progress,'first-adventure'),'COMPLETED');});
test('HP clear boundary uses pre-return health and includes exact 50%',()=>{const {rpg}=make();rpg.acceptQuest('safe-return');emit(rpg,'DUNGEON_CLEARED',{hpRatio:.49});assert.equal(questStatus(rpg.data.progress,'safe-return'),'ACTIVE');emit(rpg,'DUNGEON_CLEARED',{hpRatio:.5});assert.equal(questStatus(rpg.data.progress,'safe-return'),'COMPLETED');});
test('CLEAR_WITHOUT_DEFEAT is data-driven and rejects failed runs',()=>{const p=blankQuests();acceptQuest(p,'safe-return');const catalog=[{...QuestData.find(q=>q.id==='safe-return'),type:'CLEAR_WITHOUT_DEFEAT'}];progressQuests(p,{id:'a',type:'DUNGEON_CLEARED',dungeonId:'old-prison',defeated:true},catalog);assert.equal(p.questProgress['safe-return'].count,0);progressQuests(p,{id:'b',type:'DUNGEON_CLEARED',dungeonId:'old-prison',defeated:false},catalog);assert.equal(questStatus(p,'safe-return'),'COMPLETED');});
test('quest completion grants no immediate EXP or gold',()=>{const {rpg}=make();complete(rpg,'brain-power');assert.equal(rpg.character.gold,0);assert.equal(rpg.character.exp,0);});
test('incomplete report gives nothing',()=>{const {rpg}=make();rpg.acceptQuest('brain-power');assert.equal(rpg.reportQuest('brain-power').ok,false);assert.equal(rpg.character.gold,0);});
test('manual report grants exact EXP and gold then REWARDED',()=>{const {rpg}=make();complete(rpg,'brain-power');assert.ok(rpg.reportQuest('brain-power').ok);assert.equal(rpg.character.exp,45);assert.equal(rpg.character.gold,65);assert.equal(questStatus(rpg.data.progress,'brain-power'),'REWARDED');});
test('quest scroll reward merges bounded charges',()=>{const {rpg}=make();complete(rpg,'magic-study');rpg.reportQuest('magic-study');assert.equal(rpg.character.scrolls.find(s=>s.type==='heal').uses,1);});
test('quest equipment enters existing duplicate inventory',()=>{const {rpg}=make();rpg.character.inventory.items.push('guardian_charm');complete(rpg,'iron-guardian');rpg.reportQuest('iron-guardian');assert.equal(rpg.character.inventory.items.filter(id=>id==='guardian_charm').length,2);});
test('rapid reports and reload cannot duplicate any reward',()=>{const {rpg,storage}=make();complete(rpg,'iron-guardian');rpg.reportQuest('iron-guardian');const before=structuredClone(rpg.character);for(let i=0;i<5;i++)assert.equal(rpg.reportQuest('iron-guardian').ok,false);const next=new RPGMode(storage);next.load();assert.equal(next.reportQuest('iron-guardian').ok,false);assert.deepEqual(next.character,before);});
test('repeated event identities do not count twice',()=>{const {rpg}=make();rpg.acceptQuest('perfect-math');for(let i=0;i<4;i++)emit(rpg,'ATTACK_SUCCESS',{grade:'S'},'one-action');assert.equal(rpg.data.progress.questProgress['perfect-math'].count,1);});
test('completion frees an active slot without discarding completed report',()=>{const {rpg}=make();complete(rpg,'perfect-math');for(const id of ['brain-power','shield-practice','goblin-hunt'])assert.ok(rpg.acceptQuest(id).ok);assert.ok(rpg.data.progress.completedQuests.includes('perfect-math'));});
test('loot roll includes existing gold and excludes all drops at high RNG',()=>{assert.deepEqual(rollLoot([{type:'goblin'}],25,()=>.99),{gold:25,scrolls:[],equipment:[]});});
test('low RNG yields scroll and equipment in configured table',()=>{assert.deepEqual(rollLoot([{type:'goblin'}],25,()=>0),{gold:25,scrolls:['ice'],equipment:['old_sword']});});
test('loot supports multiple monsters and duplicate gear',()=>{const {rpg}=make(),loot=rollLoot([{type:'skeleton'},{type:'skeleton'}],30,()=>0);grantLoot(rpg.character,loot);assert.deepEqual(rpg.character.inventory.items,['old_sword','old_sword']);assert.equal(rpg.character.scrolls.find(s=>s.type==='shield').uses,4);});
test('loot probabilities remain modest and boss highest',()=>{for(const t of Object.values(LootTable)){assert.ok(t.equipmentChance<=.14);assert.ok(t.scrollChance<=.4);}assert.ok(LootTable.treeGuardian.equipmentChance>LootTable.skeleton.equipmentChance);});
test('loot is rolled once per victory and persisted before next encounter',()=>{let calls=0;const {rpg,storage}=make(()=>{calls++;return 0;});rpg.enterDungeon();const {state:s,combat:c}=rpg.createBattle();forceWin(rpg,s,c);const before=JSON.stringify(rpg.character),n=calls;rpg.awardBattle(s);assert.equal(calls,n);assert.equal(JSON.stringify(rpg.character),before);const next=new RPGMode(storage,()=>{throw Error('reroll')});next.load();const restored=next.createBattle();assert.equal(next.awardBattle(restored.state),false);assert.equal(JSON.stringify(next.character),before);assert.equal(next.data.progress.lootHistory.length,1);});
test('pending loot refresh preserves exact rolled equipment and scroll',()=>{const {rpg,storage}=make(()=>0);rpg.enterDungeon();const {state:s,combat:c}=rpg.createBattle();forceWin(rpg,s,c);const drops=structuredClone(rpg.receipt.drops);const next=new RPGMode(storage);next.load();next.createBattle();assert.deepEqual(next.receipt.drops,drops);assert.equal(next.character.gold,15);});
test('first dungeon available and forest locked even at high level',()=>{const {rpg}=make();setLevel(rpg,10);assert.ok(rpg.enterDungeon('old-prison'));assert.equal(canEnterDungeon(rpg.data.progress,'cursed-forest'),false);});
test('forest road cannot be accepted before prerequisite report',()=>{const {rpg}=make();assert.equal(rpg.acceptQuest('forest-road').ok,false);complete(rpg,'first-adventure');assert.equal(rpg.acceptQuest('forest-road').ok,false);});
test('forest unlock requires first clear and road report together',()=>{const {rpg}=make();assert.equal(unlockDungeon(rpg.data.progress,'cursed-forest'),false);assert.equal(rpg.enterDungeon('cursed-forest'),false);const x=unlocked();assert.equal(x.rpg.enterDungeon('cursed-forest'),true);});
test('forest unlock and quest progress survive reload',()=>{const {rpg,storage}=unlocked();const next=new RPGMode(storage);assert.equal(next.load().status,'ready');assert.ok(canEnterDungeon(next.data.progress,'cursed-forest'));assert.equal(questStatus(next.data.progress,'forest-road'),'REWARDED');});
test('active dungeon cannot be swapped or used to heal',()=>{const {rpg}=unlocked();rpg.enterDungeon();rpg.character.hp=47;assert.equal(rpg.enterDungeon('cursed-forest'),false);assert.equal(rpg.character.hp,47);assert.equal(rpg.run.dungeonId,'old-prison');});
test('forest uses five fights and includes a two-enemy combination',()=>{assert.equal(ForestDungeon.encounters.length,5);assert.ok(ForestDungeon.encounters.some(e=>e.enemies.length===2));assert.equal(ForestMonsterData.length,5);});
for(const [index,special]of [[0,'guard'],[1,'steal'],[2,'poison'],[3,'shift'],[4,'regenSeed']]){
 test('new monster intent '+ForestMonsterData[index].id,()=>{const {rpg}=unlocked();setLevel(rpg);rpg.enterDungeon('cursed-forest');const {state:s,combat:c}=rpg.createBattle();c.configureEncounter(0,{id:'test',enemies:[{type:ForestMonsterData[index].id}]});c.startTurn();assert.equal(s.enemies[0].intent.special,special);assert.equal(s.targets.length,8);});
}
test('guard heals six HP, caps maximum and remains blockable',()=>{const {rpg}=unlocked();rpg.enterDungeon('cursed-forest');const {state:s,combat:c}=rpg.createBattle();const e=s.enemies[0];s.enemyResolutionIndex=0;e.hp-=10;c.applySpecial();assert.equal(e.hp,e.maxHP-4);s.blockedIds.add(e.id);const hp=e.hp;assert.equal(c.applySpecial().kind,'block');assert.equal(e.hp,hp);});
test('boss phase two strengthens attack and changes special at half HP',()=>{const {rpg}=unlocked();rpg.enterDungeon('cursed-forest');const {state:s,combat:c}=rpg.createBattle();c.configureEncounter(4);c.startTurn();const e=s.enemies[0],normal=e.intent.attack;e.hp=e.maxHP/2;prepareBoss(s,e);const next=enemyIntent(s,e);assert.equal(e.bossPhase,2);assert.equal(next.attack,normal+2);assert.equal(next.special,'regenSeed');});
test('forest Defense S still blocks only selected special, both normal attacks remain',()=>{const {rpg}=unlocked();rpg.enterDungeon('cursed-forest');const {state:s,combat:c}=rpg.createBattle();c.configureEncounter(2);c.startTurn();const t=s.targets.find(t=>t.side==='defense'&&t.grade==='S');c.submit(t.solution.ids,t.solution.ops);assert.ok(c.awaitingChoices());c.chooseTarget(0,s.enemies[0].id);const events=[];while(s.phase==='resolution')events.push(c.resolveNext());assert.equal(events.filter(e=>e.kind==='enemy').length,2);assert.equal(events.filter(e=>e.kind==='block').length,1);assert.equal(s.hero.poison,2);});
test('adapter ignores reserved barrier and time stop, records actual selected block',()=>{const {rpg}=unlocked();rpg.enterDungeon('cursed-forest');const {state:s}=rpg.createBattle();assert.equal(battleEvents({kind:'barrier'},s,rpg.run).length,0);assert.equal(battleEvents({kind:'block',special:'none'},s,rpg.run).length,0);s.scrollStop=true;assert.equal(battleEvents({kind:'block',special:'guard'},s,rpg.run).length,0);s.scrollStop=false;assert.equal(battleEvents({kind:'block',special:'guard',enemyId:'one'},s,rpg.run)[0].type,'SPECIAL_BLOCKED');});
test('killed enemy identity cannot progress again after checkpoint retry',()=>{const {rpg,storage}=make();rpg.acceptQuest('skeleton-clean');rpg.enterDungeon();const {state:s}=rpg.createBattle();s.enemies[0].hp=0;syncEncounter(s);rpg.onBattleEvent({kind:'magic',type:'fire',action:{playerId:0}},s);rpg.save();const next=new RPGMode(storage);next.load();const restored=next.createBattle();restored.state.enemies[0].hp=0;next.onBattleEvent({kind:'magic',type:'fire',action:{playerId:0}},restored.state);assert.equal(next.data.progress.questProgress['skeleton-clean'].count,1);});
test('forest complete awards configured higher gold and saves five settlements',()=>{const {rpg,storage}=unlocked();setLevel(rpg);const before=rpg.character.gold;rpg.enterDungeon('cursed-forest');const {state:s,combat:c}=rpg.createBattle();for(let i=0;i<5;i++){forceWin(rpg,s,c);chooseLoot(rpg,s,c);if(i<4)rpg.advanceBattle(s,c);}assert.equal(s.phase,'clear');assert.equal(rpg.character.gold-before,411);assert.equal(rpg.data.progress.lootHistory.length,5);assert.equal(rpg.data.progress.dungeonClearHistory.at(-1).dungeonId,'cursed-forest');assert.equal(rpg.returnToTown(),'clear');const next=new RPGMode(storage);assert.equal(next.load().status,'ready');assert.ok(next.data.progress.clearedDungeons.includes('cursed-forest'));});
test('healing scroll with sage gear adds healing but no accidental enemy damage',()=>{const {rpg}=make();rpg.character.inventory.items.push('sage_staff');rpg.equip('sage_staff');rpg.enterDungeon();const {state:s}=rpg.createBattle();s.hero.hp=50;s.scrolls=[{type:'heal',uses:1}];const hp=s.enemies[0].hp;useScroll(s);assert.equal(s.enemies[0].hp,hp);assert.equal(s.hero.hp,82);});
test('CLASS context has no adventure dungeon or quest modifiers',()=>{const state=createState(4,'simultaneous'),core=new CombatSystem(state);core.configureEncounter(0);core.startTurn();assert.equal(state.battleContext.mode,'class');assert.equal(state.hero.hp,180);assert.equal(state.battleContext.dungeonId,undefined);assert.equal(state.enemies[0].maxHP,230);});
for(const field of ['unknown-item','duplicate-state','bad-progress','fake-unlock','bad-loot','bad-clear']){
 test('malformed v3 record rejected: '+field,()=>{const {rpg}=make();const d=structuredClone(rpg.data),p=d.progress;if(field==='unknown-item')d.character.inventory.items.push('unknown');if(field==='duplicate-state'){p.activeQuests=['brain-power'];p.completedQuests=['brain-power'];p.questProgress['brain-power']={count:5,scrolls:[]};}if(field==='bad-progress'){p.activeQuests=['brain-power'];p.questProgress['brain-power']={count:-1,scrolls:[]};}if(field==='fake-unlock')p.unlockedDungeons.push('cursed-forest');if(field==='bad-loot')p.lootHistory=[{id:'a',dungeonId:'old-prison',loot:{gold:0,scrolls:[],equipment:['unknown']}}];if(field==='bad-clear')p.dungeonClearHistory=[{id:'a',dungeonId:'old-prison',hpRatio:2,defeated:false}];assert.throws(()=>validateSave(d));});
}
test('production entry includes expansion stylesheet and build copies all new modules',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),build=await readFile(new URL('../build.mjs',import.meta.url),'utf8');assert.ok(html.includes('adventure-v2.2.css'));assert.ok(build.includes('adventure-v2.2.css'));for(const id of ForestMonsterData.map(m=>m.id))assert.ok((await stat(new URL(`../assets/${id}-v22.webp`,import.meta.url))).size<700000);});
for(const seed of [1,2,3]){
 test('Lv4 basic gear real forest S strategy clears seed '+seed,()=>{const r=forestSimulation('adaptive',seed,'S');assert.equal(r.phase,'clear');assert.ok(r.hp>0);assert.ok(r.turns.every(n=>n>0));assert.ok(r.totalTurns<=30);});
 test('Lv4 real forest A defense and attack strategy clears seed '+seed,()=>{const r=forestSimulation('adaptive',seed,'A');assert.equal(r.phase,'clear');assert.ok(r.hp>0);assert.ok(r.totalTurns<=40);});
}
test('forest A attacks without defense lose and pure defense cannot advance',()=>{assert.equal(forestSimulation('attack',1,'A').phase,'gameover');const defense=forestSimulation('defense',1,'S');assert.notEqual(defense.phase,'clear');assert.equal(defense.turns.slice(1).reduce((a,b)=>a+b,0),0);});
test('all forest attack gestures and unknown future actors have safe readable feedback',()=>{for(let i=5;i<=9;i++)for(let v=0;v<3;v++)assert.equal(typeof enemyGesture(i,v),'string');assert.equal(enemyGesture(99),'일반 공격');});
test('actual legacy v2.1 pending receipt migrates without rerolling or granting rewards again',()=>{const {rpg,storage}=make();rpg.enterDungeon();const {state:s,combat:c}=rpg.createBattle();forceWin(rpg,s,c);const old=structuredClone(rpg.data);old.saveVersion=2;for(const k of Object.keys(blankQuests()))delete old.progress[k];delete old.progress.lootHistory;delete old.progress.unlockedDungeons;delete old.progress.dungeonClearHistory;delete old.progress.run.pendingLoot.receipt.drops;storage.setItem(RPGConfig.saveKey,JSON.stringify(old));const next=new RPGMode(storage,()=>{throw Error('legacy reroll')});assert.equal(next.load().status,'ready');const resumed=next.createBattle();assert.equal(resumed.state.phase,'reward');assert.equal(next.awardBattle(resumed.state),false);assert.deepEqual(next.character,old.character);assert.deepEqual(resumed.state.lootCandidates,old.progress.run.pendingLoot.candidates);});
test('post-clear reload preserves HP quest snapshot before town healing',()=>{const {rpg,storage}=make();rpg.acceptQuest('safe-return');rpg.enterDungeon();const {state:s,combat:c}=rpg.createBattle();for(let i=0;i<3;i++){s.hero.hp=20;forceWin(rpg,s,c);chooseLoot(rpg,s,c);if(i<2)rpg.advanceBattle(s,c);}rpg.returnToTown();const next=new RPGMode(storage);next.load();assert.equal(next.character.hp,next.character.maxHP);assert.equal(questStatus(next.data.progress,'safe-return'),'ACTIVE');assert.ok(next.data.progress.dungeonClearHistory[0].hpRatio<.5);});
test('monsters, quests and all loot entries reference existing rewards',()=>{for(const q of QuestData){if(q.reward.equipment)assert.ok(equipmentById(q.reward.equipment));if(q.reward.scroll)assert.ok(ScrollData[q.reward.scroll]);assert.ok(q.target>0);}for(const dungeon of DungeonData)for(const e of dungeon.encounters.flatMap(c=>c.enemies))assert.ok(LootTable[e.type]);for(const t of Object.values(LootTable)){assert.ok(t.equipment.every(equipmentById));assert.ok(t.scrolls.every(id=>ScrollData[id]));}});
test('quest reward notice cannot hide a real storage failure warning',()=>{const rpg=new RPGMode({getItem(){return null;},setItem(){throw Error('quota');}});rpg.create('창의 용사');complete(rpg,'brain-power');const reward=rpg.reportQuest('brain-power');assert.equal(rpg.saveInfo.ok,false);const html=renderRPGScreen('rpg-guild',rpg,reward.message);assert.ok(html.includes('완료 보고'));assert.ok(html.includes('모험을 저장하지 못했어요'));});
