import test from 'node:test';
import assert from 'node:assert/strict';
import {RPGMode} from '../src/RPGMode.js';
import {CoreMercenaryData as MercenaryData} from '../src/MercenaryData.js';
import {MercenarySystem} from '../src/MercenarySystem.js';
import {relation,rewardAffinityClear,awakenCompanion,situationalLine} from '../src/AffinitySystem.js';
import {PersonalQuestData,CompanionStories} from '../src/AffinityData.js';
import {validateSave,migrateSave} from '../src/SaveSystem.js';
import {skillValue,incomingCompanionDamage} from '../src/MercenarySkillResolver.js';
import {characterStats} from '../src/RPGConfig.js';
import {syncEncounter} from '../src/EncounterData.js';
import {takeDamage} from '../src/DefenseSystem.js';
import {companionRecordsHTML} from '../src/CompanionView.js';
const setup=(id='rowen')=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},r=new RPGMode(storage,()=>.99);r.create('동료 모험가');r.finishOpening();Object.assign(r.character,{level:10,exp:0,...characterStats(10),hp:145,gold:50000});const p=r.data.progress;p.unlockedDungeons=['old-prison','cursed-forest','burning-mine'];p.clearedDungeons=['old-prison','cursed-forest'];p.story.mineInvestigated=true;p.rewardedQuests=['forest-road'];p.questProgress['forest-road']={count:1,scrolls:[]};r.hire(id);return r;};
function trust(r,id){const v=relation(r.data.progress,id);v.affinityLevel=2;v.affinityProgress=3;v.personalQuestUnlocked=true;v.unlockedDialogues=[1,2];}
function awake(r,id){trust(r,id);const q='personal-'+id;r.acceptQuest(q);const spec=PersonalQuestData.find(x=>x.id===q);r.data.progress.questProgress[q]={count:1,scrolls:[],personal:{actions:spec.needed,won:true}};r.data.progress.activeQuests=[];r.data.progress.completedQuests=[q];assert.ok(r.reportQuest(q).awakening);}
const ev=(kind,grade='S',extra={})=>({kind,damage:kind==='attack'?40:0,action:{targetGrade:grade,playerId:0},...extra});
function singleSupport(system,event,state){const supports=system.support(event,state);assert.ok(Array.isArray(supports));assert.ok(supports.length<=1);return supports[0]||null;}
function clear(r,n=0,dungeon='old-prison',success=true){r.enterDungeon(dungeon);const run=r.run;run.id='clear-'+n;r.data.progress.mercenaryContractState.runId=run.id;run.completed=r.dungeon.encounters.map((_,i)=>i);run.status='clear';run.partyState.successfulEncounters=success?[...run.completed]:[];r.data.progress.mercenaryContractState.successfulEncounters=run.partyState.successfulEncounters;return {run,state:{enemies:[{type:'golem',hp:0,boss:{}}]}};}
test('new saves have six independent stranger relations, no hire farming',()=>{const r=setup();for(const m of MercenaryData)assert.equal(relation(r.data.progress,m.id).affinityProgress,0);relation(r.data.progress,'rowen').claimIds.push('only-rowen');assert.deepEqual(relation(r.data.progress,'bram').claimIds,[]);assert.ok(r.save());});
for(const m of MercenaryData)test(m.id+' actual clear opens trust but never stage three',()=>{const r=setup(m.id),{run,state}=clear(r);const result=rewardAffinityClear(r.data,run,state);assert.equal(result.points,3);assert.equal(relation(r.data.progress,m.id).affinityLevel,2);assert.ok(relation(r.data.progress,m.id).personalQuestUnlocked);assert.equal(relation(r.data.progress,m.id).awakenedSkillUnlocked,false);assert.equal(rewardAffinityClear(r.data,run,state),null);});
test('clear needs real calculations throughout the adventure',()=>{const r=setup(),{run,state}=clear(r,0,'old-prison',false);assert.equal(rewardAffinityClear(r.data,run,state),null);assert.equal(relation(r.data.progress,'rowen').completedDungeonsTogether,0);});
test('aborted and failed adventures have no affinity',()=>{const r=setup(),{run,state}=clear(r);for(const status of ['active','defeat']){run.status=status;assert.equal(rewardAffinityClear(r.data,run,state),null);}});
test('repeat clear bonus diminishes 3,1,0 without clock limits',()=>{const r=setup(),points=[];for(let i=0;i<4;i++){const {run,state}=clear(r,i);points.push(rewardAffinityClear(r.data,run,state).points);r.data.progress.run=null;r.data.progress.mercenaryContractState=null;r.data.progress.activeMercenary=null;r.setParty(['rowen']);}assert.deepEqual(points,[3,1,0,0]);assert.equal(relation(r.data.progress,'rowen').completedDungeonsTogether,4);assert.equal(relation(r.data.progress,'rowen').affinityLevel,2);});
for(const field of ['character','collection','activeQuests','questProgress','mercenaryContractState','unlockedDungeons','story','lootHistory','dungeonClearHistory'])test('v2.8 additive migration preserves '+field,()=>{const r=setup();r.enterDungeon();const old=structuredClone(r.data);old.saveVersion=4;delete old.progress.mercenaryRelations;const before=structuredClone(old),next=validateSave(old);if(field==='mercenaryContractState'){for(const key of ['counts','eventIds','successfulEncounters','status','runId'])assert.deepEqual(next.progress[field][key],before.progress[field][key],key);assert.deepEqual(next.progress.activeParty,[before.progress.activeMercenary]);}else assert.deepEqual(field==='character'?next.character:next.progress[field],field==='character'?before.character:before.progress[field]);assert.deepEqual(old,before);assert.deepEqual(migrateSave(next),next);assert.equal(next.progress.mercenaryRelations.rowen.affinityLevel,1);});
test('corrupt relationships rejected, intact backup available',()=>{const r=setup();r.save();const bad=structuredClone(r.data);bad.progress.mercenaryRelations.rowen.affinityLevel=3;assert.throws(()=>validateSave(bad));r.saves.storage.setItem('dungeon-rpg-adventure-save',JSON.stringify(bad));assert.equal(r.saves.load().status,'recovered');});
for(const q of PersonalQuestData){
 test(q.id+' trust required and wrong companion cannot enter',()=>{const r=setup(q.mercenaryId);assert.equal(r.acceptQuest(q.id).ok,false);trust(r,q.mercenaryId);assert.ok(r.acceptQuest(q.id).ok);const other=MercenaryData.find(m=>m.id!==q.mercenaryId).id;assert.ok(r.hire(other).ok);assert.ok(r.setParty([other]).ok);assert.equal(r.enterPersonalQuest(q.id).ok,false);});
 test(q.id+' matching real events, victory, report exactly once',()=>{const r=setup(q.mercenaryId);trust(r,q.mercenaryId);r.acceptQuest(q.id);assert.ok(r.enterPersonalQuest(q.id).ok);const base={personalQuestId:q.id,mercenaryId:q.mercenaryId,dungeonId:q.dungeon};const type=q.condition==='attack'?'ATTACK_SUCCESS':q.condition==='defense'?'DEFENSE_SUCCESS':q.condition==='scroll'?'SCROLL_USED':q.condition==='break'?'BOSS_BREAK':'ATTACK_SUCCESS';
  r.dispatchEvent({...base,id:'wrong',type,grade:'S',mercenaryId:'none'});assert.equal(r.data.progress.questProgress[q.id].personal.actions,0);
  r.dispatchEvent({...base,id:'early-win',type:'PERSONAL_VICTORY',hpRatio:1});assert.equal(r.data.progress.questProgress[q.id].count,0);
  for(let i=0;i<q.needed;i++){const e={...base,id:'actual-'+i,type,grade:q.condition==='perfect'?'S':'A'};r.dispatchEvent(e);r.dispatchEvent(e);}
  assert.equal(r.data.progress.questProgress[q.id].personal.actions,q.needed);r.dispatchEvent({...base,id:'win',type:'PERSONAL_VICTORY',hpRatio:1});assert.ok(r.data.progress.completedQuests.includes(q.id));assert.equal(relation(r.data.progress,q.mercenaryId).affinityLevel,2);
  assert.equal(r.reportQuest(q.id).ok,false);r.run.status='defeat';r.returnToTown();const gold=r.character.gold,result=r.reportQuest(q.id);assert.ok(result.awakening);assert.equal(r.character.gold,gold+60);assert.equal(relation(r.data.progress,q.mercenaryId).affinityLevel,3);const paid=structuredClone(r.character);assert.equal(r.reportQuest(q.id).ok,false);assert.deepEqual(r.character,paid);assert.equal(r.character.gold,gold+60);assert.ok(r.saveInfo.ok);assert.equal(awakenCompanion(r.data.progress,q.mercenaryId,q.id),null);
 });
}
test('Rowen quest accepts A and never demands an S streak',()=>{const r=setup();trust(r,'rowen');r.acceptQuest('personal-rowen');const e={personalQuestId:'personal-rowen',mercenaryId:'rowen',dungeonId:'old-prison',type:'ATTACK_SUCCESS',grade:'A'};for(let i=0;i<2;i++)r.dispatchEvent({...e,id:'a'+i});assert.equal(r.data.progress.questProgress['personal-rowen'].personal.actions,2);});
test('Sera minimum HP checked on victory, retries keep action progress',()=>{const r=setup('sera');trust(r,'sera');r.acceptQuest('personal-sera');const e={personalQuestId:'personal-sera',mercenaryId:'sera',dungeonId:'cursed-forest'};for(let i=0;i<2;i++)r.dispatchEvent({...e,id:'calc'+i,type:'DEFENSE_SUCCESS',grade:'B'});r.dispatchEvent({...e,id:'lowwin',type:'PERSONAL_VICTORY',hpRatio:.2});assert.equal(r.data.progress.questProgress['personal-sera'].count,0);r.dispatchEvent({...e,id:'retrywin',type:'PERSONAL_VICTORY',hpRatio:.25});assert.equal(r.data.progress.questProgress['personal-sera'].count,1);});
test('personal boss win does not clear region, grant normal bonus, or change unique pity',()=>{const r=setup();trust(r,'rowen');r.acceptQuest('personal-rowen');const before=structuredClone(r.data.progress.collection.bossLoot.golem),cleared=[...r.data.progress.clearedDungeons];r.enterPersonalQuest('personal-rowen');const {state}=r.createBattle();state.enemies.forEach(e=>e.hp=0);syncEncounter(state);state.phase='clear';state.lootCandidates=['fire','shield','heal'];const receipt=r.awardBattle(state);assert.deepEqual(receipt.bonus,{exp:0,gold:0});assert.deepEqual(r.data.progress.collection.bossLoot.golem,before);assert.deepEqual(r.data.progress.clearedDungeons,cleared);assert.equal(r.data.progress.dungeonClearHistory.length,0);assert.equal(relation(r.data.progress,'rowen').completedDungeonsTogether,0);assert.ok(r.saveInfo.ok);const next=validateSave(r.data);assert.equal(next.progress.run.nextEncounter,1);assert.equal(r.awardBattle(state),false);});
for(const m of MercenaryData)test(m.id+' small trusted bonus and awakened skill preserve trigger grades/caps',()=>{const r=setup(m.id);r.enterDungeon();const {state}=r.createBattle(),s=new MercenarySystem(r.data,r.run),kind=m.trigger==='dual'?'attack':m.trigger,event=ev(kind,'S',{type:'fire',mercenaryBoost:6});if(kind==='victory')r.run.partyState.successfulEncounters=[0];const base=skillValue(r.data,m,event,state);trust(r,m.id);assert.equal(skillValue(r.data,m,event,state),base+1);assert.equal(s.available(ev('pass'),state),false);assert.equal(s.available(ev(kind,'C'),state),kind==='victory');});
test('awakened Rowen pierces a second enemy only on S',()=>{const r=setup();awake(r,'rowen');r.enterDungeon('cursed-forest');r.run.nextEncounter=2;const {state}=r.createBattle(),s=new MercenarySystem(r.data,r.run);const before=state.enemies[1].hp,a=singleSupport(s,ev('attack','A',{enemyId:state.enemies[0].id}),state);assert.equal(a.secondary,undefined);state.turn++;const x=singleSupport(s,ev('attack','S',{enemyId:state.enemies[0].id}),state);assert.equal(x.secondary.value,3);assert.equal(state.enemies[1].hp,before-3);});
test('awakened Bram normal damage hook is once per current turn, no special mitigation',()=>{const r=setup('bram');awake(r,'bram');r.enterDungeon();const {state}=r.createBattle(),s=new MercenarySystem(r.data,r.run);singleSupport(s,ev('defense'),state);assert.equal(incomingCompanionDamage(r.data,r.run,state,8),8);assert.equal(r.run.skillState.guardReady,true);assert.equal(incomingCompanionDamage(r.data,r.run,state,16),13);assert.equal(incomingCompanionDamage(r.data,r.run,state,16),16);state.turn++;singleSupport(s,ev('defense'),state);state.turn++;assert.equal(incomingCompanionDamage(r.data,r.run,state,20),20);r.run.skillState.guardReady=true;r.run.skillState.guardTurn=state.turn;state.hero.shield=0;const hp=state.hero.hp;takeDamage(state,16,'special');assert.equal(state.hero.hp,hp-16);assert.equal(r.run.skillState.guardReady,true);});
test('Sera emergency is once per dungeon, persisted, positive HP only',()=>{const r=setup('sera');awake(r,'sera');r.enterDungeon();const {state}=r.createBattle(),s=new MercenarySystem(r.data,r.run);state.hero.hp=10;assert.equal(singleSupport(s,ev('attack'),state).value,6);state.turn++;state.hero.hp=10;assert.equal(singleSupport(s,ev('attack'),state),null);r.captureBattle(state);assert.ok(r.save());assert.equal(validateSave(r.data).progress.run.skillState.seraEmergencyUsed,true);state.hero.hp=0;assert.equal(singleSupport(s,ev('defense'),state),null);assert.equal(state.hero.hp,0);});
for(const [type,value]of [['fire',8],['ice',8],['heal',9],['shield',9],['cleanse',7],['time',7]])test('Luna awakened '+type+' boost '+value,()=>{const r=setup('luna');awake(r,'luna');r.enterDungeon();const {state}=r.createBattle(),s=new MercenarySystem(r.data,r.run);if(type==='heal')state.hero.hp=100;assert.equal(skillValue(r.data,MercenaryData.find(m=>m.id==='luna'),ev('magic','S',{type}),state),value);assert.equal(s.scrollModifier({targetGrade:'S',scrollEffect:type},state),6);assert.equal(s.scrollModifier({targetGrade:'A',scrollEffect:type},state),0);});
test('Kain strongest support confined to genuine boss BREAK',()=>{const r=setup('kain');awake(r,'kain');r.enterDungeon('old-prison','deep');r.run.nextEncounter=2;const {state}=r.createBattle(),m=MercenaryData.find(m=>m.id==='kain'),event=ev('attack','S',{enemyId:state.enemies[0].id});assert.equal(skillValue(r.data,m,event,state),13);state.enemies[0].boss.breakTurns=2;assert.equal(skillValue(r.data,m,event,state),17);assert.equal(new MercenarySystem(r.data,r.run).available(ev('attack','A'),state),false);});
test('Elia awakened S paths cap at three shared supports and hint has no answer',()=>{const r=setup('elia');awake(r,'elia');r.enterDungeon('old-prison','deep');r.run.nextEncounter=2;const {state}=r.createBattle(),s=new MercenarySystem(r.data,r.run);for(let i=0;i<3;i++){state.turn++;const x=singleSupport(s,ev(i%2?'attack':'defense','S',{enemyId:state.enemies[0].id}),state);assert.match(x.text,/석갑|차단|약점/);assert.doesNotMatch(x.text,/정답|\d+\s*[+×÷]/);}state.turn++;assert.equal(singleSupport(s,ev('attack'),state),null);});
test('CLASS cannot trigger even awakened emergency or scroll support',()=>{const r=setup('sera');awake(r,'sera');r.enterDungeon();const {state}=r.createBattle(),s=new MercenarySystem(r.data,r.run);state.battleContext.mode='class';state.hero.hp=1;const before=structuredClone(r.data.progress);assert.equal(singleSupport(s,ev('attack'),state),null);assert.deepEqual(r.data.progress,before);assert.equal(state.hero.hp,1);});
test('occasional dialogue cooldown and identity survive repeated event',()=>{const r=setup();r.enterDungeon();const {state}=r.createBattle(),event=ev('attack');const a=situationalLine(r.data.progress,r.run,event,state);assert.ok(a);assert.equal(situationalLine(r.data.progress,r.run,event,state),null);state.turn+=3;assert.equal(situationalLine(r.data.progress,r.run,event,state),null);state.turn++;assert.notEqual(situationalLine(r.data.progress,r.run,event,state).text,a.text);});
test('record hides locked story and skill, retains original six portraits',()=>{const r=setup(),html=companionRecordsHTML(r,'','','rowen');assert.match(html,/\?\?\?/);assert.ok(!html.includes(CompanionStories.rowen.chapters[1]));assert.match(html,/assets\/mercenaries\/rowen.webp/);trust(r,'rowen');const trusted=companionRecordsHTML(r,'','','rowen');assert.ok(trusted.includes(CompanionStories.rowen.chapters[1]));assert.ok(!trusted.includes(CompanionStories.rowen.chapters[2]));});
test('decisive Rowen S scene is late, once, and cosmetic after exhausted support quota',()=>{const r=setup();trust(r,'rowen');r.acceptQuest('personal-rowen');r.enterPersonalQuest('personal-rowen');const {state}=r.createBattle();const early=ev('attack');situationalLine(r.data.progress,r.run,early,state);assert.equal(r.run.rowenDecisiveSeen,undefined);state.enemies[0].hp=Math.floor(state.enemies[0].maxHP*.4);const hp=state.enemies[0].hp,event=ev('attack','S',{enemyId:state.enemies[0].id});assert.ok(situationalLine(r.data.progress,r.run,event,state));assert.ok(event.support.cosmetic);assert.equal(state.enemies[0].hp,hp);assert.equal(r.data.progress.mercenaryStats.supports,0);assert.equal(situationalLine(r.data.progress,r.run,ev('attack'),state),null);assert.ok(r.save());});
for(const key of ['personalQuestId','companionId','personalIntroSeen','skillState','companionLineIds','lastCompanionLineTurn'])test('personal checkpoint rejects malformed '+key,()=>{const r=setup();trust(r,'rowen');r.acceptQuest('personal-rowen');r.enterPersonalQuest('personal-rowen');const d=structuredClone(r.data);d.progress.run[key]=key==='skillState'?{seraEmergencyUsed:'true'}:key==='companionLineIds'?['same','same']:key==='lastCompanionLineTurn'?-1:key==='personalIntroSeen'?1:'unknown';assert.throws(()=>validateSave(d));});
test('public enterDungeon API cannot inject an unaccepted personal route',()=>{const r=setup();assert.equal(r.enterDungeon('old-prison',undefined,'personal-rowen'),false);assert.equal(r.run,null);assert.equal(r.enterDungeon('old-prison',undefined,'unknown'),false);});
test('first boss bonus remains available after ordinary prison repetitions, once per boss',()=>{const r=setup(),v=relation(r.data.progress,'rowen');for(let i=0;i<3;i++){const {run,state}=clear(r,i);state.enemies=[{type:'orc',hp:0}];rewardAffinityClear(r.data,run,state);r.data.progress.run=null;r.data.progress.activeMercenary=null;r.data.progress.mercenaryContractState=null;r.setParty(['rowen']);}const {run,state}=clear(r,3);assert.equal(rewardAffinityClear(r.data,run,state).points,1);assert.ok(v.claimIds.includes('first-boss:golem'));assert.equal(rewardAffinityClear(r.data,run,state),null);r.data.progress.run=null;r.data.progress.activeMercenary=null;r.data.progress.mercenaryContractState=null;r.setParty(['rowen']);const next=clear(r,4);assert.equal(rewardAffinityClear(r.data,next.run,next.state).points,0);});

test('exhausted Rowen story arrow joins the party presentation array without consuming support or damage',()=>{const r=setup();trust(r,'rowen');r.acceptQuest('personal-rowen');r.enterPersonalQuest('personal-rowen');const {state}=r.createBattle();state.enemies[0].hp=Math.floor(state.enemies[0].maxHP*.4);const hp=state.enemies[0].hp,event=ev('attack','S',{enemyId:state.enemies[0].id,support:null,supports:[]});assert.ok(situationalLine(r.data.progress,r.run,event,state));assert.equal(event.supports.length,1);assert.equal(event.supports[0].mercenaryId,'rowen');assert.equal(event.supports[0].cosmetic,true);assert.equal(event.supports[0].value,0);assert.equal(event.support,event.supports[0]);assert.equal(state.enemies[0].hp,hp);assert.equal(r.data.progress.mercenaryStats.supports,0);});
