import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {AudioManager,AudioAssets} from '../src/AudioManager.js';import {displayText} from '../src/LocalizedText.js';
function wav(name){const b=readFileSync(new URL(`../assets/audio/${name}.wav`,import.meta.url));assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.readUInt16LE(20),1);assert.equal(b.readUInt16LE(34),16);const channels=b.readUInt16LE(22),rate=b.readUInt32LE(24),samples=(b.length-44)/2;let peak=0;for(let i=44;i<b.length;i+=2)peak=Math.max(peak,Math.abs(b.readInt16LE(i))/32768);return {b,channels,duration:samples/channels/rate,peak};}
test('original music assets are long stereo loops with smooth boundaries and no clipping',()=>{for(const name of ['dungeon-suite','golem-suite']){const {b,channels,duration,peak}=wav(name);assert.equal(channels,2);assert.ok(duration>65);assert.ok(peak<.7);for(let ch=0;ch<2;ch++)assert.ok(Math.abs(b.readInt16LE(44+ch*2)-b.readInt16LE(b.length-4+ch*2))/32768<.005);}});
test('weapon and major combat assets have bounded peaks and quiet endpoints',()=>{for(const name of new Set(Object.values(AudioAssets.effects).flat())){const {b,peak,duration}=wav(name);assert.ok(peak<=.71);assert.ok(duration<=1.2);assert.ok(Math.abs(b.readInt16LE(44))/32768<.003);assert.ok(Math.abs(b.readInt16LE(b.length-2))/32768<.003);}});
test('display translations preserve numbers, HP, player identifiers and grades',()=>{assert.equal(displayText('TOTAL DAMAGE 55'),'총 피해 55');assert.equal(displayText('3P SHIELD +26'),'3P 방어막 +26');assert.equal(displayText('TURN 2'),'2턴');assert.equal(displayText('SPECIAL BLOCKED!'),'특수 공격 방어 성공!');assert.equal(displayText('HP 180 · S/A/B/C'),'HP 180 · S/A/B/C');});
function mock(){const sources=[],targets=[];const param=()=>({value:1,setTargetAtTime(v){this.value=v;targets.push(v);},cancelScheduledValues(){},setValueAtTime(v){this.value=v;},exponentialRampToValueAtTime(){}}),node=()=>({gain:param(),connect(){return this;},disconnect(){}});const c={currentTime:0,destination:{},resume:async()=>{},createDynamicsCompressor:node,createGain:node,decodeAudioData:async()=>({duration:65.45}),createBufferSource:()=>{const s={...node(),playbackRate:param(),start(){},stop(){}};sources.push(s);return s;}};return {c,sources,targets};}
test('same music stays running across input/battle; variations and grade gains stay bounded',async()=>{const {c,sources}=mock(),a=new AudioManager(()=>c);await a.activate();a.buffers.set('dungeon-suite',{duration:65.45});a.playBGM('dungeon');await new Promise(r=>setImmediate(r));const music=a.music,source=music.source;a.setMood('battle');a.playBGM('battle');assert.equal(a.music,music);assert.equal(a.music.source,source);assert.equal(music.gain.gain.value,.92);a.setMood('input');assert.equal(music.gain.gain.value,.52);
 for(const name of Object.values(AudioAssets.effects).flat())a.buffers.set(name,{});a.play('attack',{grade:'C'});a.play('attack',{grade:'A'});a.play('attack',{grade:'S'});const records=a.history.filter(x=>x.name==='attack');assert.ok(records[0].gain<records[1].gain);assert.equal(records[1].gain,records[2].gain);assert.notEqual(a.previousVariation.attack,undefined);for(let i=0;i<30;i++)a.play('magic');assert.equal(a.voices.size,12);a.configure('SFX',{enabled:false});const count=sources.length;a.play('attack');assert.equal(sources.length,count);a.dispose();});
test('active audio with missing assets remains usable and never throws',async()=>{const {c}=mock(),a=new AudioManager(()=>c);await a.activate();const original=globalThis.fetch;try{globalThis.fetch=async()=>{throw Error('missing');};assert.equal(await a.load('missing-file'),null);assert.equal(await a.playAsset('missing.wav'),false);a.play('tap');assert.equal(a.active,true);}finally{globalThis.fetch=original;a.dispose();}});
