const path=require('node:path');let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}const {chromium}=playwright,assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true}),errors=[],runs=[];page.on('pageerror',e=>errors.push(e.message));
async function start(players,mode='sequential'){await page.goto('http://127.0.0.1:4173/?debug=1');await page.locator('[data-action=setup]').tap();await page.locator(`[data-players="${players}"]`).tap();await page.locator(`[data-mode="${mode}"]`).tap();await page.locator('[data-action=story]').tap();await page.locator('[data-action=start]').tap();await page.locator('[data-action=presentation-skip]').dispatchEvent('click');await page.waitForFunction(()=>window.dungeonDebug.timer.running);await page.locator('[data-action=debug-toggle]').tap();await page.locator('#debug-animation').selectOption('0.25');await page.locator('[data-action=debug-toggle]').tap();}
const state=()=>page.evaluate(()=>window.dungeonDebug.state);
async function solve(player,t){const root=page.locator(`.input-pad[data-player="${player}"]`);for(let i=0;i<t.solution.ids.length;i++){if(i)await root.locator(`[data-op="${t.solution.ops[i-1]}"]`).tap();await root.locator(`[data-dice="${t.solution.ids[i]}"]`).tap();}await root.locator('[data-action=submit]').tap();}
async function campaign(players,policy,mode='sequential',limit=65){await start(players,mode);const turns=[0,0,0,0,0];let guard=0,lastTurn=-1;
 while(guard++<limit){let s=await state();if(['clear','gameover'].includes(s.phase))break;if(s.phase==='reward'){await page.locator('[data-action=next-monster]').tap();await page.waitForFunction(()=>window.dungeonDebug.timer.running);s=await state();}
 if(s.phase==='resolution'||s.phase==='enemy'){await page.evaluate(()=>window.dungeonDebug.skip());await page.waitForFunction(()=>window.dungeonDebug.timer.running||['clear','reward','gameover'].includes(window.dungeonDebug.state.phase));continue;}
 if(s.phase!=='playing')throw Error('Unexpected '+s.phase);await page.waitForFunction(()=>window.dungeonDebug.timer.running);s=await state();if(lastTurn!==s.turn){lastTurn=s.turn;turns[s.monsterIndex]++;}
 assert.equal(await page.locator('#monster-hp-text').textContent(),`${s.monsterHP} / ${s.monsterMaxHP}`);const prepared=await page.evaluate(async policy=>{const {plan}=await import('/tests/BalanceStrategies.js');const goals=plan(window.dungeonDebug.state,policy);return {ids:goals.map(t=>t.id),scroll:window.dungeonDebug.state.scrollIndex};},policy);
 if(s.scrolls.length)await page.locator('#scroll-select').selectOption(String(prepared.scroll));
 const before=s.monsterHP;for(const id of prepared.ids){s=await state();const player=s.actionsDone.findIndex(x=>!x),t=s.targets.find(t=>t.id===id);if(player<0)break;await solve(player,t);}
 s=await state();while(s.phase==='playing'){const player=s.actionsDone.findIndex(x=>!x);await page.locator(`.input-pad[data-player="${player}"] [data-action=pass]`).tap();s=await state();}
 // Resolving through the real UI director; SKIP accelerates repeated presentations only.
 if(await page.locator('[data-action=presentation-skip]').count())await page.locator('[data-action=presentation-skip]').dispatchEvent('click');await page.waitForFunction(()=>window.dungeonDebug.timer.running||['clear','reward','gameover'].includes(window.dungeonDebug.state.phase));
 if(policy==='defense-all'&&lastTurn>=10)break;
 }
 const end=await state(),result={players,mode,policy,phase:end.phase,turns,hp:end.hero.hp,shield:end.hero.shield};runs.push(result);console.log(JSON.stringify(result));return result;
}
if(process.argv.includes('--balanced-only')){const r=await campaign(4,'balanced');assert.equal(r.phase,'clear');assert.deepEqual(errors,[]);const file=path.join(__dirname,'..','BROWSER-BALANCE-RESULTS.json'),fs=require('node:fs');const prior=JSON.parse(fs.readFileSync(file,'utf8'));for(const row of prior)if(row.policy==='balanced')row.policy='one-defense';prior.push(r);fs.writeFileSync(file,JSON.stringify(prior,null,2));await browser.close();return;}
for(const players of [1,2,3,4]){const r=await campaign(players,'adaptive');assert.equal(r.phase,'clear');if(players===4){assert.equal(r.turns[0],3);assert.ok(r.turns[1]>=3);assert.ok(r.turns[4]>=5);await page.screenshot({path:path.join(__dirname,'..','preview-v5-strategy-clear.png'),fullPage:true});}}
for(const policy of ['attack-all','defense-all','one-defense','balanced','attack-S','defense-S']){const r=await campaign(4,policy);if(policy==='attack-all')assert.equal(r.phase,'gameover');if(policy==='defense-all'){assert.equal(r.phase,'playing');assert.equal((await state()).monsterHP,230);}if(['balanced','attack-S','defense-S'].includes(policy))assert.equal(r.phase,'clear');}
await page.setViewportSize({width:1920,height:1080});const board=await campaign(4,'adaptive','simultaneous');assert.equal(board.phase,'clear');assert.deepEqual(errors,[]);require('node:fs').writeFileSync(path.join(__dirname,'..','BROWSER-BALANCE-RESULTS.json'),JSON.stringify(runs,null,2));console.log('PASS actual touch UI campaigns: all party sizes, all six policies, 4-pad simultaneous, scaled HP and existing cutscenes');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
