import test from 'node:test';import assert from 'node:assert/strict';import {BalanceProfiles,encounterStats} from '../src/BalanceSystem.js';import {MonsterData} from '../src/MonsterData.js';import {createState} from '../src/GameState.js';import {CombatSystem} from '../src/CombatSystem.js';import {GameConfig} from '../src/GameConfig.js';import {simulate} from './BalanceStrategies.js';
test('party profiles are sublinear and retain four-player skeleton baseline',()=>{assert.equal(encounterStats(0,4).hp,230);assert.equal(encounterStats(0,4).attack,8);for(const p of BalanceProfiles){assert.ok(p.hp.every((n,i)=>!i||n>p.hp[i-1]));assert.ok(p.hp[3]<p.hp[0]*4);assert.equal(p.hp[3],MonsterData.find(m=>m.id===p.id).hp);}});
test('all four-player later monsters exceed previous pressure and have bounded predictable patterns',()=>{for(let i=1;i<5;i++){assert.ok(encounterStats(i,4).hp>encounterStats(i-1,4).hp);assert.ok(encounterStats(i,4).attack>encounterStats(i-1,4).attack);for(let turn=1;turn<=100;turn++){const stats=encounterStats(i,4,turn);assert.ok(stats.attack<GameConfig.heroHP);assert.ok(BalanceProfiles[i].specials.includes(stats.special));}}assert.equal(encounterStats(1,4,2).special,'none');assert.equal(encounterStats(2,4,2).special,'none');assert.equal(encounterStats(4,4,2).special,'stone');});
test('scaled HP and exact upcoming damage agree with initialized state and intent',()=>{for(let p=1;p<=4;p++){const s=createState(p),c=new CombatSystem(s);assert.equal(s.monsterHP,encounterStats(0,p).hp);c.startTurn();assert.equal(s.intent.attack,encounterStats(0,p).attack);s.phase='reward';c.nextMonster();assert.equal(s.monsterMaxHP,encounterStats(1,p).hp);assert.equal(s.monsterHP,s.monsterMaxHP);assert.equal(s.intent.attack,encounterStats(1,p).attack);}});
test('all-in becomes unsafe; pure defense cannot progress; adaptive can clear every party size',()=>{for(let p=1;p<=4;p++){assert.equal(simulate(p,'attack-all').clear,false,`${p} player all-in`);assert.equal(simulate(p,'defense-all',1,{maxTurns:12}).clear,false);assert.equal(simulate(p,'adaptive').clear,true,`${p} player adaptive`);}const team=simulate(4,'adaptive');assert.equal(team.turns[0],3);assert.ok(team.turns[1]>=3&&team.turns[1]<=5);assert.ok(team.turns[4]>=5&&team.turns[4]<=9);assert.ok(team.hp>100);assert.ok(team.defenseActions>0&&team.attackActions>team.defenseActions);});
test('a late lethal attack cancels special and normal attack; insisting on defense delays a win',()=>{const s=createState(4),c=new CombatSystem(s);s.monsterIndex=1;s.monsterHP=20;c.startTurn();s.hero.hp=10;const t=s.targets.find(t=>t.side==='attack'&&t.grade==='S');c.submit(t.solution.ids,t.solution.ops);c.endTurn();c.resolveAll();assert.equal(s.phase,'reward');assert.equal(s.hero.hp,10);assert.equal(s.events.filter(e=>e.kind==='enemy'||e.kind==='steal').length,0);assert.equal(s.scrolls[0].uses,3);});
test('one missed defense is recoverable; repeated unprotected boss attacks lose',()=>{const s=createState(4),c=new CombatSystem(s);s.monsterIndex=4;s.monsterHP=MonsterData[4].hp;c.startTurn();c.endTurn();c.resolveAll();assert.equal(s.hero.hp,128);assert.equal(s.phase,'enemy');assert.equal(simulate(4,'attack-all',1,{isolated:4}).phase,'gameover');assert.equal(simulate(4,'adaptive',1,{isolated:4}).clear,true);});
test('goblin timing, poison cap and action lock remain unchanged in the new balance',()=>{const s=createState(4),c=new CombatSystem(s);s.monsterIndex=1;s.monsterHP=MonsterData[1].hp;c.startTurn();c.endTurn();c.resolveAll();c.startTurn();assert.equal(s.duration,45);assert.equal(s.intent.special,'none');c.endTurn();c.resolveAll();c.startTurn();assert.equal(s.duration,60);s.intent.special='poison';c.applySpecial();c.applySpecial();assert.equal(s.hero.poison,3);s.intent.special='web';c.applySpecial();c.endTurn();c.resolveAll();c.startTurn();assert.ok(s.actionsDone[s.blocked.slot]);assert.equal(s.actionsDone.filter(x=>!x).length,3);});

test('web and petrify rotate threatened players rather than repeatedly targeting only even slots',()=>{for(const index of [3,4]){const s=createState(4),c=new CombatSystem(s),slots=[];s.monsterIndex=index;s.monsterHP=MonsterData[index].hp;for(const turn of [2,4,6,8]){s.enemyTurn=turn-1;s.phase='ready';c.startTurn();slots.push(s.intent.slot);}assert.deepEqual(slots,[1,2,3,0]);}});
