import test from 'node:test';
import assert from 'node:assert/strict';
import {createState} from '../src/GameState.js';
import {CombatSystem} from '../src/CombatSystem.js';
import {prepareBoss,pressureBoss,bossDamage,bossTransitions,bossSpecial,tickBoss} from '../src/BossBattleSystem.js';
import {checkpointBoss,restoreBoss,validateBossCheckpoint} from '../src/BossCheckpoint.js';
import {syncEncounter} from '../src/EncounterData.js';
import {applyScrollEffect} from '../src/ScrollSystem.js';
import {ScrollData} from '../src/ScrollData.js';
import {RPGMode} from '../src/RPGMode.js';
const battle=type=>{const s=createState(1),c=new CombatSystem(s);c.configureEncounter(0,{id:'boss-test',enemies:[{type}]});c.startTurn();return {s,c,e:s.enemies[0]};};
for(const type of ['golem','treeGuardian','flameGiant']){
 test(type+' phases monotonic, multiple thresholds announced once',()=>{const {s,e}=battle(type);assert.deepEqual(bossTransitions(e).map(x=>x.phase),[1]);e.hp=Math.floor(e.maxHP*.2);prepareBoss(s,e);assert.deepEqual(bossTransitions(e).map(x=>x.phase),[2,3]);e.hp=e.maxHP;prepareBoss(s,e);assert.equal(e.boss.phase,3);assert.deepEqual(bossTransitions(e),[]);});
 test(type+' scroll never adds BREAK pressure; broken weakness amplifies it',()=>{const {s,e}=battle(type);e.boss.phase=3;const before=e.hp;applyScrollEffect(s,ScrollData.fire,e.id);assert.equal(e.boss.pressure,0);assert.equal(e.boss.seedPressure,0);const normal=before-e.hp;e.boss.breakTurns=2;const hp=e.hp;applyScrollEffect(s,ScrollData.fire,e.id);assert.ok(hp-e.hp>normal);});
 test(type+' BREAK gives no immediate damage and expires after two following turns',()=>{const {s,e}=battle(type);e.boss.phase=3;e.boss.seedTurns=2;const hp=e.hp;for(let i=0;i<4&&!e.boss.breakTurns;i++)pressureBoss(e,'A');assert.ok(e.boss.breakTurns);assert.equal(e.hp,hp);assert.equal(e.intent.special,'none');assert.ok(bossDamage(e,20)>20);tickBoss(s);assert.equal(e.boss.breakTurns,2);tickBoss(s);tickBoss(s);assert.equal(e.boss.breakTurns,0);});
 test(type+' checkpoint resumes exact remaining action without replay',()=>{const {s,c,e}=battle(type);bossTransitions(e);const t=s.targets.find(t=>t.side==='attack'&&t.grade==='S');c.submit(t.solution.ids,t.solution.ops);c.resolveNext();const cp=checkpointBoss(s);assert.equal(validateBossCheckpoint(cp),true);const next=battle(type);next.s.scrolls=structuredClone(s.scrolls);assert.ok(restoreBoss(next.s,cp));assert.equal(next.e.id,e.id);assert.equal(next.s.enemies[0].hp,e.hp);assert.deepEqual(bossTransitions(next.s.enemies[0]),[]);const hp=next.s.enemies[0].hp;for(const a of next.s.actionQueue)if(a.actionType==='scroll')a.status='cancelled';next.c.resolveAll();assert.equal(next.s.enemies[0].hp,hp);});
}
test('tree two A attacks on separate seed preparation turns cancel bounded regeneration',()=>{const {s,e}=battle('treeGuardian');e.hp-=30;assert.equal(pressureBoss(e,'A'),false);bossSpecial(s,e,'regenSeed');tickBoss(s);assert.equal(e.boss.seedTurns,1);assert.equal(pressureBoss(e,'A'),true);assert.equal(e.boss.seedTurns,0);assert.equal(e.hp,e.maxHP-30);});
test('tree seed healing is capped and respects the final phase',()=>{const {s,e}=battle('treeGuardian');e.boss.phase=3;e.boss.seedTurns=1;e.hp=e.maxHP-4;bossSpecial(s,e,'regenSeed');assert.equal(e.hp,e.maxHP);});
test('malformed checkpoint values are rejected',()=>{const {s}=battle('golem'),cp=checkpointBoss(s);for(const key of ['phase','breakTurns','seedTurns']){const bad=structuredClone(cp);bad.enemies[0].boss[key]=999;assert.equal(validateBossCheckpoint(bad),false);}const bad=structuredClone(cp);bad.enemies[0].hp=-1;assert.equal(validateBossCheckpoint(bad),false);});
test('golem C-only calculations still inflict damage without a rank gate',()=>{const {s,c}=battle('golem');s.hero.shield=9999;let turns=0;while(s.monsterHP>0&&turns++<60){if(s.phase==='enemy')c.startTurn();const t=s.targets.find(t=>t.side==='attack'&&t.grade==='C');c.submit(t.solution.ids,t.solution.ops);c.resolveAll();}assert.equal(s.monsterHP,0);assert.ok(turns>5);});
test('real RPG save/load retains boss HP, shield, phase acknowledgement and uncast scroll reference',()=>{const records=new Map(),storage={getItem:k=>records.get(k)||null,setItem:(k,v)=>records.set(k,v)},r=new RPGMode(storage);r.create('보스 용사');const p=r.data.progress;p.clearedDungeons=['old-prison'];p.rewardedQuests=['forest-road'];p.questProgress={'forest-road':{count:1,scrolls:[]}};p.unlockedDungeons.push('cursed-forest');r.enterDungeon('cursed-forest');r.run.nextEncounter=4;const {state:s,combat:c}=r.createBattle();s.hero.shield=77;bossTransitions(s.enemies[0]);const t=s.targets.find(t=>t.side==='attack'&&t.grade==='S');c.submit(t.solution.ids,t.solution.ops);const event=c.resolveNext();r.onBattleEvent(event,s);assert.equal(r.saveInfo.ok,true);const restored=new RPGMode(storage);assert.equal(restored.load().status,'ready');const next=restored.createBattle();assert.equal(next.state.phase,'resolution');assert.equal(next.state.enemies[0].hp,s.enemies[0].hp);assert.equal(next.state.hero.shield,77);assert.deepEqual(bossTransitions(next.state.enemies[0]),[]);const scroll=next.state.actionQueue.find(a=>a.actionType==='scroll');assert.equal(scroll.scrollSlot,next.state.scrolls[0]);const hp=next.state.enemies[0].hp;next.combat.resolveNext();assert.ok(next.state.enemies[0].hp<hp);assert.equal(next.state.stats.attack.S,1);});
test('actual core BREAK freezes heat on trigger and two following turns, then resumes',()=>{const encounter={id:'heat-test',enemies:[{type:'flameGiant'}]},s=createState(1,'sequential',{mode:'rpg',dungeonId:'burning-mine',heroMaxHP:500,encounters:[encounter],maxMitigationRatio:0}),c=new CombatSystem(s);c.configureEncounter(0);s.enemies[0].hp=70;c.startTurn();s.hero.shield=999;const a=s.targets.find(t=>t.side==='attack'&&t.grade==='A');c.submit(a.solution.ids,a.solution.ops);c.resolveAll();assert.equal(s.enemies[0].boss.breakTurns,2);assert.equal(s.heatPoints,0);for(let i=0;i<2;i++){c.startTurn();const t=s.targets.find(t=>t.side==='defense'&&t.grade==='A');c.submit(t.solution.ids,t.solution.ops);c.resolveAll();assert.equal(s.heatPoints,0);}c.startTurn();const t=s.targets.find(t=>t.side==='defense'&&t.grade==='S');c.submit(t.solution.ids,t.solution.ops);c.resolveAll();assert.equal(s.heatPoints,2);assert.equal(s.enemies[0].boss.phase,3);});
