import {legacyV34} from './legacy-v34-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {preparedCastle,enterCastle} from './castle-fixture.mjs';import {preparedCanyon} from './canyon-fixture.mjs';import {RPGMode} from '../src/RPGMode.js';import {validateSave} from '../src/SaveSystem.js';import {CastleDungeon,CastleMonsterData} from '../src/CastleData.js';import {castleDamage,elitePressure,assistElite,castleSpecial,castleTurn,tickCastle} from '../src/CastleSystem.js';import {chaosMasked} from '../src/ChaosSystem.js';import {checkpointBoss,validateBossCheckpoint} from '../src/BossCheckpoint.js';import {castleRestPending,castleRestHTML,castleSceneHTML,castleDoorHTML} from '../src/CastleStory.js';import {syncEncounter} from '../src/EncounterData.js';import {resolveTower} from './chaos-fixture.mjs';import {dungeonCollection} from '../src/CollectionSystem.js';
test('six encounters with three elites, no king or new boss',()=>{assert.equal(CastleDungeon.encounters.length,6);assert.equal(CastleMonsterData.length,3);assert.ok(CastleMonsterData.every(m=>!m.boss));assert.deepEqual(CastleDungeon.encounters.at(-1).enemies.map(e=>e.type),['royalGuard','abyssMage','sealGuardian']);});
test('third seal, town and Act III required to unlock castle',()=>{const {r}=preparedCanyon();assert.equal(r.finishCastleOpening(),false);assert.equal(r.enterDungeon('demon-castle'),false);const {r:next}=preparedCastle();assert.equal(next.enterDungeon('demon-castle'),true);});
test('v32 save migrates without changing inventory, resources or relationships',()=>{const {r}=preparedCanyon(),old=legacyV34(structuredClone(r.data));for(const k of ['actThreeSeen','eliaTruthSeen','throneReached','throneSceneSeen'])delete old.progress.campaign[k];const fresh=validateSave(old);assert.deepEqual(fresh.character,old.character);assert.deepEqual(fresh.progress.mercenaryRelations,old.progress.mercenaryRelations);assert.equal(fresh.progress.campaign.actThreeSeen,false);});
for(const key of ['actThreeSeen','eliaTruthSeen','throneReached','throneSceneSeen'])test('reject malformed Act III '+key,()=>{const {r}=preparedCastle();r.data.progress.campaign[key]=1;assert.throws(()=>validateSave(r.data));});
for(let index=0;index<6;index++)test('mixed-mechanic exact F5 checkpoint '+index,()=>{const {r,state:s,storage}=enterCastle(index);s.seconds=43;s.elapsed=17;r.captureBattle(s);assert.equal(r.save(),true);const cp=checkpointBoss(s);assert.ok(cp.castleRun);assert.equal(validateBossCheckpoint(cp),true);const next=new RPGMode(storage);assert.equal(next.load().status,'ready');const b=next.createBattle();for(const key of ['targets','dice','enemies','seconds','castle','chaos','chaosTurn','canyon','heatPoints','morale'])assert.deepEqual(b.state[key],s[key],key);});
test('castle checkpoint cannot contain the king, wrong elite or another region',()=>{const {r,state:s}=enterCastle(5);const cp=checkpointBoss(s);cp.enemies[0].type='darkKnight';assert.equal(validateBossCheckpoint(cp),false);r.run.bossCheckpoint={...checkpointBoss(s),castleRun:true};r.run.dungeonId='sky-canyon';assert.throws(()=>validateSave(r.data));});
test('illusion corridor keeps all numbers readable even at maximum chaos',()=>{const {state:s,combat:c}=enterCastle(2);s.chaos.level=3;s.chaos.mask=true;s.chaos.shuffle=true;s.phase='enemy';c.startTurn();s.elapsed=12;assert.equal(s.chaosTurn.maskIds.length,0);assert.ok(s.targets.every(t=>!chaosMasked(s,t)));});
test('barrier protects allies only and ends immediately when guardian dies',()=>{const {state:s}=enterCastle(5),g=s.enemies[2];assert.equal(castleDamage(s,s.enemies[0],40),30);assert.equal(castleDamage(s,g,40),40);g.hp=0;assert.equal(castleDamage(s,s.enemies[0],40),40);});
test('A/S BREAK removes barrier, lasts two enemy turns and boosts damage',()=>{const {state:s}=enterCastle(5),g=s.enemies[2];assert.equal(elitePressure(s,g,'A'),false);assert.equal(elitePressure(s,g,'S'),true);assert.equal(s.castle.barrierId,null);assert.equal(castleDamage(s,g,40),54);tickCastle(s);assert.equal(g.elite.breakTurns,2);tickCastle(s);tickCastle(s);assert.equal(g.elite.breakTurns,0);});
test('support pressure assists but cannot automatically BREAK',()=>{const {state:s}=enterCastle(5),g=s.enemies[2];for(let i=0;i<20;i++)assistElite(s,g);assert.equal(g.elite.pressure,2.75);assert.equal(g.elite.breakTurns,0);assert.equal(elitePressure(s,g,'A'),true);});
for(const special of ['royalGuard','abyssCurse','sealBarrier'])test('Defense S cancels '+special,()=>{const {state:s,combat:c}=enterCastle(5),e=s.enemies.find(e=>e.intent.special===special),hp=s.hero.hp;s.enemyResolutionIndex=s.enemies.indexOf(e);s.blockedIds.add(e.id);assert.equal(c.applySpecial().kind,'block');assert.equal(s.hero.hp,hp);assert.equal(s.hero.poison,0);});
test('curse and strong counter use existing poison/shield rules',()=>{const {state:s}=enterCastle(5);s.hero.shield=4;const hp=s.hero.hp;castleSpecial(s,s.enemies[0],'royalGuard');assert.equal(s.hero.hp,hp);assert.equal(s.hero.shield,0);castleSpecial(s,s.enemies[1],'abyssCurse');assert.equal(s.hero.poison,2);});
function restFixture(){const v=enterCastle(3),{r,state:s,combat:c}=v;s.enemies.forEach(e=>e.hp=0);syncEncounter(s);c.win();r.awardBattle(s);const type=s.lootCandidates[0];c.chooseReward(type);r.recordLoot(s,type);r.character.hp=Math.floor(r.character.maxHP*.3);s.hero.hp=r.character.hp;r.captureBattle(s);r.save();return v;}
test('35% rest clamps maxHP, persists and cannot repeat after F5',()=>{const {r,storage}=restFixture(),hp=r.character.hp,max=r.character.maxHP;assert.ok(castleRestPending(r.run));assert.equal(r.restCastle(),Math.round(max*.35));assert.equal(r.character.hp,hp+Math.round(max*.35));const next=new RPGMode(storage);assert.equal(next.load().status,'ready');assert.equal(next.restCastle(),false);assert.equal(next.character.hp,r.character.hp);});
test('rest at full HP consumes once even when gain is zero',()=>{const {r}=restFixture();r.character.hp=r.character.maxHP;assert.equal(r.restCastle(),0);assert.equal(r.restCastle(),false);assert.ok(r.run.restUsed);});
test('cannot leave rest without resting and reading truth, no shopping or selling',()=>{const {r,state:s,combat:c}=restFixture();assert.equal(r.advanceBattle(s,c),false);r.restCastle();r.applyCharacter(s);assert.equal(r.advanceBattle(s,c),false);assert.equal(r.buy('steel_sword').ok,false);assert.equal(r.sell('steel_sword').ok,false);assert.equal(r.finishCastleTruth(),true);assert.equal(r.advanceBattle(s,c),true);assert.equal(s.encounterIndex,4);assert.ok(r.run.restDeparted);});
test('Elia truth appears through record without Elia and directly with Elia',()=>{const {r}=restFixture(),p=r.data.progress;let html=castleSceneHTML('castle-truth',2,p);assert.match(html,/기억의 수정/);assert.match(html,/숫자, 연산, 논리/);p.activeMercenary='elia';html=castleSceneHTML('castle-truth',0,p);assert.match(html,/동행 엘리아/);assert.match(html,/나는 알고 있었어/);});
test('rest gear only contains owned equipment, comparison and no sale controls',()=>{const {r}=restFixture();r.castleRestTab='gear';r.character.inventory.items=['steel_sword'];const html=castleRestHTML(r);assert.match(html,/장착/);assert.match(html,/equipment-comparison/);assert.doesNotMatch(html,/data-action="rpg-sell"|data-action="rpg-buy"/);});
test('final elite clear is recorded once, throne button never creates a battle',()=>{const {r,state:s,combat:c}=enterCastle(5);r.data.progress.campaign.eliaTruthSeen=true;s.enemies.forEach(e=>e.hp=0);syncEncounter(s);c.win();r.awardBattle(s);c.chooseReward(s.lootCandidates[0]);r.recordLoot(s,s.lootAcquired);const xp=r.character.exp,gold=r.character.gold;assert.equal(r.awardBattle(s),false);assert.match(castleDoorHTML(r),/이 문 너머에 마왕/);assert.equal(r.reachThrone(),true);assert.equal(r.reachThrone(),true);assert.equal(r.character.exp,xp);assert.equal(r.character.gold,gold);assert.ok(r.data.progress.campaign.throneSceneSeen);assert.ok(s.enemies.every(e=>!e.boss));assert.equal(r.save(),true);assert.equal(r.returnToTown(),'clear');});
test('castle collection has no invented boss unique entry',()=>{const {r}=preparedCastle();assert.equal(dungeonCollection(r.data.progress,CastleDungeon).boss,undefined);});

for(const merc of ['rowen','bram','sera','luna','kain','elia'])test('sixth encounter saves actual '+merc+' contract support',()=>{const {r,storage}=preparedCastle();r.hire(merc);r.enterDungeon('demon-castle');r.run.nextEncounter=5;const {state:s,combat:c}=r.createBattle();s.hero.shield=400;resolveTower(r,s,c,merc==='bram'?'defense':'attack','S',undefined,s.enemies[0].id);r.captureBattle(s);assert.equal(r.save(),true);const next=new RPGMode(storage);assert.equal(next.load().status,'ready');assert.deepEqual(next.data.progress.mercenaryContractState,r.data.progress.mercenaryContractState);});
test('forge heat at 12 and burn persist exactly through F5',()=>{const {r,state:s,storage}=enterCastle(3);s.heatPoints=12;s.hero.burn=2;r.captureBattle(s);assert.equal(r.save(),true);const next=new RPGMode(storage);assert.equal(next.load().status,'ready');const resumed=next.createBattle();assert.equal(resumed.state.heatPoints,12);assert.equal(resumed.state.hero.burn,2);});
test('forged rest metadata cannot turn an unused rest into a repeated heal',()=>{const {r}=enterCastle(3);r.run.restHeal=40;assert.throws(()=>validateSave(r.data));});
