const path=require('node:path');let pw;try{pw=require('playwright')}catch{pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}const assert=require('node:assert/strict');
(async()=>{const browser=await pw.chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.setDefaultTimeout(12000);
const state=()=>page.evaluate(()=>window.dungeonDebug.state);
async function start(mode='sequential',production=false){await page.goto(`http://127.0.0.1:4173/${production?'dist/index.html':''}?debug=1`);await page.locator('[data-action=setup]').tap();await page.locator('[data-players="4"]').tap();await page.locator(`[data-mode="${mode}"]`).tap();await page.locator('[data-action=story]').tap();await page.locator('[data-action=start]').tap();await page.locator('[data-action=presentation-skip]').tap();await page.waitForFunction(()=>window.dungeonDebug.timer.running);}
async function encounter(index){await page.locator('[data-action=debug-toggle]').tap();await page.locator(`[data-debug="${index==='triple'?'triple':'encounter-'+index}"]`).tap();await page.locator('[data-action=presentation-skip]').dispatchEvent('click');await page.waitForFunction(()=>window.dungeonDebug.timer.running);await page.locator('[data-action=debug-toggle]').tap();}
async function solve(p,side,grade){const s=await state(),t=s.targets.find(t=>t.side===side&&t.grade===grade&&!t.used),root=page.locator(`.input-pad[data-player="${p}"]`);for(let i=0;i<t.solution.ids.length;i++){if(i)await root.locator(`[data-op="${t.solution.ops[i-1]}"]`).tap();await root.locator(`[data-dice="${t.solution.ids[i]}"]`).tap();}await root.locator('[data-action=submit]').tap();}
async function target(p,index){const s=await state();await page.locator(`.player-target-choice [data-action=choose-target][data-player-id="${p}"][data-enemy="${s.enemies[index].id}"]`).tap();}
async function skip(){await page.locator('[data-action=presentation-skip]').dispatchEvent('click');}
for(const [width,height,mode]of [[1024,768,'sequential'],[1920,1080,'simultaneous']]){await page.setViewportSize({width,height});await start(mode);for(const [index,n]of [[0,1],[1,2],['triple',3]]){await encounter(index);assert.equal(await page.locator('.enemy-card').count(),n);assert.equal(await page.locator('.combat-target').count(),8);assert.equal(await page.locator('.input-pad').count(),mode==='sequential'?1:4);const box=await page.locator('.pad-deck').boundingBox();assert.ok(box.y+box.height<=height+1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const card of await page.locator('.enemy-card').all()){const c=await card.boundingBox();assert.ok(c.width>=140);assert.ok(await card.locator('.enemy-plan').isVisible());}await page.screenshot({path:path.join(__dirname,`../preview-v12-${mode}-${n}.png`)});}console.log('PASS layout',mode,'1 / 2 / 3 enemies, eight common goals, input pads visible');}
// Sequential editing uses a separate dialog even after the player's pad has changed.
await start();await encounter(1);await solve(0,'attack','A');await target(0,0);await page.locator('[data-action=change-target][data-player-id="0"]').tap();assert.equal(await page.locator('.edit-target-overlay').count(),1);await target(0,1);assert.equal((await state()).actionQueue[0].enemyId,(await state()).enemies[1].id);assert.equal(await page.locator('.edit-target-overlay').count(),0);assert.equal(await page.evaluate(()=>window.dungeonDebug.timer.running),true);console.log('PASS sequential edit after current player changed');
// Independent simultaneous choices: all are math submissions through actual touch pads.
await start('simultaneous');await encounter('triple');await solve(0,'attack','A');await solve(1,'attack','B');assert.equal(await page.locator('.player-target-choice').count(),2);assert.equal(await page.evaluate(()=>window.dungeonDebug.timer.running),false);const seconds=(await state()).seconds;await page.waitForTimeout(650);assert.equal((await state()).seconds,seconds);await target(0,2);assert.equal(await page.evaluate(()=>window.dungeonDebug.timer.running),false);await target(1,1);assert.equal(await page.evaluate(()=>window.dungeonDebug.timer.running),true);await page.locator('[data-action=change-target][data-player-id="0"]').tap();await target(0,0);assert.equal((await state()).actionQueue[0].enemyId,(await state()).enemies[0].id);await solve(2,'defense','S');await target(2,1);const before=await state();await page.locator('.input-pad[data-player="3"] [data-action=pass]').tap();await skip();await page.waitForFunction(t=>window.dungeonDebug.state.turn>t&&window.dungeonDebug.timer.running,before.turn);const after=await state();assert.equal(after.enemies[0].hp,before.enemies[0].hp-25);assert.equal(after.enemies[1].hp,before.enemies[1].hp-16);assert.equal(after.stats.blocks,1);assert.equal(after.curse,false);assert.equal(after.duration,45);console.log('PASS simultaneous choices, timer reference count, target edit, single Defense S with other special active');
// Scroll primary targets and real multi-target impacts.
for(const type of ['fire','lightning','iceStorm','meteor','heal','shield']){await start();await encounter('triple');await page.evaluate(type=>{const d=window.dungeonDebug;const slot=d.state.scrolls.find(s=>s.type===type);if(slot)slot.uses=2;else d.state.scrolls.push({type,uses:2});d.state.hero.hp=100;},type);await solve(0,'attack','S');await target(0,2);for(const p of [1,2,3])await page.locator(`.input-pad[data-player="${p}"] [data-action=pass]`).tap();await page.locator('.scroll-choice-overlay').waitFor();const before=await state();await page.locator(`.scroll-choice-overlay [data-type="${type}"]`).tap();if(['fire','lightning','meteor'].includes(type)){await page.locator('.target-scroll-overlay').waitFor();assert.equal(await page.evaluate(()=>window.dungeonDebug.timer.running),false);await page.locator(`.target-scroll-overlay [data-enemy="${before.enemies[0].id}"]`).tap();}else assert.equal(await page.locator('.target-scroll-overlay').count(),0);await page.locator('.fx-magic').waitFor();const result=await state();const delta=result.enemies.map((e,i)=>before.enemies[i].hp-e.hp);assert.deepEqual(delta,{fire:[22,0,0],lightning:[26,18,12],iceStorm:[16,16,16],meteor:[48,12,12],heal:[0,0,0],shield:[0,0,0]}[type]);assert.equal(result.scrolls.find(s=>s.type===type).uses,1);if(type==='iceStorm')await page.screenshot({path:path.join(__dirname,'../preview-v12-iceStorm.png')});await skip();await page.waitForFunction(t=>window.dungeonDebug.state.turn>t&&window.dungeonDebug.timer.running,before.turn);console.log('PASS real scroll target',type,delta);}
// Real six-fight campaign. Automatic expression solver supplies valid expressions; UI submits all actions and loot.
await page.setViewportSize({width:1920,height:1080});await start('simultaneous');let turns=Array(6).fill(0),guard=0;
while(guard++<180){const s=await state();if(['clear','gameover'].includes(s.phase)){if(s.phase==='clear'&&!s.lootChosen){await page.locator('[data-action=loot-choice]').first().tap();}assert.equal(s.phase,'clear','campaign should be clear');break;}
 if(s.phase==='reward'){await page.locator('[data-action=loot-choice]').first().tap();const hp=(await state()).hero.hp;await page.locator('[data-action=next-monster]').tap();await skip();await page.waitForFunction(()=>window.dungeonDebug.timer.running);assert.equal((await state()).hero.hp,hp);assert.equal((await state()).hero.shield,0);continue;}
 if(s.phase!=='playing'){await page.waitForTimeout(50);continue;}await page.waitForFunction(()=>window.dungeonDebug.timer.running);turns[s.encounterIndex]++;
 const alive=s.enemies.filter(e=>e.hp>0),focus=alive.find(e=>e.type==='goblin')||alive[0];
 let slots=s.actionsDone.map((done,p)=>done?-1:p).filter(p=>p>=0);const incoming=alive.reduce((n,e)=>n+e.intent.attack,0)+(s.hero.poison?5:0),shield=s.hero.shield;let defenseNeeded=Math.max(0,incoming-shield),grades=[];
 for(const g of ['S','A','B']){if(defenseNeeded<=0||grades.length>=slots.length-1)break;grades.push(['defense',g]);defenseNeeded-=g==='B'?16:26;}
 for(const g of ['S','A','B','C'])if(grades.length<slots.length)grades.push(['attack',g]);
 for(const [i,[side,g]]of grades.entries()){const p=slots[i];await solve(p,side,g);const cur=await state();if(cur.choices[p]){const targetEnemy=side==='attack'?focus:alive.find(e=>e.intent.special!=='none')||alive[0];await page.locator(`.player-target-choice [data-player-id="${p}"][data-enemy="${targetEnemy.id}"]`).tap();}}
 // Use offense or defense scroll selected by current survival need.
 const picking=async()=>{if(await page.locator('.scroll-choice-overlay').count()){const ss=await state();const pick=ss.hero.hp<110?ss.scrolls.find(x=>x.type==='heal'):null;await page.locator(pick?`.scroll-choice-overlay [data-type="${pick.type}"]`:'.scroll-choice-overlay [data-action=cast-choice]').first().tap();}if(await page.locator('.target-scroll-overlay').count())await page.locator('.target-scroll-overlay [data-action=scroll-target]').first().tap();};
 await skip();for(let j=0;j<80;j++){await picking();const cur=await state();if(cur.phase!=='resolution')break;await page.waitForTimeout(30);}await page.waitForFunction(()=>window.dungeonDebug.state.phase!=='resolution');if((await state()).phase==='playing')await page.waitForFunction(()=>window.dungeonDebug.timer.running);
}
assert.ok(guard<180);assert.ok(turns.every(n=>n>0));console.log('PASS six encounters campaign turns',turns,'HP',(await state()).hero.hp);
await start('sequential',true);await encounter('triple');assert.equal(await page.locator('.enemy-card').count(),3);console.log('PASS production build multi-enemy scene');await page.goto('http://127.0.0.1:4173/');assert.equal(await page.evaluate(()=>typeof window.dungeonDebug),'undefined');assert.deepEqual(errors,[]);console.log('PASS no browser errors, student debug hidden');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
