import test from 'node:test';
import assert from 'node:assert/strict';
import {createState} from '../src/GameState.js';
import {CombatSystem} from '../src/CombatSystem.js';
import {EncounterData,livingEnemies,syncEncounter} from '../src/EncounterData.js';
import {ScrollData} from '../src/ScrollData.js';
import {useScroll} from '../src/ScrollSystem.js';
import {StatusRules,applyStatus} from '../src/StatusEffectSystem.js';
const custom=types=>({id:'test',name:'테스트 전투',enemies:types.map(type=>({type,hpModifier:.5,attackModifier:.5})),rewardModifier:1});
const game=(types=['goblin','orc'],players=4)=>{const s=createState(players,'simultaneous'),c=new CombatSystem(s,Math.random,()=>.2);c.configureEncounter(3,custom(types));c.startTurn();return {s,c};};
function submit(c,side,grade,p=0,index=0){const s=c.state,t=s.targets.find(t=>t.side===side&&t.grade===grade);c.submit(t.solution.ids,t.solution.ops,p);if(s.choices[p])assert.equal(c.chooseTarget(p,s.enemies[index].id),true);return s.actionQueue.find(a=>a.playerId===p&&a.actionType===side);}
function finish(c){c.endTurn();c.resolveAll();}
for(const n of [2,3])test(`${n} enemies: target claim is atomic, pauses input and stores chosen instance`,()=>{const {s,c}=game(Array(n).fill('goblin'));const t=s.targets.find(t=>t.side==='attack'&&t.grade==='A');c.submit(t.solution.ids,t.solution.ops,0);assert.equal(t.used,true);assert.equal(s.actionsDone[0],false);assert.equal(c.endTurn(),false);const seconds=s.seconds;c.timeUpdate(0);assert.equal(s.seconds,seconds);assert.throws(()=>c.submit(t.solution.ids,t.solution.ops,1));assert.equal(s.actionsDone[1],false);c.chooseTarget(0,s.enemies[n-1].id);const before=s.enemies.map(e=>e.hp);finish(c);assert.equal(s.enemies[n-1].hp,before[n-1]-26);assert.equal(s.enemies[0].hp,before[0]);});
test('simultaneous choices stay pending independently and may focus the same enemy',()=>{const {s,c}=game();for(const [p,g]of ['A','B'].entries()){const t=s.targets.find(t=>t.side==='attack'&&t.grade===g);c.submit(t.solution.ids,t.solution.ops,p);}assert.equal(Object.keys(s.choices).length,2);c.chooseTarget(1,s.enemies[0].id);assert.equal(c.awaitingChoices(),true);c.chooseTarget(0,s.enemies[0].id);assert.equal(c.awaitingChoices(),false);const hp=s.enemies[0].hp;finish(c);assert.equal(hp-s.enemies[0].hp,26+16);});
test('split attacks damage independently; editable target does not duplicate player action',()=>{const {s,c}=game();submit(c,'attack','A',0,0);submit(c,'attack','B',1,0);assert.equal(c.changeTarget(1,s.enemies[1].id),true);const hp=s.enemies.map(e=>e.hp);finish(c);assert.equal(hp[0]-s.enemies[0].hp,26);assert.equal(hp[1]-s.enemies[1].hp,15);assert.equal(s.stats.attack.A,1);assert.equal(c.changeTarget(0,s.enemies[1].id),false);});
test('overkill retargets in data order and dead enemies have neither normal nor special actions',()=>{const {s,c}=game();s.enemies[0].hp=1;syncEncounter(s);submit(c,'attack','C',0,0);submit(c,'attack','A',1,0);const hp=s.enemies[1].hp;finish(c);assert.equal(s.enemies[1].hp,hp-25);assert.ok(s.events.some(e=>e.retargeted?.includes('이미 쓰러져')));assert.equal(s.events.filter(e=>e.enemyId===s.enemies[0].id&&['enemy','steal'].includes(e.kind)).length,0);assert.equal(s.phase,'enemy');});
test('Defense S blocks exactly selected special, keeps both normal attacks and A shield',()=>{const {s,c}=game();submit(c,'defense','S',0,1);finish(c);assert.equal(s.events.filter(e=>e.kind==='enemy').length,2);assert.equal(s.stolen,true);assert.equal(s.curse,false);assert.equal(s.stats.blocks,1);assert.equal(s.hero.shield,0);assert.equal(s.hero.hp,180-(16+19-26));});
test('Defense S alternate target leaves curse active and time theft blocked',()=>{const {s,c}=game();submit(c,'defense','S',0,0);finish(c);assert.equal(s.curse,true);assert.equal(s.stolen,false);});
test('mid-input curse respects selected enemy rather than blanket block',()=>{for(const index of [0,1]){const {s,c}=game();submit(c,'defense','S',0,index);c.timeUpdate(40);assert.equal(s.curse,index===0);}});
test('shared shield is consumed by enemies in data order',()=>{const {s,c}=game();s.hero.shield=20;finish(c);const events=s.events.filter(e=>e.kind==='enemy');assert.equal(events[0].absorbed,16);assert.equal(events[1].absorbed,4);assert.equal(events[1].hpDamage,15);});
test('multiple time thieves use strongest time floor without addition',()=>{const {s,c}=game(['goblin','goblin','goblin']);s.enemies[1].intent.seconds=30;finish(c);assert.equal(s.stolenDuration,30);c.startTurn();assert.equal(s.duration,30);assert.equal(s.stolenDuration,null);});
for(const players of [1,2,3,4])test(`overlapping webs and stone leave one actionable player (${players}P)`,()=>{const {s,c}=game(['spider','golem','spider'],players);for(const [i,e]of s.enemies.entries())e.intent={attack:0,special:i===1?'stone':'web',slot:i%players,locks:2};finish(c);c.startTurn();assert.ok(s.actionsDone.filter(x=>!x).length>=1);assert.ok(s.blockedList.length<=players-1);});
test('poison refreshes at bounded three turns; all statuses declare stacking metadata',()=>{const {s}=game();for(let i=0;i<20;i++)applyStatus(s,'poison',{});assert.equal(s.hero.poison,3);for(const rule of Object.values(StatusRules))for(const field of ['stack','maxStack','duration','refresh','dispellable'])assert.ok(field in rule);});
for(const type of ['fire','ice','lightning','iceStorm','meteor','heal','shield','cleanse','time'])test(`scroll ${type}: real target behavior, one charge, preserved unrelated HP`,()=>{const {s}=game(['goblin','orc','skeleton']);s.enemies.forEach(e=>e.hp=100);syncEncounter(s);s.hero.hp=100;s.hero.poison=3;s.curse=true;s.stolen=true;s.nextBlockedList=[{slot:1,type:'web'}];s.nextBlocked=s.nextBlockedList[0];s.scrolls=[{type,uses:1}];const result=useScroll(s,s.scrolls[0],s.enemies[1].id);assert.equal(s.scrolls.length,0);assert.equal(s.stats.scrolls,1);const hp=s.enemies.map(e=>e.hp);if(type==='fire')assert.deepEqual(hp,[100,78,100]);if(type==='ice'){assert.deepEqual(hp,[100,80,100]);assert.equal(s.enemies[1].weaken,.35);assert.equal(s.enemies[0].weaken,0);}if(type==='lightning')assert.deepEqual(hp,[82,74,88]);if(type==='iceStorm'){assert.deepEqual(hp,[84,84,84]);assert.ok(s.enemies.every(e=>e.weaken===.25));}if(type==='meteor')assert.deepEqual(hp,[88,52,88]);if(type==='heal')assert.equal(s.hero.hp,130);if(type==='shield')assert.equal(s.hero.shield,36);if(type==='cleanse'){assert.equal(s.hero.poison,0);assert.deepEqual(s.nextBlockedList,[]);assert.equal(s.curse,false);assert.equal(s.stolen,false);}if(type==='time')assert.equal(s.scrollStop,true);assert.equal(result.damage,[...result.impacts].reduce((n,e)=>n+e.damage,0));});
test('dead scroll target cannot be selected; valid selection only before cast',()=>{const {s,c}=game();submit(c,'attack','S');const a=s.actionQueue.find(a=>a.actionType==='scroll');s.enemies[1].hp=0;assert.equal(c.chooseScrollTarget(a,s.enemies[1].id),false);assert.equal(c.chooseScrollTarget(a,s.enemies[0].id),true);a.status='resolved';assert.equal(c.chooseScrollTarget(a,s.enemies[0].id),false);});
test('time stops all remaining enemies, but poison ticks once',()=>{const {s,c}=game(['spider','goblin']);s.hero.poison=3;submit(c,'attack','S');const a=s.actionQueue.find(a=>a.actionType==='scroll');s.scrolls.push({type:'time',uses:1});c.chooseScroll(a,1);finish(c);assert.equal(s.hero.hp,175);assert.equal(s.stolen,false);assert.equal(s.hero.poison,2);assert.equal(s.events.filter(e=>e.kind==='enemy'&&e.attack===0).length,2);c.startTurn();assert.equal(s.scrollStop,false);});
test('only final kill gives three cards once; HP and scroll inventory carry with shield reset',()=>{const {s,c}=game();s.enemies[0].hp=1;syncEncounter(s);submit(c,'attack','C');finish(c);assert.equal(s.phase,'enemy');assert.equal(s.lootCandidates,undefined);c.startTurn();s.enemies[1].hp=1;syncEncounter(s);submit(c,'attack','C');finish(c);assert.equal(s.phase,'reward');assert.equal(s.lootCandidates.length,3);c.chooseReward(s.lootCandidates[0]);const inventory=JSON.stringify(s.scrolls),hp=s.hero.hp;s.hero.shield=38;c.win();assert.equal(s.lootChosen,true);c.nextMonster();assert.equal(s.encounterIndex,4);assert.equal(s.hero.hp,hp);assert.equal(s.hero.shield,0);assert.equal(JSON.stringify(s.scrolls),inventory);});
test('six campaign encounters and custom triple are bounded, with single final boss',()=>{assert.equal(EncounterData.length,6);assert.equal(EncounterData[5].enemies[0].type,'golem');assert.equal(EncounterData[5].enemies.length,1);for(let i=0;i<6;i++){const {s,c}=game();c.configureEncounter(i);assert.ok(s.enemies.length>=1&&s.enemies.length<=3);}const {c}=game();assert.throws(()=>c.configureEncounter(0,custom(Array(4).fill('goblin'))));});


import {simulateEncounterCampaign} from './EncounterStrategies.mjs';
test('new six-fight balance: adaptive clears 1–4 players, blind attacks lose and defense alone stalls',()=>{for(const players of [1,2,3,4]){const adaptive=simulateEncounterCampaign(players);assert.equal(adaptive.phase,'clear',`${players}P adaptive`);assert.ok(adaptive.turns.every(t=>t>0));assert.ok(adaptive.hp>0);const reckless=simulateEncounterCampaign(players,'attack-all');assert.equal(reckless.phase,'gameover');}const passive=simulateEncounterCampaign(4,'defense-all');assert.equal(passive.phase,'playing');assert.equal(passive.turns.slice(1).reduce((n,x)=>n+x,0),0);});
