import test from 'node:test';
import assert from 'node:assert/strict';
import {createCharacter} from '../src/CharacterSystem.js';
import {EquipmentData} from '../src/EquipmentData.js';
import {buyItem} from '../src/ShopSystem.js';
import {equipItem,unequipItem,sellItem,finalStats} from '../src/EquipmentSystem.js';
import {validateSave} from '../src/SaveSystem.js';
import {createRPGContext} from '../src/RPGConfig.js';
import {createState} from '../src/GameState.js';
const hero=()=>{const c=createCharacter('장비 용사');c.gold=10000;return c;};
test('equipment catalog has 12 data-driven items and four Korean rarities',()=>{assert.equal(EquipmentData.length,12);assert.deepEqual(new Set(EquipmentData.map(i=>i.rarity)),new Set(['COMMON','UNCOMMON','RARE','EPIC']));});
test('buy deducts exact gold and adds one inventory item',()=>{const c=hero(),before=c.gold;assert.equal(buyItem(c,'old_sword').ok,true);assert.equal(c.gold,before-100);assert.deepEqual(c.inventory.items,['old_sword']);});
test('insufficient gold and unknown item do not mutate inventory',()=>{const c=createCharacter('가난한 용사');assert.equal(buyItem(c,'steel_sword').ok,false);assert.equal(c.inventory.items.length,0);assert.equal(buyItem(c,'missing').ok,false);});
test('equip replaces old item and returns it to inventory',()=>{const c=hero();buyItem(c,'old_sword');buyItem(c,'steel_sword');assert.equal(equipItem(c,'old_sword').ok,true);assert.equal(equipItem(c,'steel_sword').ok,true);assert.equal(c.equipment.weapon,'steel_sword');assert.deepEqual(c.inventory.items,['old_sword']);});
test('unequip returns item and removes its attack modifier without accumulation',()=>{const c=hero();buyItem(c,'steel_sword');equipItem(c,'steel_sword');assert.equal(finalStats(c).attack,14);unequipItem(c,'weapon');assert.equal(finalStats(c).attack,10);assert.equal(finalStats(c).maxHP,100);});
test('armor maximum HP and current HP clamp safely on removal',()=>{const c=hero();c.hp=100;buyItem(c,'mage_armor');equipItem(c,'mage_armor');assert.equal(c.maxHP,115);c.hp=115;unequipItem(c,'armor');assert.equal(c.maxHP,100);assert.equal(c.hp,100);});
test('accessory slot replacement keeps exactly one modifier',()=>{const c=hero();buyItem(c,'power_ring');equipItem(c,'power_ring');buyItem(c,'life_necklace');equipItem(c,'life_necklace');assert.deepEqual(finalStats(c),{maxHP:108,attack:10,defense:5});assert.deepEqual(c.inventory.items,['power_ring']);});
test('special equipment effects stay in RPG context only',()=>{const c=hero();buyItem(c,'rogue_dagger');equipItem(c,'rogue_dagger');const s=createState(1,'sequential',createRPGContext(c));assert.equal(s.battleContext.attackGradeBonus('B'),1);assert.equal(s.battleContext.attackGradeBonus('A'),0);});
test('defense and scroll special effects are bounded data bonuses',()=>{const c=hero();for(const id of ['guardian_armor','sage_ring']){buyItem(c,id);equipItem(c,id);}const ctx=createRPGContext(c);assert.equal(ctx.defenseGradeBonus('S'),3);assert.equal(ctx.scrollPowerBonus('S'),3);});
test('selling grants sell price and equipped items require unequip first',()=>{const c=hero();buyItem(c,'old_sword');equipItem(c,'old_sword');assert.equal(sellItem(c,'old_sword').ok,false);unequipItem(c,'weapon');assert.equal(sellItem(c,'old_sword').ok,true);assert.equal(c.gold,9950);});
test('migration preserves v2.0 progression and creates empty equipment fields',()=>{const c=createCharacter('이전 용사');c.level=3;c.exp=7;c.gold=175;c.maxHP=110;c.hp=110;c.attack=14;c.defense=7;const old={saveVersion:1,character:c,progress:{clearedDungeons:[],run:null,completedRuns:0,stats:{turns:0,blocks:0,scrolls:0,attack:{S:0,A:0,B:0,C:0},defense:{S:0,A:0,B:0,C:0}}},meta:{createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}};delete old.character.equipment;delete old.character.inventory;const migrated=validateSave(old);assert.equal(migrated.saveVersion,2);assert.equal(migrated.character.level,3);assert.equal(migrated.character.gold,175);assert.deepEqual(migrated.character.inventory.items,[]);});
test('class context ignores RPG equipment entirely',()=>{const c=hero();buyItem(c,'sage_staff');equipItem(c,'sage_staff');const classState=createState(1);assert.equal(classState.battleContext.mode,'class');assert.equal(classState.battleContext.attackBonus,0);});
test('duplicate rapid purchases each charge exactly once',()=>{const c=hero();assert.equal(buyItem(c,'old_sword').ok,true);assert.equal(buyItem(c,'old_sword').ok,true);assert.equal(c.inventory.items.length,2);assert.equal(c.gold,9800);});
