const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{
 const {RPGMode}=await import('../src/RPGMode.js'),{characterStats}=await import('../src/RPGConfig.js');
 const rpg=new RPGMode({getItem(){return null},setItem(){}});rpg.create('동료 탐험가');Object.assign(rpg.character,{level:4,exp:0,...characterStats(4),hp:110,gold:5000});rpg.character.inventory.items.push('steel_sword','leather_armor');rpg.equip('steel_sword');rpg.equip('leather_armor');rpg.acceptQuest('new-companion');rpg.acceptQuest('perfect-team');
 const fixture=structuredClone(rpg.data);fixture.saveVersion=3;for(const k of ['activeMercenary','mercenaryContractState','mercenaryStats'])delete fixture.progress[k];
 const browser=await pw.chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true});
 const errors=[],results={},frames=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});page.setDefaultTimeout(20000);
 const click=async action=>page.locator('[data-action="'+action+'"]:not([disabled])').first().tap(),data=()=>page.evaluate(()=>structuredClone(window.dungeonDebug.rpg.data)),state=()=>page.evaluate(()=>window.dungeonDebug.state);
 const shot=async name=>page.screenshot({path:path.join(__dirname,'../preview-v23-'+name+'.png'),fullPage:true});
 const skip=async()=>{if(await page.locator('[data-action=presentation-skip]').count())await page.locator('[data-action=presentation-skip]').dispatchEvent('click');};
 async function openBase(){await page.goto('http://127.0.0.1:4173/?debug=1');await page.evaluate(d=>{localStorage.clear();localStorage.setItem('dungeon-rpg-adventure-save',JSON.stringify(d));},fixture);await page.reload();await click('rpg-enter');await click('rpg-continue');assert.equal((await data()).saveVersion,4);assert.deepEqual((await data()).character,fixture.character);}
 async function hire(id){await click('rpg-mercenaries');await page.locator('[data-action=rpg-mercenary-hire][data-mercenary="'+id+'"]').tap();}
 async function enter(){await click('rpg-town');await click('rpg-dungeon');await page.locator('[data-action=rpg-dungeon-start][data-dungeon=old-prison]').tap();assert.equal(await page.locator('.party-members').count(),1);await page.waitForFunction(()=>{const img=document.querySelector('.party-members img');return img?.complete&&img.naturalWidth>0;});await shot('party-'+(await data()).progress.activeMercenary);await click('rpg-party-depart');await skip();await page.waitForFunction(()=>window.dungeonDebug.timer.running);assert.equal(await page.locator('.mercenary-companion').count(),1);await click('debug-toggle');await page.locator('#debug-animation').selectOption('0.25');await click('debug-toggle');await page.evaluate(()=>{window.__supportFrames=[];new MutationObserver(()=>{if(!document.querySelector('.mercenary-support')||window.__sampling)return;window.__sampling=true;let prev=null,a=[];function sample(t){if(prev!==null)a.push(t-prev);prev=t;if(a.length<30)requestAnimationFrame(sample);else{window.__supportFrames.push(a);window.__sampling=false;}}requestAnimationFrame(sample);}).observe(document.querySelector('#app'),{childList:true,subtree:true});});}
 async function solve(side='attack',grade='S',want='fire',capture=null){
  await page.waitForFunction(()=>window.dungeonDebug.timer.running);
  const s=await state(),t=s.targets.find(t=>t.side===side&&t.grade===grade),pad=page.locator('.input-pad');
  for(let i=0;i<t.solution.ids.length;i++){if(i)await pad.locator('[data-op="'+t.solution.ops[i-1]+'"]').tap();await pad.locator('[data-dice="'+t.solution.ids[i]+'"]').tap();}
  await pad.locator('[data-action=submit]').tap();
  for(let i=0;i<600;i++){
   if(await page.locator('.scroll-choice-overlay').count()){const ss=await state(),pick=ss.scrolls.find(x=>x.type===want)||ss.scrolls.find(x=>['fire','ice'].includes(x.type))||ss.scrolls[0];await page.locator(pick?'.scroll-choice-overlay [data-type="'+pick.type+'"]':'.scroll-choice-overlay [data-action=cast-skip]').first().tap();}
   if(await page.locator('.mercenary-support').count()){const id=(await data()).progress.activeMercenary;if(!results[id+'-visual']){await shot('support-'+(capture||id));results[id+'-visual']=true;}}
   if((await state()).phase!=='resolution')break;await page.waitForTimeout(10);
  }
  await page.waitForFunction(()=>window.dungeonDebug.state.phase!=='resolution');
 }
 async function finish(full=false){let guard=0;while(guard++<50){const s=await state();assert.notEqual(s.phase,'gameover');if(['reward','clear'].includes(s.phase)){if(!full||s.phase==='clear')return;await page.locator('[data-action=loot-choice]').first().tap();await click('next-monster');await skip();continue;}await solve();}throw Error('fight guard');}
 await openBase();await click('rpg-mercenaries');assert.equal(await page.locator('.mercenary-card').count(),6);
 for(const id of ['rowen','bram','sera','luna','kain','elia']){const art=page.locator('[data-mercenary="'+id+'"] img');await art.scrollIntoViewIfNeeded();await page.waitForFunction(id=>{const img=document.querySelector('[data-mercenary="'+id+'"] img');return img?.complete&&img.naturalWidth>0;},id);await page.locator('[data-action=rpg-mercenary-detail][data-mercenary="'+id+'"]').first().tap();await shot('detail-'+id);assert.ok(await page.locator('.mercenary-detail .mercenary-art').isVisible());await click('rpg-mercenary-close');}
 for(const [width,height]of [[390,844],[1024,768],[1920,1080]]){await page.setViewportSize({width,height});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('guild-'+width);}await page.setViewportSize({width:1024,height:768});
 await page.locator('[data-action=rpg-mercenary-hire][data-mercenary=rowen]').tap();assert.equal((await data()).character.gold,4740);await page.evaluate(()=>{const button=document.querySelector('[data-action=rpg-mercenary-hire][data-mercenary=rowen]');for(let i=0;i<8;i++)button.dispatchEvent(new MouseEvent('click',{bubbles:true}));});assert.equal((await data()).character.gold,4740);
 await page.locator('[data-action=rpg-mercenary-hire][data-mercenary=kain]').tap();assert.equal(await page.locator('.mercenary-confirm-overlay').count(),1);await click('rpg-mercenary-close');assert.equal((await data()).progress.activeMercenary,'rowen');
 await enter();await solve('attack','A','fire','rowen');let row=await data();assert.equal(row.progress.mercenaryStats.supports,1);assert.equal(row.progress.questProgress['perfect-team'].count,1);const contract=structuredClone(row.progress.mercenaryContractState),gold=row.character.gold;
 await page.reload();await click('rpg-enter');await click('rpg-continue');assert.deepEqual((await data()).progress.mercenaryContractState,contract);assert.equal((await data()).character.gold,gold);await click('rpg-dungeon');await click('rpg-dungeon-start');await skip();await finish(true);
 const clear=await data();assert.equal(clear.progress.activeMercenary,'rowen');assert.ok(clear.progress.completedQuests.includes('new-companion'));assert.ok(clear.progress.completedQuests.includes('perfect-team'));await shot('rowen-clear');await page.locator('[data-action=loot-choice]').first().tap();await click('rpg-return');assert.equal((await data()).progress.activeMercenary,null);assert.equal((await data()).progress.mercenaryStats.ended,1);results.rowen={fullClear:true,supports:clear.progress.mercenaryStats.supports,reload:true};
 for(const id of ['bram','sera','luna','kain','elia']){
  await openBase();if(id==='sera'){await page.evaluate(()=>{window.dungeonDebug.rpg.character.hp=70;window.dungeonDebug.rpg.save();});}await hire(id);await enter();
  if(id==='bram')await solve('defense','S','fire',id);
  else if(id==='elia'){await solve('defense','S','fire',id+'-defense');await solve('attack','S','fire',id+'-attack');}
  else await solve('attack','S','fire',id);
  await finish(true);const ss=await state(),d=await data(),events=ss.events.filter(e=>e.support).map(e=>e.support);assert.ok(events.length>0,id+' support missing');assert.ok(events.every(e=>e.mercenaryId===id));if(id==='sera')assert.ok(events.some(e=>e.effect==='heal'&&e.value===12));if(id==='elia')assert.ok(events.some(e=>e.effect==='damage')&&events.some(e=>e.effect==='shield'));
  await shot(id+'-victory');assert.equal(d.character.gold,5000-({bram:240,sera:480,luna:520,kain:1050,elia:1150}[id])+175);results[id]={fullClear:true,effects:events,supports:d.progress.mercenaryStats.supports,gold:d.character.gold,hp:d.character.hp,animationFrames:await page.evaluate(()=>window.__supportFrames)};await page.locator('[data-action=loot-choice]').first().tap();await click('rpg-return');assert.equal((await data()).progress.activeMercenary,null);assert.equal((await data()).progress.mercenaryStats.ended,1);
 }
 await openBase();await click('rpg-dungeon');await page.locator('[data-action=rpg-dungeon-start][data-dungeon=old-prison]').tap();await skip();await page.waitForFunction(()=>window.dungeonDebug.timer.running);await click('debug-toggle');await page.locator('#debug-animation').selectOption('0.25');await click('debug-toggle');assert.equal(await page.locator('.mercenary-companion').count(),0);await finish(true);results.none={fullClear:true,gold:(await data()).character.gold,hp:(await data()).character.hp};assert.equal(results.none.gold,5175);
 await openBase();await hire('bram');await page.reload();await click('rpg-enter');await click('rpg-continue');assert.equal((await data()).progress.activeMercenary,'bram');await enter();
 await page.evaluate(()=>new Promise(resolve=>{let prev=null;const a=[];function frame(t){if(prev!==null)a.push(t-prev);prev=t;if(a.length<60)requestAnimationFrame(frame);else{window.__frames=a;resolve();}}requestAnimationFrame(frame);}));frames.push(...await page.evaluate(()=>window.__frames));frames.sort((a,b)=>a-b);
 await page.goto('http://127.0.0.1:4173/dist/index.html?debug=1');await click('rpg-enter');await click('rpg-continue');await click('rpg-mercenaries');assert.equal(await page.locator('.mercenary-card').count(),6);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'../MERCENARY-BROWSER-RESULTS.json'),JSON.stringify({pass:true,fixture:'v2.2 Lv4 / steel sword / leather armor / 5000G QA save; Sera starts at70HP; no forced combat wins',results,frames:{medianMS:frames[30],p95MS:frames[57]},errors},null,2));console.log('PASS six mercenaries real browser math, full Rowen dungeon, costs, refresh, quests, party, responsive art, production',JSON.stringify(results));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
