const path=require('node:path');let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}const {chromium}=playwright,assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1024,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
async function korean(){const words=await page.evaluate(()=>{const clone=document.body.cloneNode(true);clone.querySelectorAll('.debug,[data-action=debug-toggle]').forEach(x=>x.remove());return (clone.textContent.match(/[A-Za-z]+/g)||[]).filter(w=>!['S','A','B','C','HP','P'].includes(w));});assert.deepEqual(words,[]);}
async function shot(name){await page.screenshot({path:path.join(__dirname,'..',`preview-v4-${name}.png`),fullPage:true});}
async function start(mode='sequential'){await page.goto('http://127.0.0.1:4173/?debug=1&legacy=1');await page.evaluate(()=>{window.v11TestObserver?.disconnect();window.v11TestObserver=new MutationObserver(()=>{const choice=document.querySelector('.scroll-choice-overlay [data-action="cast-choice"]');if(choice)choice.click();const loot=document.querySelector('[data-action="loot-choice"][data-type="fire"]')||document.querySelector('[data-action="loot-choice"]');if(loot)loot.click();});window.v11TestObserver.observe(document.querySelector('#app'),{childList:true,subtree:true});});await korean();await page.click('[data-action=setup]');await korean();await page.click('[data-players="4"]');await page.click(`[data-mode=${mode}]`);await page.click('[data-action=story]');await korean();await page.click('[data-action=start]');await page.locator('.monster-dialogue').waitFor();await korean();await page.locator('[data-action=presentation-skip]').dispatchEvent('click');await page.waitForFunction(()=>window.dungeonDebug.timer.running);await korean();}
await start();await shot('tablet');await page.waitForFunction(()=>window.dungeonDebug.audio.buffers.size>=15);assert.ok(await page.evaluate(()=>window.dungeonDebug.audio.music.source.loop));assert.ok(await page.evaluate(()=>window.dungeonDebug.audio.music.source.buffer.duration)>65);
await page.evaluate(()=>{const a=window.dungeonDebug.audio;window.qualitySource=a.music.source;window.qualityMusic=a.music;a.setMood('battle');a.playBGM('battle');});assert.equal(await page.evaluate(()=>window.qualitySource===window.dungeonDebug.audio.music.source),true);await page.evaluate(()=>window.dungeonDebug.audio.setMood('input'));
await page.click('[data-action=settings]');await korean();await shot('settings');await page.click('[data-action=settings-close]');
await page.evaluate(()=>{window.qualityFrames=[];new MutationObserver(()=>{const stage=document.querySelector('.battle-stage');if(stage)window.qualityFrames.push({effect:stage.dataset.effect,time:window.dungeonDebug.audio.context.currentTime});}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['data-effect']});});
async function solve(player,side,grade){const t=await page.evaluate(({side,grade})=>window.dungeonDebug.state.targets.find(t=>t.side===side&&t.grade===grade),{side,grade});for(let i=0;i<t.solution.ids.length;i++){if(i)await page.locator(`[data-player="${player}"] [data-op="${t.solution.ops[i-1]}"]`).click();await page.locator(`[data-player="${player}"] [data-dice="${t.solution.ids[i]}"]`).click();}await page.locator(`[data-player="${player}"] [data-action=submit]`).click();}
await solve(0,'attack','C');await solve(1,'defense','S');await solve(2,'attack','S');await solve(3,'attack','A');await page.locator('.fx-attack').waitFor();await korean();await shot('impact');await page.locator('.fx-scroll-open').waitFor();await korean();await shot('scroll');await page.locator('.fx-magic').waitFor();await korean();await shot('fireball');await page.waitForFunction(()=>window.dungeonDebug.state.turn===2&&window.dungeonDebug.timer.running,{},{timeout:30000});
const audio=await page.evaluate(()=>({history:window.dungeonDebug.audio.history,frames:window.qualityFrames}));const swing=audio.history.find(x=>x.name==='whoosh'),impact=audio.history.find(x=>x.name==='attack');assert.ok(swing.asset&&impact.asset);assert.ok(impact.time-swing.time>=.08&&impact.time-swing.time<.25,'C preparation should be about 0.1s: '+(impact.time-swing.time));const frame=audio.frames.find(x=>x.effect==='attack');assert.ok(Math.abs(frame.time-impact.time)<.04);assert.ok(audio.history.some(x=>x.name==='charge'&&x.asset));assert.ok(audio.history.some(x=>x.name==='launch'&&x.asset));assert.ok(audio.history.some(x=>x.name==='magic'&&x.asset));assert.ok(audio.history.some(x=>x.name==='collision'&&x.asset));assert.equal(audio.history.filter(x=>x.name==='music').length,1);console.log('PASS music continuity; recorded swing/impact spacing',impact.time-swing.time,'seconds; impact frame delta',frame.time-impact.time);
for(const [w,h,name,mode] of [[390,844,'mobile','sequential'],[1920,1080,'board','simultaneous']]){await page.setViewportSize({width:w,height:h});await start(mode);await shot(name);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),w);await korean();if(w===1920){assert.equal(await page.locator('.input-pad').count(),4);assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight),h);}await page.click('[data-action=settings]');await korean();await page.click('[data-action=settings-close]');}
// All translated special names and outcomes in real cutscenes.
await page.click('[data-action=debug-toggle]');await page.selectOption('#debug-animation','0.25');for(const [index,special] of [[1,'steal'],[2,'curse'],[3,'web'],[3,'poison'],[4,'shift'],[4,'stone']]){if(!await page.locator('.debug').count())await page.click('[data-action=debug-toggle]');await page.selectOption('#debug-select-monster',String(index));await page.waitForFunction(()=>window.dungeonDebug.timer.running);await page.evaluate(special=>{window.dungeonDebug.state.intent.special=special;window.dungeonDebug.state.hero.hp=180;},special);await page.click('[data-debug=end]');await page.locator('.special-sequence').waitFor();await korean();await page.locator('.special-sequence.impact').waitFor();await korean();await page.locator('[data-action=presentation-skip]').dispatchEvent('click');await page.waitForFunction(()=>window.dungeonDebug.timer.running);}
assert.deepEqual(errors,[]);console.log('PASS Korean title/setup/story/settings/input/attacks/spells/all specials; mobile/tablet/board; no browser errors');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});



