import {preparedTower} from './chaos-fixture.mjs';
import {ScrollData} from '../src/ScrollData.js';
import {applyScrollEffect} from '../src/ScrollSystem.js';
import {MercenarySystem} from '../src/MercenarySystem.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {RPGMode} from '../src/RPGMode.js';import {validateSave,migrateSave} from '../src/SaveSystem.js';import {MercenaryData} from '../src/MercenaryData.js';import {refreshRecruitPool,recruitMercenary,rosterCapacity} from '../src/MercenaryRoster.js';
const create=()=>{const memory=new Map(),r=new RPGMode({getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)});r.create('새로운 모험');r.finishOpening();r.character.gold=15000;return r;};
test('new roster has eighteen distinct roles, five persisted offers and zero hired companions',()=>{const r=create();assert.equal(MercenaryData.length,18);assert.equal(new Set(MercenaryData.map(m=>m.id)).size,18);assert.equal(r.data.saveVersion,5);assert.equal(r.data.progress.mercenaryRecruitPool.length,5);assert.deepEqual(r.data.progress.ownedMercenaries,[]);assert.deepEqual(r.data.progress.activeParty,[]);assert.ok(r.save());assert.deepEqual(validateSave(r.data),r.data);});
test('candidate transaction rejects absent offers; permanent purchase charges once',()=>{const r=create(),p=r.data.progress,id=p.mercenaryRecruitPool[0],missing=MercenaryData.find(m=>!p.mercenaryRecruitPool.includes(m.id)).id,gold=r.character.gold;assert.equal(r.recruit(missing).ok,false);assert.equal(r.character.gold,gold);assert.ok(r.recruit(id).ok);assert.equal(r.character.gold,gold-MercenaryData.find(m=>m.id===id).recruitCost);assert.ok(p.ownedMercenaries.includes(id));assert.ok(!p.mercenaryRecruitPool.includes(id));const after=r.character.gold;assert.equal(r.recruit(id).ok,false);assert.equal(r.character.gold,after);assert.ok(r.save());});
test('six owned slots and three expedition slots are independent limits',()=>{const r=create();for(const m of MercenaryData.slice(0,6))assert.ok(r.hire(m.id).ok);const before=r.character.gold;assert.equal(r.hire('aiden').storageFull,true);assert.equal(r.character.gold,before);assert.equal(r.setParty(['rowen','bram','sera','luna']).ok,false);assert.equal(r.setParty(['aiden']).ok,false);assert.ok(r.setParty([]).ok);assert.ok(r.setParty(['sera','kain','elia']).ok);assert.equal(r.data.progress.activeMercenary,'sera');assert.ok(r.save());assert.equal(rosterCapacity(r.data.progress),6);assert.equal(rosterCapacity({clearedDungeons:['burning-mine']}),8);assert.equal(rosterCapacity({clearedDungeons:['sky-canyon']}),10);});
test('farewell needs confirmation, keeps relationship and reacquisition restores it',()=>{const r=create();assert.ok(r.hire('rowen').ok);const p=r.data.progress;p.mercenaryRelations.rowen.affinityProgress=1;p.mercenaryRelations.rowen.claimIds=['legacy-clear'];const relation=structuredClone(p.mercenaryRelations.rowen);assert.equal(r.dismiss('rowen').needsConfirmation,true);assert.ok(p.ownedMercenaries.includes('rowen'));assert.ok(r.dismiss('rowen',{confirm:true}).ok);assert.deepEqual(p.mercenaryRelations.rowen,relation);assert.ok(p.mercenaryRecords.recruited.includes('rowen'));assert.ok(p.mercenaryRecords.departed.includes('rowen'));p.mercenaryRecruitPool.push('rowen');const gold=r.character.gold;assert.ok(r.recruit('rowen').rejoined);assert.equal(r.character.gold,gold-520);assert.deepEqual(p.mercenaryRelations.rowen,relation);assert.ok(r.save());});
test('candidate refresh excludes owned members, has S ceiling and cannot duplicate a return',()=>{const r=create(),p=r.data.progress;assert.ok(r.hire('rowen').ok);p.recruitmentState.withoutS=0;for(let i=0;i<4;i++){refreshRecruitPool(p,()=>0,'return-'+i);assert.ok(!p.mercenaryRecruitPool.includes('rowen'));assert.equal(p.mercenaryRecruitPool.length,5);}refreshRecruitPool(p,()=>0,'return-4');assert.ok(p.mercenaryRecruitPool.some(id=>MercenaryData.find(m=>m.id===id).grade==='S'));const snapshot=structuredClone(p);assert.equal(refreshRecruitPool(p,()=>.99,'return-4'),false);assert.deepEqual(p,snapshot);assert.ok(r.save());});
test('invalid modern parties and malformed ownership never silently normalize',()=>{const r=create(),bad=structuredClone(r.data);bad.progress.activeParty=['kain'];assert.throws(()=>validateSave(bad));const bad2=structuredClone(r.data);bad2.progress.ownedMercenaries=['rowen','rowen'];assert.throws(()=>validateSave(bad2));assert.deepEqual(migrateSave(r.data),r.data);});
test('three companions commit separate supports once and remain below student damage',()=>{const r=create();for(const id of ['rowen','kain','elia'])assert.ok(r.hire(id).ok);assert.ok(r.enterDungeon());const {state:s,combat:c}=r.createBattle(),target=s.targets.find(t=>t.side==='attack'&&t.grade==='S');c.submit(target.solution.ids,target.solution.ops);const e=c.resolveNext();assert.equal(e.kind,'attack');assert.equal(e.supports.length,3);assert.deepEqual(e.supports.map(x=>x.mercenaryId),['rowen','kain','elia']);const total=e.supports.reduce((sum,x)=>sum+x.value+(x.secondary?.value||0),0);assert.ok(total<=Math.floor(e.damage*.65));assert.equal(new Set(r.run.partyState.eventIds).size,3);assert.equal(r.data.progress.mercenaryStats.supports,3);assert.ok(r.save());});
test('next-turn bard bonus changes only the next input clock and is consumed once',()=>{const r=create();assert.ok(r.hire('lyra').ok);assert.ok(r.enterDungeon());const {state:s,combat:c}=r.createBattle();const normal=s.duration,target=s.targets.find(t=>t.side==='defense'&&t.grade==='S');c.submit(target.solution.ids,target.solution.ops);const event=c.resolveNext();assert.equal(event.supports[0].effect,'time');assert.equal(s.duration,normal);assert.equal(r.run.partyState.nextTimeBonus,3);while(s.phase==='resolution')c.resolveNext();assert.equal(s.phase,'enemy');c.startTurn();assert.equal(s.duration,normal+3);assert.equal(r.run.partyState.nextTimeBonus,0);s.phase='enemy';c.startTurn();assert.equal(s.duration,normal);});

test('three scroll allies share the bounded power budget without starving the last member',()=>{const r=create();for(const id of ['luna','tobin','sol'])assert.ok(r.hire(id).ok);assert.ok(r.enterDungeon());const {state:s}=r.createBattle(),system=new MercenarySystem(r.data,r.run),action={targetGrade:'S',scrollEffect:'fire',playerId:0};const boost=system.scrollModifier(action,s);assert.equal(boost,6);const supports=system.support({kind:'magic',type:'fire',action,mercenaryBoost:boost,damage:28},s);assert.equal(supports.length,3);assert.deepEqual(supports.map(v=>v.mercenaryId),['luna','tobin','sol']);assert.ok(supports.every(v=>v.value>0));assert.equal(supports.reduce((n,v)=>n+v.value,0),6);assert.equal(system.magicContributions.size,0);assert.deepEqual(system.support({kind:'magic',type:'fire',action,mercenaryBoost:boost},s),[]);});
test('seeded five-candidate rarity distribution remains near B55 A35 S10 while enforcing the S ceiling',()=>{const r=create(),p=r.data.progress;let seed=4271;const rng=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296),counts={B:0,A:0,S:0};for(let i=0;i<1000;i++){refreshRecruitPool(p,rng);assert.equal(p.mercenaryRecruitPool.length,5);assert.equal(new Set(p.mercenaryRecruitPool).size,5);for(const id of p.mercenaryRecruitPool)counts[MercenaryData.find(m=>m.id===id).grade]++;assert.ok(p.recruitmentState.withoutS<=4);}assert.equal(counts.B+counts.A+counts.S,5000);assert.ok(counts.B>=2400&&counts.B<=3000,JSON.stringify(counts));assert.ok(counts.A>=1450&&counts.A<=1900,JSON.stringify(counts));assert.ok(counts.S>=400&&counts.S<=750,JSON.stringify(counts));});

test('healing support reports only the applied marginal HP and consumes no quota at full HP',()=>{const r=create();r.hire('luna');r.enterDungeon();const {state:s}=r.createBattle(),system=new MercenarySystem(r.data,r.run),action={targetGrade:'S',scrollEffect:'heal',playerId:0};s.hero.hp=s.battleContext.heroMaxHP-ScrollData.heal.heal-1;const boost=system.scrollModifier(action,s);assert.equal(boost,1);const actual=applyScrollEffect(s,ScrollData.heal,null,boost),supports=system.support({kind:'magic',type:'heal',action,heal:actual.heal,mercenaryBoost:boost},s);assert.equal(actual.heal,ScrollData.heal.heal+1);assert.equal(supports[0].value,1);const count=r.data.progress.mercenaryStats.supports;s.turn++;assert.equal(system.scrollModifier(action,s),0);assert.deepEqual(system.support({kind:'magic',type:'heal',action,heal:0,mercenaryBoost:0},s),[]);assert.equal(r.data.progress.mercenaryStats.supports,count);});

test('Luna tower dialogue works from the third slot and never overwrites another ally speaker',()=>{const {r}=preparedTower();for(const id of ['rowen','tobin','luna'])assert.ok(r.hire(id).ok);r.finishChaosOpening();r.investigateTower();assert.ok(r.enterDungeon('chaos-tower'));const {state:s,combat:c}=r.createBattle(),t=s.targets.find(v=>v.side==='attack'&&v.grade==='S');c.submit(t.solution.ids,t.solution.ops);if(c.awaitingChoices())assert.ok(c.chooseTarget(0,s.enemies[0].id,0));let magic=null;while(s.phase==='resolution'){const a=s.actionQueue[s.resolutionIndex];if(a?.actionType==='scroll'&&a.status==='pending')c.chooseScroll(a,s.scrolls.findIndex(v=>v.type==='fire'));const event=c.resolveNext();const other=event?.supports?.find(v=>v.mercenaryId==='tobin')?.dialogue;r.onBattleEvent(event,s);if(event?.kind==='magic'){magic=event;assert.equal(event.supports.find(v=>v.mercenaryId==='tobin').dialogue,other);assert.match(event.supports.find(v=>v.mercenaryId==='luna').dialogue,/금지된 마력/);}}assert.ok(magic);assert.equal(r.data.progress.activeParty[2],'luna');assert.equal(r.data.progress.activeMercenary,'rowen');});
