import {validateSave} from '../src/SaveSystem.js';
import test from 'node:test';import assert from 'node:assert/strict';import {LegendaryData} from '../src/LegendaryData.js';import {rollLegendary,validateLegendary,acknowledgeLegendary} from '../src/LegendarySystem.js';import {RPGMode} from '../src/RPGMode.js';import {characterStats,createRPGContext} from '../src/RPGConfig.js';import {createState} from '../src/GameState.js';import {attackDamage} from '../src/BattleContext.js';import {GameConfig} from '../src/GameConfig.js';
const create=()=>{const r=new RPGMode({getItem(){return null},setItem(){}});r.create('전설 탐험가');r.finishOpening();return r;};
test('seven bosses have distinct legendary weapons and explicit weapon types',()=>{assert.equal(LegendaryData.length,7);assert.equal(new Set(LegendaryData.map(i=>i.id)).size,7);assert.equal(new Set(LegendaryData.map(i=>i.boss)).size,7);assert.ok(LegendaryData.every(i=>i.rarity==='LEGENDARY'&&['SWORD','GREATSWORD','STAFF'].includes(i.weaponType)));});
test('legendary can drop on first victory; reward identity never repeats',()=>{const r=create(),p=r.data.progress,id=rollLegendary(p,'golem','first-golem',()=>.099);assert.equal(id,'earth_shatterer');r.character.inventory.items.push(id);assert.ok(r.save());assert.ok(validateLegendary(p));const before=structuredClone(p.legendaryDrops);assert.equal(rollLegendary(p,'golem','first-golem',()=>0),null);assert.equal(rollLegendary(p,'golem','second-golem',()=>0),null);assert.deepEqual(p.legendaryDrops,before);assert.equal(p.legendaryRewardQueue.length,1);assert.ok(acknowledgeLegendary(p,'first-golem'));assert.equal(acknowledgeLegendary(p,'first-golem'),false);});
test('four failed draws guarantee the fifth; reload state and reused event do not reroll',()=>{const r=create(),p=r.data.progress;for(let i=1;i<=4;i++){assert.equal(rollLegendary(p,'treeGuardian','tree-'+i,()=>1),null);assert.equal(p.legendaryDrops.treeGuardian.attempts,i);assert.ok(r.save());}const snapshot=structuredClone(p.legendaryDrops);assert.equal(rollLegendary(p,'treeGuardian','tree-4',()=>0),null);assert.deepEqual(p.legendaryDrops,snapshot);assert.equal(rollLegendary(p,'treeGuardian','tree-5',()=>1),'worldtree_staff');assert.equal(p.legendaryDrops.treeGuardian.attempts,5);r.character.inventory.items.push('worldtree_staff');assert.ok(r.save());});
test('king legendary is reserved for post-ending rematches',()=>{const r=create(),p=r.data.progress;assert.equal(rollLegendary(p,'demonKing','story-win',()=>0),null);assert.equal(p.legendaryDrops.demonKing,undefined);p.storyCompleted=true;assert.equal(rollLegendary(p,'demonKing','postgame-win',()=>0),'finale_staff');});
test('legendary cannot be sold or farmed for duplicate sale gold',()=>{const r=create(),id=rollLegendary(r.data.progress,'flameGiant','flame-1',()=>0);r.character.inventory.items.push(id);assert.ok(r.save());const gold=r.character.gold;assert.equal(r.sell(id).ok,false);assert.equal(r.character.gold,gold);assert.ok(r.character.inventory.items.includes(id));assert.equal(rollLegendary(r.data.progress,'flameGiant','flame-2',()=>0),null);});
test('high-level equipment still changes actual attacks beyond the growth cap',()=>{const r=create();Object.assign(r.character,{level:20,...characterStats(20),hp:195});r.character.inventory.items.push('old_sword','steel_sword','rogue_dagger','flame_greatsword');const values={};for(const id of ['old_sword','steel_sword','rogue_dagger','flame_greatsword']){const result=r.equip(id);assert.ok(result.ok);assert.ok(result.before&&result.after);const s=createState(1,'sequential',createRPGContext(r.character));values[id]={C:attackDamage(s,'C'),S:attackDamage(s,'S')};}assert.ok(values.steel_sword.S>values.old_sword.S);assert.ok(values.rogue_dagger.C>values.steel_sword.C);assert.ok(values.rogue_dagger.S<values.steel_sword.S);assert.ok(values.flame_greatsword.S>values.steel_sword.S);});
test('CLASS math attack and HP rules remain independent of equipment and roster',()=>{const s=createState();for(const grade of ['C','B','A','S'])assert.equal(attackDamage(s,grade),GameConfig.attack[grade]);assert.equal(s.hero.hp,GameConfig.heroHP);});
for(const item of LegendaryData)test(item.id+' deterministic drop probability, pity, persisted reward and duplicate prevention',()=>{for(const [index,chance]of [0.1,0.15,0.2,0.25].entries()){const r=create(),p=r.data.progress;p.storyCompleted=true;for(let i=0;i<index;i++)assert.equal(rollLegendary(p,item.boss,'failure-'+i,()=>1),null);assert.equal(rollLegendary(p,item.boss,'boundary-failure',()=>chance),null);assert.equal(p.legendaryDrops[item.boss].attempts,index+1);}const r=create();r.data.progress.storyCompleted=true;r.data.progress.clearedDungeons.push('demon-throne');for(let i=1;i<=4;i++){assert.equal(rollLegendary(r.data.progress,item.boss,'roll-'+i,()=>1),null);assert.equal(r.data.progress.legendaryDrops[item.boss].attempts,i);const restored=JSON.parse(JSON.stringify(r.data.progress));assert.equal(rollLegendary(restored,item.boss,'roll-'+i,()=>0),null);assert.deepEqual(restored,r.data.progress);}assert.equal(rollLegendary(r.data.progress,item.boss,'roll-5',()=>1),item.id);r.character.inventory.items.push(item.id);assert.ok(r.save());assert.ok(validateLegendary(r.data.progress));assert.equal(r.data.progress.legendaryDrops[item.boss].attempts,5);assert.equal(rollLegendary(r.data.progress,item.boss,'roll-6',()=>0),null);assert.equal(r.data.progress.legendaryRewardQueue.filter(v=>v.item===item.id).length,1);assert.ok(r.equip(item.id).ok);assert.equal(r.character.equipment.weapon,item.id);});

test('modern legendary possession cannot disagree with its acquisition ledger',()=>{const r=create();r.character.inventory.items.push('earth_shatterer');r.data.progress.collection.equipment.push('earth_shatterer');assert.throws(()=>validateSave(r.data));r.data.progress.legendaryAcquired.push('earth_shatterer');assert.throws(()=>validateSave(r.data));r.data.progress.legendaryDrops.golem={attempts:1,acquired:true,eventIds:['earned']};assert.doesNotThrow(()=>validateSave(r.data));});
