const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{const {RPGMode}=await import('../src/RPGMode.js'),{EquipmentData}=await import('../src/EquipmentData.js');
 const r=new RPGMode({getItem(){return null},setItem(){}});r.create('빛의 모험가');r.finishOpening();r.character.gold=5000;r.character.inventory.items=EquipmentData.map(x=>x.id);r.equip('sage_staff');r.equip('mage_armor');r.equip('sage_ring');
 const b=await pw.chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1440,height:1000},hasTouch:true});p.setDefaultTimeout(15000);const errors=[],screens=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
 const click=async a=>p.locator('[data-action="'+a+'"]').first().tap();
 async function shot(n){await p.evaluate(()=>Promise.all([...document.images].map(i=>{i.loading="eager";return i.decode().catch(()=>{});} )));await p.waitForTimeout(250);await p.screenshot({path:path.join(__dirname,'../preview-v24-'+n+'.png'),fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),n+' horizontal overflow');screens.push(n);}
 await p.goto('http://127.0.0.1:4173/?debug=1');await shot('main');await p.evaluate(d=>localStorage.setItem('dungeon-rpg-adventure-save',JSON.stringify(d)),r.data);await p.reload();await click('rpg-enter');await click('rpg-continue');await shot('town');
 for(const [action,name]of [['rpg-shop-weapon','weapons'],['rpg-shop-armor','armor'],['rpg-shop-accessory','accessories'],['rpg-inventory','inventory'],['rpg-character','character'],['rpg-guild','guild'],['rpg-mercenaries','mercenaries'],['rpg-dungeon','dungeons']]){await click('rpg-town');await click(action);await shot(name);if(name==='accessories'){await p.locator('.item-detail summary').first().tap();await p.locator(".item-detail[open]>div").waitFor();await p.waitForFunction(()=>document.querySelector(".item-detail[open] image").getAttribute("href").endsWith("accessories.webp"));await shot('item-detail');await p.locator(".item-detail[open] summary").tap();assert.equal(await p.locator(".item-detail[open]").count(),0);}}
 await click('rpg-town');await click('rpg-mercenaries');await p.locator('[data-action=rpg-mercenary-hire][data-mercenary=rowen]').tap();await click('rpg-town');await click('rpg-dungeon');await p.locator('[data-action=rpg-dungeon-start][data-dungeon=old-prison]').tap();await shot('party');await click('rpg-party-depart');if(await p.locator('[data-action=presentation-skip]').count())await p.locator('[data-action=presentation-skip]').dispatchEvent('click');await p.waitForFunction(()=>window.dungeonDebug.timer.running);await shot('prison-companion');
 await p.evaluate(()=>window.dungeonDebug.timer.stop()); // Isolated presentation fixtures.
 await p.evaluate(async()=>{const {artHTML}=await import('./src/AssetManifest.js');document.querySelector('#app').innerHTML='<main class="rpg-shell"><h1>두루마리 선택</h1><div class="scroll-cards">'+['fire','ice','iceStorm','shield','heal','lightning','cleanse','meteor','time'].map(id=>'<button class="scroll-card">'+artHTML(id)+'<strong>'+id+'</strong></button>').join('')+'</div></main>';});await shot('scroll-selection');
 await p.evaluate(async()=>{const {dropsHTML}=await import('./src/AdventureView.js');document.querySelector('#app').innerHTML='<main class="rpg-shell">'+dropsHTML({gold:30,scrolls:['fire','time'],equipment:['sage_ring','guardian_armor']})+'</main>';});await shot('loot-equipment');
 await p.evaluate(async()=>{const {VisualEffects}=await import('./src/VisualEffects.js');const host=document.querySelector('#app');host.className='battle-stage';new VisualEffects(()=>{}).show({kind:'scroll-open',type:'time'});});await shot('scroll-open');
 await p.goto('http://127.0.0.1:4173/dist/index.html?debug=1');await click('rpg-enter');await click('rpg-continue');
 for(const [w,h]of [[390,844],[1024,768],[1920,1080]]){await p.setViewportSize({width:w,height:h});await shot('town-'+w);await click('rpg-shop-accessory');await shot('accessories-'+w);await p.locator(".item-detail summary").first().tap();await p.locator(".item-detail[open]>div").waitFor();await shot("detail-"+w);const box=await p.locator(".item-detail[open]>div").boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=w&&box.y+box.height<=h);await p.locator(".item-detail[open] summary").tap();await click('rpg-town');}
 const fallback=await b.newPage();await fallback.route('**/assets/remaster/**',route=>route.abort());await fallback.goto('http://127.0.0.1:4173/');await fallback.evaluate(async()=>{const {artHTML}=await import('./src/AssetManifest.js');document.querySelector('#app').innerHTML=artHTML('hero')+artHTML('steel_sword',{label:'강철검'});});await fallback.waitForFunction(()=>document.querySelector('img.art-missing')&&document.querySelector('svg.art-missing text'));assert.match(await fallback.locator('svg text').textContent(),/강철검/);await fallback.close();
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'../REMASTER-BROWSER-RESULTS.json'),JSON.stringify({pass:true,screens,errors,fallback:true},null,2));await b.close();console.log('PASS remaster screens, responsive layouts, production assets, missing image fallback',screens.length);})().catch(e=>{console.error(e);process.exit(1)});
