import test from 'node:test';
import assert from 'node:assert/strict';
import {RPGMode} from '../src/RPGMode.js';
import {RPGConfig,RPGDungeonData,nextLevelExp,createRPGContext} from '../src/RPGConfig.js';
import {validateName,createCharacter,addExperience} from '../src/CharacterSystem.js';
import {SaveSystem,validateSave} from '../src/SaveSystem.js';
import {createState} from '../src/GameState.js';
import {CombatSystem} from '../src/CombatSystem.js';
import {useScroll} from '../src/ScrollSystem.js';
import {attackDamage,mitigateAttack} from '../src/BattleContext.js';
class Storage{constructor(){this.map=new Map();}getItem(key){return this.map.get(key)||null;}setItem(key,value){this.map.set(key,value);}}
const mode=()=>{const storage=new Storage(),rpg=new RPGMode(storage);rpg.create('테스트 용사');return {storage,rpg};};
function battle(rpg){if(!rpg.run)rpg.enterDungeon();return rpg.createBattle();}
function hit(c,side='attack',grade='S'){const t=c.state.targets.find(t=>t.side===side&&t.grade===grade);c.submit(t.solution.ids,t.solution.ops);}
function win(rpg,s,c){s.enemies.forEach(e=>e.hp=1);s.monsterHP=s.enemies.length;hit(c,'attack','A');c.resolveAll();rpg.onBattleEvent(s.events.at(-1),s);assert.ok(['reward','clear'].includes(s.phase));}
function loot(rpg,s,c,type=s.lootCandidates[0]){assert.equal(c.chooseReward(type),true);assert.equal(rpg.recordLoot(s,type),true);}
test('name validation trims but rejects blank, long and punctuation abuse',()=>{assert.equal(validateName('  지승  용사 '),'지승 용사');for(const name of ['', '   ', '가'.repeat(13),'<script>','!!','용사🔥'])assert.throws(()=>validateName(name));assert.equal(createCharacter('용사').level,1);});
test('new character has configurable initial stats and empty equipment hooks',()=>{const {rpg,storage}=mode(),c=rpg.character;assert.equal(c.maxHP,100);assert.equal(c.hp,100);assert.equal(c.attack,10);assert.equal(c.defense,5);assert.equal(c.exp,0);assert.equal(c.gold,0);assert.deepEqual(c.equipment,{weapon:null,armor:null,accessory:null});assert.ok(storage.getItem(RPGConfig.saveKey));});
test('RPG context reuses CombatSystem with one player, eight math goals and independent three-fight data',()=>{const {rpg}=mode(),{state:s,combat:c}=battle(rpg);assert.ok(c instanceof CombatSystem);assert.equal(s.players,1);assert.equal(s.targets.length,8);assert.equal(s.hero.hp,100);assert.equal(s.monsterHP,75);assert.equal(s.battleContext.encounters.length,3);});
test('class context ignores RPG level, HP, gold and scroll collection',()=>{const {rpg}=mode();addExperience(rpg.character,20000);rpg.character.gold=9999;rpg.character.scrolls=[{type:'meteor',uses:9}];const s=createState(4),c=new CombatSystem(s);c.configureEncounter(0);c.startTurn();assert.equal(s.hero.hp,180);assert.equal(attackDamage(s,'A'),27);assert.equal(mitigateAttack(s,20),20);assert.deepEqual(s.scrolls,[{type:'fire',uses:3}]);assert.notStrictEqual(s.scrolls,rpg.character.scrolls);});
test('attack modifier stays small and preserves C/B/A/S differences at maximum level',()=>{const char=createCharacter('용사');addExperience(char,1e7);const s=createState(1,'sequential',createRPGContext(char));assert.equal(attackDamage(s,'C'),18);assert.equal(attackDamage(s,'A'),35);assert.equal(attackDamage(s,'S'),35);assert.ok(attackDamage(s,'C')<75);});
test('actual RPG queued attack uses character modifier only at resolution',()=>{const {rpg}=mode();addExperience(rpg.character,50);const {state:s,combat:c}=battle(rpg),before=s.monsterHP;hit(c,'attack','A');assert.equal(s.monsterHP,before);c.resolveAll();assert.equal(s.monsterHP,before-28);});
test('passive defense lowers normal attack only slightly, shield goals remain valuable',()=>{const {rpg}=mode(),{state:s,combat:c}=battle(rpg);assert.equal(mitigateAttack(s,6),5);c.pass();c.resolveAll();assert.equal(s.hero.hp,95);const high=createState(1,'sequential',createRPGContext({...rpg.character,defense:1000}));assert.equal(mitigateAttack(high,5),4);assert.equal(mitigateAttack(high,30),26);});
test('healing scroll respects RPG maximum HP rather than class HP180',()=>{const {rpg}=mode(),{state:s}=battle(rpg);s.hero.hp=95;s.scrolls=[{type:'heal',uses:1}];const effect=useScroll(s);assert.equal(effect.heal,5);assert.equal(s.hero.hp,100);});
test('monster EXP and gold awarded once even if victory callback repeats',()=>{const {rpg}=mode(),{state:s,combat:c}=battle(rpg);win(rpg,s,c);assert.equal(rpg.character.exp,20);assert.equal(rpg.character.gold,15);assert.equal(rpg.awardBattle(s),false);assert.equal(rpg.character.gold,15);});
test('level curve is configurable; multiple level gains increase HP, attack and defense',()=>{const char=createCharacter('용사');char.hp=40;assert.deepEqual([1,2,3].map(nextLevelExp),[50,80,120]);const up=addExperience(char,135);assert.equal(char.level,3);assert.equal(char.exp,5);assert.equal(char.maxHP,110);assert.equal(char.hp,50);assert.equal(char.attack,14);assert.equal(char.defense,7);assert.deepEqual(up,{from:1,to:3,maxHP:10,attack:4,defense:2});});
test('HP carries without full recovery; shield resets and scrolls persist into next fight',()=>{const {rpg}=mode(),{state:s,combat:c}=battle(rpg);s.hero.hp=43;s.hero.shield=38;win(rpg,s,c);loot(rpg,s,c);const scrolls=structuredClone(s.scrolls);rpg.advanceBattle(s,c);assert.equal(s.hero.hp,43);assert.equal(s.hero.shield,0);assert.deepEqual(s.scrolls,scrolls);assert.equal(s.encounterIndex,1);});
test('full three-battle rewards, level growth, bonus once, return heal and recorded dungeon clear',()=>{const {rpg}=mode();let {state:s,combat:c}=battle(rpg);for(let i=0;i<3;i++){win(rpg,s,c);loot(rpg,s,c);if(i<2){assert.equal(s.phase,'reward');assert.equal(rpg.advanceBattle(s,c),true);}else assert.equal(s.phase,'clear');}assert.equal(rpg.character.level,3);assert.equal(rpg.character.exp,15);assert.equal(rpg.character.gold,175);assert.equal(rpg.awardBattle(s),false);assert.equal(rpg.character.gold,175);assert.equal(rpg.returnToTown(),'clear');assert.equal(rpg.character.hp,110);assert.deepEqual(rpg.data.progress.clearedDungeons,[RPGDungeonData.id]);assert.equal(rpg.data.progress.completedRuns,1);assert.equal(rpg.run,null);});
test('real math RPG loop can clear without force-kills and all saved counts stay stable',()=>{const {rpg}=mode();let {state:s,combat:c}=battle(rpg),guard=0;while(!['clear','gameover'].includes(s.phase)&&guard++<100){if(s.phase==='playing'){hit(c);while(s.phase==='resolution'){const e=c.resolveNext();rpg.onBattleEvent(e,s);}if(s.phase==='enemy'){rpg.onBattleEvent(s.events.at(-1),s);c.startTurn();}}else if(s.phase==='reward'){loot(rpg,s,c,s.lootCandidates.find(id=>id==='fire')||s.lootCandidates[0]);rpg.advanceBattle(s,c);}}assert.equal(s.phase,'clear');assert.ok(rpg.character.hp>0);assert.equal(rpg.character.gold,175);});
test('autosave consumed scrolls and character HP; reload recreates independent inventory',()=>{const {rpg,storage}=mode(),{state:s,combat:c}=battle(rpg);hit(c);while(s.phase==='resolution'){const e=c.resolveNext();rpg.onBattleEvent(e,s);}const saved=new RPGMode(storage);assert.equal(saved.load().status,'ready');assert.equal(saved.character.scrolls[0].uses,2);assert.equal(saved.character.hp,95);assert.equal(saved.run.nextEncounter,0);const resumed=saved.createBattle();assert.equal(resumed.state.hero.hp,95);assert.equal(resumed.state.scrolls[0].uses,2);assert.notStrictEqual(resumed.state.scrolls,saved.character.scrolls);});
test('reload after awarded victory keeps pending loot and cannot duplicate EXP/gold',()=>{const {rpg,storage}=mode(),{state:s,combat:c}=battle(rpg);win(rpg,s,c);const saved=new RPGMode(storage);saved.load();const restored=saved.createBattle();assert.equal(restored.pending,true);assert.equal(restored.state.phase,'reward');assert.equal(saved.character.exp,20);assert.equal(saved.awardBattle(restored.state),false);loot(saved,restored.state,restored.combat);assert.equal(saved.character.gold,15);assert.equal(saved.advanceBattle(restored.state,restored.combat),true);assert.equal(restored.state.encounterIndex,1);});
test('reload after chosen loot does not grant the same reward twice',()=>{const {rpg,storage}=mode(),{state:s,combat:c}=battle(rpg);win(rpg,s,c);loot(rpg,s,c);const saved=new RPGMode(storage);saved.load();const restored=saved.createBattle(),before=JSON.stringify(saved.character.scrolls);assert.equal(restored.state.lootChosen,true);assert.equal(restored.combat.chooseReward(restored.state.lootCandidates[0]),false);assert.equal(JSON.stringify(saved.character.scrolls),before);});
test('defeat preserves earned level/EXP/gold/scrolls and returns with recovered HP',()=>{const {rpg}=mode(),{state:s,combat:c}=battle(rpg);win(rpg,s,c);loot(rpg,s,c);rpg.advanceBattle(s,c);const before={level:rpg.character.level,exp:rpg.character.exp,gold:rpg.character.gold,scrolls:JSON.stringify(rpg.character.scrolls)};s.hero.hp=1;c.pass();c.resolveAll();rpg.onBattleEvent(s.events.at(-1),s);assert.equal(s.phase,'gameover');assert.equal(rpg.run.status,'defeat');assert.equal(rpg.returnToTown(),'defeat');assert.equal(rpg.character.hp,rpg.character.maxHP);for(const key of ['level','exp','gold'])assert.equal(rpg.character[key],before[key]);assert.equal(JSON.stringify(rpg.character.scrolls),before.scrolls);});
test('versioned save includes character, future equipment slots and progress',()=>{const {rpg}=mode();const data=validateSave(rpg.data);assert.equal(data.saveVersion,4);assert.ok(data.character.equipment);assert.ok(data.character.inventory);assert.ok(data.progress.clearedDungeons);});
test('corrupt primary recovers previous valid automatic backup without dropping character',()=>{const {rpg,storage}=mode();rpg.character.gold=30;rpg.save();storage.setItem(RPGConfig.saveKey,'broken');const recovered=new RPGMode(storage);assert.equal(recovered.load().status,'recovered');assert.equal(recovered.character.name,'테스트 용사');assert.equal(recovered.character.gold,0);});
test('invalid/newer saves are preserved, not silently overwritten',()=>{const storage=new Storage(),saves=new SaveSystem(storage);for(const raw of ['broken',JSON.stringify({saveVersion:99})]){storage.setItem(RPGConfig.saveKey,raw);const result=saves.load();assert.ok(['invalid','newer'].includes(result.status));assert.equal(storage.getItem(RPGConfig.saveKey),raw);}});
test('malformed save numeric values and scrolls are rejected before rendering',()=>{const {rpg}=mode();for(const modify of [d=>d.character.gold=-1,d=>d.character.hp=1e9,d=>d.character.level=NaN,d=>d.character.name='<script>',d=>d.character.scrolls=[{type:'bad',uses:3}],d=>d.meta=null]){const data=structuredClone(rpg.data);modify(data);assert.throws(()=>validateSave(data));}});
test('storage denial/quota never crashes gameplay or claims save success',()=>{const storage={getItem(){throw new Error('denied')},setItem(){throw new Error('quota')}},rpg=new RPGMode(storage);assert.equal(rpg.load().status,'unavailable');assert.doesNotThrow(()=>rpg.create('용사'));assert.equal(rpg.saveInfo.ok,false);assert.ok(rpg.character);assert.equal(new SaveSystem(null).save(rpg.data).ok,false);});
test('known earlier schema migrates while keeping progression',()=>{const {rpg}=mode(),data=structuredClone(rpg.data);data.saveVersion=0;delete data.character.equipment;const migrated=validateSave(data);assert.equal(migrated.saveVersion,4);assert.equal(migrated.character.name,rpg.character.name);assert.ok(migrated.character.equipment);});

test('unsaved in-memory character survives mode switching',()=>{const rpg=new RPGMode(null);rpg.create('용사');rpg.character.gold=15;rpg.load();assert.equal(rpg.character.gold,15);});

test('active uncompleted enemies cannot trigger EXP or gold rewards',()=>{const {rpg}=mode(),{state:s}=battle(rpg);assert.equal(rpg.awardBattle(s),false);assert.equal(rpg.character.gold,0);});
test('level-up and gold are persisted together with victory receipt',()=>{const {rpg,storage}=mode(),{state:s,combat:c}=battle(rpg);win(rpg,s,c);loot(rpg,s,c);rpg.advanceBattle(s,c);win(rpg,s,c);const saved=new RPGMode(storage);saved.load();assert.equal(saved.character.level,2);assert.equal(saved.character.attack,12);assert.equal(saved.character.gold,40);assert.equal(saved.run.pendingLoot.receipt.levelUp.to,2);});
test('clear return requires selecting loot and never increments runs twice',()=>{const {rpg}=mode(),{state:s,combat:c}=battle(rpg);for(let i=0;i<3;i++){win(rpg,s,c);if(i<2){loot(rpg,s,c);rpg.advanceBattle(s,c);}}assert.equal(rpg.returnToTown(),false);loot(rpg,s,c);assert.equal(rpg.returnToTown(),'clear');assert.equal(rpg.returnToTown(),false);assert.equal(rpg.data.progress.completedRuns,1);});
test('a second dungeon starts with saved scrolls and fresh encounter progress',()=>{const {rpg}=mode(),{state:s,combat:c}=battle(rpg);for(let i=0;i<3;i++){win(rpg,s,c);loot(rpg,s,c);if(i<2)rpg.advanceBattle(s,c);}rpg.returnToTown();const scrolls=structuredClone(rpg.character.scrolls);rpg.enterDungeon();const next=rpg.createBattle().state;assert.equal(next.encounterIndex,0);assert.equal(next.hero.hp,110);assert.deepEqual(next.scrolls,scrolls);assert.deepEqual(rpg.run.completed,[]);});
test('corrupted pending reward receipt is rejected before UI can render it',()=>{const {rpg}=mode(),{state:s,combat:c}=battle(rpg);win(rpg,s,c);const d=structuredClone(rpg.data);d.progress.run.pendingLoot.receipt.enemyNames=123;assert.throws(()=>validateSave(d));});
test('creating a confirmed replacement clears old warning and persists new name',()=>{const {rpg,storage}=mode();rpg.character.gold=99;rpg.save();rpg.loadInfo.message='old warning';rpg.create('새 용사');const next=new RPGMode(storage);next.load();assert.equal(next.character.name,'새 용사');assert.equal(next.character.gold,0);assert.equal(rpg.loadInfo.message,'');});

test('leaving during a lethal impact saves defeat rather than a playable zero-HP run',()=>{const {rpg,storage}=mode(),{state:s}=battle(rpg);s.hero.hp=0;s.phase='resolution';rpg.captureBattle(s);rpg.save();const loaded=new RPGMode(storage);loaded.load();assert.equal(loaded.run.status,'defeat');assert.equal(loaded.returnToTown(),'defeat');assert.equal(loaded.character.hp,100);assert.equal(loaded.character.level,1);});
