const path=require('node:path'),assert=require('node:assert/strict');const pw=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{const browser=await pw.chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:900},hasTouch:true});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const click=async action=>page.locator(`[data-action="${action}"]:not(:disabled)`).first().tap();const shot=async name=>{await page.evaluate(()=>Promise.all([...document.images].map(i=>{i.loading="eager";return i.decode().catch(()=>{})})));return page.screenshot({path:path.join(__dirname,`../preview-v26-story-${name}.png`),fullPage:true})};const noOverflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const data=()=>page.evaluate(()=>structuredClone(window.dungeonDebug.rpg.data));
await page.goto('http://127.0.0.1:4173/?debug=1');await click('rpg-enter');await page.locator('#character-name').fill('이야기 용사');await click('rpg-create-submit');await page.locator('.opening-classroom').waitFor();const original=(await data()).character;await shot('opening-classroom');await page.reload();await click('rpg-enter');await click('rpg-continue');await page.locator('.opening-classroom').waitFor();await click('rpg-opening-next');await page.locator('.opening-demon').waitFor();assert.match(await page.locator('body').innerText(),/나를 찾아와 쓰러뜨려라/);await shot('opening-demon');await click('rpg-opening-next');await page.locator('.opening-village').waitFor();await click('rpg-opening-skip');assert.deepEqual((await data()).character,original);await shot('town');assert.equal(await page.locator('.region-map li').count(),6);assert.equal(await page.locator('.region-map li.locked').count(),5);assert.match(await page.locator('.next-goal').innerText(),/먼저 모험가 길드/);await noOverflow();
await page.reload();await click('rpg-enter');await click('rpg-continue');assert.equal(await page.locator('.rpg-opening').count(),0);await click('rpg-guild');assert.equal((await data()).progress.story.guildVisited,true);assert.equal(await page.locator('.main-quest').count(),7);assert.equal(await page.locator('.quest-card').count(),16);await shot('guild');await click('rpg-town');await click('rpg-records');const before=await data();await click('rpg-opening-replay');await click('rpg-opening-skip');assert.deepEqual((await data()).character,before.character);assert.deepEqual((await data()).progress,before.progress);
await click('rpg-shop-weapon');assert.equal(await page.locator('[data-action=rpg-buy]:disabled').count(),4);await shot('shop-poor');await page.evaluate(()=>{window.dungeonDebug.rpg.character.gold=1000;window.dungeonDebug.rpg.save()});await click('rpg-town');await click('rpg-shop-weapon');for(const card of await page.locator('.equipment-card').all()){await card.locator('.price').scrollIntoViewIfNeeded();assert.ok(await card.locator('.price').isVisible());assert.match(await card.locator('.purchase-info').innerText(),/보유 1000G/);}await page.locator('[data-action=rpg-buy][data-item=old_sword]').tap();assert.equal((await data()).character.gold,900);await click('rpg-town');await click('rpg-inventory');await click('rpg-equip');assert.equal((await data()).character.equipment.weapon,'old_sword');await click('rpg-town');await click('rpg-shop-weapon');assert.match(await page.locator('[data-equipment=steel_sword] .equipment-comparison').innerText(),/공격력 \+2/);await shot('shop-weapon');
for(const type of ['armor','accessory']){await click('rpg-town');await click('rpg-shop-'+type);await shot('shop-'+type);await noOverflow();}
await click('rpg-town');await click('rpg-character');assert.match(await page.locator('.growth-goal').innerText(),/50 EXP/);await shot('character');await click('rpg-town');await click('rpg-dungeon');assert.equal(await page.locator('.unlock-checklist li').count(),8);await shot('dungeons');await click('rpg-town');await click('rpg-mercenaries');assert.equal(await page.locator('.mercenary-card').count(),6);await shot('mercenaries');await noOverflow();
for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1920,height:1080}]){await page.setViewportSize(viewport);await click('rpg-town');await shot('town-'+viewport.width);await noOverflow();await click('rpg-shop-armor');await shot('armor-'+viewport.width);await noOverflow();for(const card of await page.locator('.equipment-card').all()){await card.locator('.price').scrollIntoViewIfNeeded();assert.ok(await card.locator('.price').isVisible());}await click('rpg-town');await click('rpg-mercenaries');await noOverflow();}
await page.setViewportSize({width:1280,height:900});await click('rpg-town');const facility=page.locator('.facility').first();await facility.hover();const colors=await facility.evaluate(el=>({bg:getComputedStyle(el).backgroundColor,fg:getComputedStyle(el.querySelector('strong')).color}));assert.notEqual(colors.bg,'rgb(255, 255, 255)');await facility.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');assert.notEqual(await facility.evaluate(el=>getComputedStyle(el).outlineStyle),'none');await shot('town-focus');
// Report rewards use the existing system; the new feedback shows its exact growth receipt.
await page.evaluate(()=>{const r=window.dungeonDebug.rpg;r.character.exp=49;r.data.progress.completedQuests=['first-adventure'];r.data.progress.questProgress['first-adventure']={count:1,scrolls:[]};r.save();});await click('rpg-guild');await click('rpg-quest-report');const feedback=await page.locator('.story-level-overlay').innerText();assert.match(feedback,/레벨 1 → 2/);assert.match(feedback,/최대 HP \+5 · 공격력 \+2 · 방어력 \+1/);await page.waitForTimeout(900);await shot('guild-level-up');await click('rpg-level-close');
// Real saved achievements, not fake playable future regions.
await page.evaluate(()=>{const r=window.dungeonDebug.rpg;r.data.progress.clearedDungeons=['old-prison','cursed-forest'];r.data.progress.unlockedDungeons=['old-prison','cursed-forest'];r.data.progress.rewardedQuests=['first-adventure','forest-road'];for(const id of r.data.progress.rewardedQuests)r.data.progress.questProgress[id]={count:1,scrolls:[]};r.save();});await click('rpg-town');assert.match(await page.locator('.story-overview').innerText(),/2 \/ 6/);assert.match(await page.locator('.next-goal').innerText(),/붉은 마력/);assert.equal(await page.locator('.region-map li.locked').count(),4);await shot('story-complete');
await page.goto('http://127.0.0.1:4173/dist/index.html?debug=1');await click('rpg-enter');await click('rpg-continue');await page.locator('.story-overview').waitFor();assert.match(await page.title(),/2.9/);assert.deepEqual(errors,[]);await browser.close();console.log('PASS v2.6 opening, once/replay, main story, prices/comparison, touch, responsive, hover/focus, progress, production');})().catch(e=>{console.error(e);process.exit(1)});
