import {dungeonCollection} from './CollectionSystem.js';
import {mainQuestsHTML} from './StoryView.js';
import {forestChecklist} from './StorySystem.js';
import {artHTML} from './AssetManifest.js';
import {QuestData,QuestConfig} from './QuestData.js';
import {questStatus} from './QuestSystem.js';
import {DungeonData,dungeonById} from './DungeonData.js';
import {canEnterDungeon} from './DungeonSystem.js';
import {equipmentById,RarityNames} from './EquipmentData.js';
import {ScrollData} from './ScrollData.js';
import {monsterArt} from './AssetManager.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dungeonName=id=>id==='any'?'모든 던전':dungeonById(id)?.name;
export function rewardText(r){return `⭐ ${r.exp||0} EXP · 💰 ${r.gold||0}G${r.scroll?' · 📜 '+ScrollData[r.scroll].name:''}${r.equipment?' · '+equipmentById(r.equipment).name:''}${r.unlock?' · 🌲 숲 해금':''}`;}
function questCard(q,p){
 const status=questStatus(p,q.id),v=p.questProgress[q.id]?.count||0,locked=q.prerequisites?.some(id=>!p.rewardedQuests.includes(id));
 return `<article class="quest-card status-${status}" data-quest="${q.id}"><div class="quest-art">${artHTML(q.dungeon==='cursed-forest'?'forest':q.id==='magic-study'||q.id==='forest-road'?'fire':q.id==='iron-guardian'?'guardian_charm':'prison')}</div><div class="quest-copy"><small>${dungeonName(q.dungeon)} · ${q.difficulty}</small><h3>${q.name}</h3><p>${q.description}</p><div class="quest-count">${v} / ${q.target} <span>${status==='COMPLETED'?'완료 보고 가능!':status==='REWARDED'?'✓ 보상 받음':'목표 진행'}</span></div><div class="quest-track"><i style="width:${v/q.target*100}%"></i></div><p class="quest-reward">${rewardText(q.reward)}</p>${status==='AVAILABLE'?`<button class="primary" data-action="rpg-quest-accept" data-quest="${q.id}" ${locked||p.activeQuests.length>=QuestConfig.maxActive?'disabled':''}>${locked?'첫 번째 모험 보고 필요':'수락'}</button>`:status==='COMPLETED'?`<button class="primary" data-action="rpg-quest-report" data-quest="${q.id}">완료 보고</button>`:''}</div></article>`;
}
export function guildHTML(session,header,warning){
 const p=session.data.progress;
 return `<main class="rpg-shell guild-shell">${header}<section class="guild-panel">${artHTML("guild",{className:"shop-environment",eager:true})}<div class="eyebrow">모험가 길드</div><h1>이번 모험의 목표를 골라 보세요</h1><p>진행 중 의뢰 ${p.activeQuests.length} / ${QuestConfig.maxActive} · 전투 의뢰는 수락 이후의 행동, 수집 의뢰는 이미 발견한 기록도 셉니다. 조건을 채우면 귀환 후 보고해요.</p>${mainQuestsHTML(p)}${session.run?'<p class="rpg-notice">중단한 던전을 먼저 마쳐 주세요. 수락과 보고는 귀환 후 가능합니다.</p>':''}${[['COMPLETED','완료 보고'],['ACTIVE','진행 중'],['AVAILABLE','새로운 의뢰'],['REWARDED','보고한 의뢰']].map(([status,label])=>`<section class="guild-section"><h2>${label}</h2><div class="quest-grid">${QuestData.filter(q=>questStatus(p,q.id)===status).map(q=>questCard(q,p)).join('')||'<p class="empty-queue">이곳에 의뢰가 표시됩니다.</p>'}</div></section>`).join('')}</section>${warning}</main>`;
}
function collectionPreview(p,d){if(!p.clearedDungeons.includes(d.id))return '';const v=dungeonCollection(p,d),item=equipmentById(v.boss.item);return '<aside class="dungeon-collection"><b>지역 수집 기록</b><p>몬스터 '+v.monsters+'/'+v.monsterTotal+' · 일반 장비 '+v.equipment+'/'+v.equipmentTotal+' · 보스 전리품 '+(v.bossFound?'1':'0')+'/1</p><div>'+artHTML(item.id)+'<span>'+item.name+(v.bossFound?' · 발견 완료':' · 아직 발견하지 못했어요')+'</span></div><small>선택형 재도전 · 심층은 강철검·갑옷을 준비해요. 첫 처치 후 25%, 4번째 재처치까지 확정 · 한 번만 획득</small>'+(d.id==='old-prison'?'<button class="secondary" data-action="rpg-deep-start" '+(p.run?'disabled':'')+'>심층 다시 도전 · 권장 Lv4+ →</button>':'')+'</aside>';}
export function dungeonSelectorHTML(session,header,warning){
 const p=session.data.progress,run=session.run;
 return `<main class="rpg-shell dungeon-selector">${header}${run?`<div class="resume-note"><b>${dungeonName(run.dungeonId)} · ${run.pendingLoot?'받지 못한 전리품':run.status==='defeat'?'패배 후 귀환':run.status==='clear'?'클리어 후 귀환':'중단한 모험'}</b><p>현재 HP와 사용한 두루마리가 유지됩니다. 중단한 전투는 다시 시작합니다.</p><button class="primary" data-action="${run.status==='defeat'?'rpg-return':'rpg-dungeon-start'}" data-dungeon="${run.dungeonId}">모험 이어가기 →</button></div>`:''}<div class="dungeon-grid">${DungeonData.map(d=>{const unlocked=canEnterDungeon(p,d.id);return `<section class="dungeon-entry-card ${d.id==='cursed-forest'?'forest-entry':''}">${artHTML(d.id==='burning-mine'?'mine':d.id==='cursed-forest'?'forest':'prison',{className:"dungeon-landscape"})}<div class="dungeon-copy"><div class="eyebrow">권장 레벨 ${d.recommendedLevel}+ · ${d.encounters.length}개 전투</div><h1>${d.id==='burning-mine'?'🌋':d.id==='cursed-forest'?'🌲':'🏚'} ${d.name}</h1><p>${d.description}</p><p class="dungeon-guide">${d.id==='burning-mine'?'난이도 · ★★★★ / 주요 위협 · 열기, 강한 공격, 장기전 위험 / 보상 · 높은 EXP·골드, 희귀 장비와 정화·치유 두루마리':d.id==='cursed-forest'?'난이도 · 도전 / 주요 위협 · 독과 행동 방해, 마지막 나무 수호자 / 전리품 · 희귀 장비와 두루마리 획득 가능':'난이도 · 입문 / 주요 위협 · 스켈레톤, 고블린, 오크 주술사 / 전리품 · 골드, 장비, 두루마리'}</p><div class="dungeon-enemies">${[...new Set(d.encounters.flatMap(e=>e.enemies.map(e=>e.type)))].slice(0,3).map(type=>`<div>${monsterArt(type)}</div>`).join('')}</div><div class="dungeon-reward-preview">클리어 추가 보상 · ⭐ ${d.clearReward.exp} EXP · 💰 ${d.clearReward.gold}G</div><p>${unlocked?'HP와 두루마리는 다음 전투로 이어집니다.':'🔒 아래 조건을 채우면 새로운 지역이 열려요.'}</p>${collectionPreview(p,d)}${!unlocked?`<ul class="unlock-checklist">${(d.id==='burning-mine'?[['지하감옥 클리어',p.clearedDungeons.includes('old-prison')],['저주받은 숲 클리어',p.clearedDungeons.includes('cursed-forest')],['길드에서 붉은 마력의 흔적 확인',p.story?.mineInvestigated===true]]:forestChecklist(p)).map(([label,done])=>`<li class="${done?'done':'pending'}">${done?'✓':'○'} ${label}</li>`).join('')}</ul>`:''}<button class="primary" data-action="rpg-dungeon-start" data-dungeon="${d.id}" ${!unlocked||run?'disabled':''}>${unlocked?(p.clearedDungeons.includes(d.id)?'다시 도전 →':'입장 →'):'🔒 잠김'}</button></div></section>`;}).join('')}</div>${warning}</main>`;
}
export function questTrackerHTML(session){
 const p=session.data.progress,ids=[...p.activeQuests,...p.completedQuests];
 return `<details class="quest-tracker"><summary>📜 퀘스트 · ${p.activeQuests.length}개 진행 중 · ${p.completedQuests.length}개 보고 가능</summary><div>${ids.map(id=>{const q=QuestData.find(q=>q.id===id);return `<span>${q.name} <b>${p.questProgress[id].count}/${q.target} ${p.completedQuests.includes(id)?'✓ 보고 가능':''}</b></span>`;}).join('')||'<span>길드에서 의뢰를 수락해 주세요.</span>'}</div><small role="status">${esc(session.questNotice)} ${esc(session.collectionNotice)}</small></details>${session.collectionNotice?'<div class="collection-toast" role="status">'+esc(session.collectionNotice)+'</div>':''}`;
}
export function dropsHTML(drops){
 if(!drops)return '';
 return `<section class="loot-summary"><h3>전리품 획득!</h3><div><span>💰 ${drops.gold}G</span>${drops.scrolls.map(type=>`<span>${artHTML(type,{label:ScrollData[type].name})}${ScrollData[type].name}</span>`).join('')}${drops.equipment.map(id=>{const e=equipmentById(id);return `<span class="drop-${e.rarity}">${artHTML(e.id,{label:e.name})} ${e.name} [${RarityNames[e.rarity]}]</span>`;}).join('')}</div><small>가방에 지급 완료 · 골드는 위 전투 보상과 같습니다.</small></section>`;
}
