import {runAttackS35,AttackS35Reduced,AttackS35Timeline} from './AttackS35Timeline.js';
import {attackAnchor} from './FirstPersonCamera.js';
import {artHTML} from './AssetManifest.js';
import {equipmentById} from './EquipmentData.js';
import {impactMaterial} from './BattlePresentation.js';
const assets={slash:'assets/presentation-v35/slash.webp',magic:'assets/presentation-v35/magic.webp',impactAtlas:'assets/presentation-v35/impactAtlas.webp'};
const materialCell={stone:0,leaf:1,metal:2,ember:3,scale:4,arcane:5,void:5};
export class AttackSPrototype{
 constructor({settings=()=>({}),character=()=>null,audio=null}={}){Object.assign(this,{settings,character,audio});this.token=0;this.animations=new Set();this.failed=new Set();this.root=null;this.trace=[];this.preload();}
 preload(){if(this.loading)return this.loading;this.loading=Promise.all(Object.entries(assets).map(async([key,src])=>{const image=new Image();image.src=src;try{await image.decode();}catch{this.failed.add(key);}}));return this.loading;}
 animate(el,frames,options){if(!el?.animate)return;const a=el.animate(frames,options);a.finished.catch(()=>{});this.animations.add(a);return a;}
 clear(){this.token++;if(this.origin?.image)this.origin.image.style.transformOrigin=this.origin.value;this.origin=null;for(const a of this.animations)a.cancel();this.animations.clear();this.root?.remove();this.root=null;document.querySelectorAll('[data-s35-target]').forEach(n=>n.removeAttribute('data-s35-target'));const stage=document.querySelector('.battle-stage');stage?.removeAttribute('data-s35-active');stage?.removeAttribute('data-s35-phase');}
 async play(ctx){this.clear();const token=this.token,stage=document.querySelector('.battle-stage');if(!stage)return ctx.commit();const prefs=this.settings(),reduced=!!prefs.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches,simple=prefs.detail==='simple',limited=reduced||simple,scale=ctx.scale||1,anchor=attackAnchor(stage,ctx.action,ctx.state),weapon=equipmentById(this.character()?.equipment?.weapon),magic=weapon?.id==='sage_staff',material=impactMaterial(anchor.type),root=document.createElement('div');root.className='bp-layer bp-attack-windup';root.dataset.grade='S';root.dataset.s35='true';root.setAttribute('aria-hidden','true');root.style.setProperty('--s35-x',anchor.x+'px');root.style.setProperty('--s35-y',anchor.y+'px');root.style.setProperty('--s35-time-scale',scale);root.style.setProperty('--s35-flame',weapon?.id==='flame_greatsword'?1:0);stage.append(root);this.root=root;stage.dataset.s35Active='true';stage.dataset.effect='attack-windup';stage.dataset.variation=ctx.windup?.variation??0;anchor.card?.setAttribute('data-s35-target','true');const make=(tag,cls,text)=>{const el=document.createElement(tag);el.className=cls;if(text!==undefined)el.textContent=text;root.append(el);return el;};const grade=make('strong','s35-rank','S'),cut=make('div','s35-cutin'),foreweapon=make('div','s35-weapon'),trail=make('img','s35-trail'),impact=make('div','s35-material'),damage=make('strong','s35-damage');cut.innerHTML=artHTML('hero',{eager:true});foreweapon.innerHTML=artHTML(weapon?.id||'old_sword',{eager:true,full:true});trail.src=assets[magic?'magic':'slash'];trail.alt='';trail.style.display='none';impact.style.display='none';damage.style.display='none';if(!this.failed.has('impactAtlas')){const cell=materialCell[material];impact.innerHTML='<svg viewBox="0 0 100 100" aria-hidden="true"><svg viewBox="'+((cell%3)*100)+' '+(Math.floor(cell/3)*100)+' 100 100" width="100" height="100"><image href="'+assets.impactAtlas+'" width="300" height="200" preserveAspectRatio="none"/></svg></svg>';}
const originalOrigin=anchor.image?.style.transformOrigin||'',zoom=anchor.preset.closeUpScale;if(anchor.image){const r=anchor.image.getBoundingClientRect(),b=stage.getBoundingClientRect();anchor.image.style.transformOrigin=((anchor.x+b.left-r.left)/r.width*100)+'% '+((anchor.y+b.top-r.top)/r.height*100)+'%';}this.origin={image:anchor.image,value:originalOrigin};const trace=[],started=performance.now();this.trace=trace;const record=(name)=>{trace.push({stage:name,time:performance.now()-started});if(trace.length>16)trace.shift();};const valid=()=>token===this.token&&ctx.valid();const cue=(kind)=>{if(!ctx.skipped())this.audio?.cue(kind,material,magic);};const transition=(name,event)=>{if(!valid())return;record(name);stage.dataset.s35Phase=name;root.dataset.attackSStage=name;const skip=ctx.skipped();switch(name){
case 'anticipation':cue('prepare');grade.style.opacity='1';break;
case 'cutin':if(!limited&&!ctx.skipped()&&anchor.image)this.animate(anchor.image,[{transform:'scale(1)'},{transform:'scale('+zoom+')'}],{duration:300*scale,fill:'forwards',easing:'ease-in-out'});cut.style.opacity=limited||skip?'0':'1';if(!limited&&!skip){this.animate(cut,[{clipPath:'polygon(0 22%,8% 19%,8% 78%,0 86%)',opacity:.1},{clipPath:'polygon(0 16%,87% 0,100% 82%,5% 100%)',opacity:1}],{duration:260*scale,fill:'none',easing:'cubic-bezier(.18,.75,.25,1)'});}break;
case 'charge':foreweapon.style.opacity='1';if(!limited&&!skip)this.animate(foreweapon,[{transform:'translate(15px,30px) rotate(-12deg)',opacity:0},{transform:'translate(0,0) rotate(-18deg)',opacity:1}],{duration:230*scale,fill:'none',easing:'ease-out'});break;
case 'trail':cue('motion');cut.style.opacity='0';grade.style.opacity='.25';foreweapon.style.opacity='.2';if(!this.failed.has(magic?'magic':'slash')){trail.style.display='block';if(!limited&&!skip)this.animate(trail,[{opacity:0,transform:'translate(70px,65px) scale(.78)'},{opacity:1,transform:'translate(0,0) scale(1)'}],{duration:180*scale,fill:'none',easing:'cubic-bezier(.08,.65,.18,1)'});}if(!limited&&!skip&&anchor.image){this.animate(anchor.image,[{filter:'brightness(1)'},{filter:'brightness(1.13)'}],{duration:160*scale,fill:'forwards'});}break;
case 'contact':root.className='bp-layer bp-attack';stage.dataset.effect='attack';cue('impact');cue('low');if(!skip)this.audio?.duck(160);trail.style.opacity='.9';impact.style.display=this.failed.has('impactAtlas')?'none':'block';if(!limited&&!skip)this.animate(impact,[{opacity:.9,transform:'scale(.65)'},{opacity:.65,transform:'scale(1)'}],{duration:100*scale,fill:'none'});damage.textContent=String(event?.damage??0);if(event?.combo)make('small','combo-counter',event.combo===1?'첫 타격':event.combo+'연속 공격');break;
case 'reaction':if(!limited&&!skip&&anchor.image){this.animate(anchor.image,[{transform:'scale('+zoom+')',filter:'brightness(1.13)'},{transform:'translate(0,-8px) scale('+(zoom*.985)+')',filter:'brightness(1)'},{transform:'scale('+zoom+')',filter:'brightness(1)'}],{duration:250*scale,easing:'ease-out'});}trail.style.opacity='0';impact.style.opacity='.4';break;
case 'damage':damage.style.display='block';impact.style.opacity='0';if(!limited&&!skip)this.animate(damage,[{opacity:0,transform:'translateY(12px) scale(.85)'},{opacity:1,transform:'translateY(0) scale(1.04)'},{opacity:1,transform:'translateY(-5px) scale(1)'}],{duration:250*scale,fill:'forwards',easing:'cubic-bezier(.18,.75,.2,1)'});if(event?.equipmentBonus){const label=make('small','equipment-proc');label.textContent=(weapon?.id==='flame_greatsword'?'화염 거인의 대검 · ':'장비 · ')+'피해 +'+event.equipmentBonus;label.dataset.s35Equipment='true';}break;
case 'restore':if(!limited&&!ctx.skipped()&&anchor.image)this.animate(anchor.image,[{transform:'scale('+zoom+')'},{transform:'scale(1)'}],{duration:170*scale,fill:'forwards',easing:'ease-in-out'});cut.style.opacity='0';foreweapon.style.opacity='0';grade.style.opacity='0';if(!skip)this.animate(root,[{opacity:1},{opacity:0}],{duration:160*scale,fill:'forwards',easing:'ease-in-out'});break;
}};
try{const event=await runAttackS35({plan:limited?AttackS35Reduced:AttackS35Timeline,wait:ctx.wait,valid,stage:transition,resolve:()=>{const event=ctx.commit();if(event)ctx.update(event);return event;}});return event;}finally{if(token===this.token){this.lastRun={elapsed:performance.now()-started,limited,fast:!!prefs.fast,assetFailures:[...this.failed],trace:[...trace]};this.clear();if(anchor.image)anchor.image.style.transformOrigin=originalOrigin;}}
 }
}
