import {ScrollData} from './ScrollData.js';
// Project-owned WAV assets. All channel controls remain independent.
export const AudioAssets={music:{'boss-final-king':'king-trial-v34','king-dominion':'king-dominion-v34','king-true':'king-true-v34',ending:'ending-v34','boss-dragon':'dragon-boss-suite','boss-chaos':'chaos-boss-suite','boss-knight':'knight-boss-suite','boss-golem':'golem-suite','boss-tree':'tree-boss-suite','boss-flame':'flame-boss-suite',dungeon:'dungeon-suite',battle:'dungeon-suite',boss:'golem-suite',victory:'victory',gameover:'gameover'},effects:{'s35-low':['s35-low-impact'],kingSword:['sword-swing-3'],kingBreath:['dragon-roar'],lawCollapse:['magic-charge'],magicStorm:['chain-lightning'],absoluteOrder:['magic-charge'],roar:['dragon-roar'],wind:['canyon-wind'],guard:['magic-shield'],whoosh:['sword-swing-1','sword-swing-2','sword-swing-3'],attack:['sword-impact-1','sword-impact-2','sword-impact-3'],'scroll-open':['scroll-open'],charge:['magic-charge'],launch:['magic-launch'],magic:['fire-explosion','ice-spear','magic-shield','healing-light','chain-lightning','purification','meteor-impact','time-stop'],collision:['shield-impact'],break:['shield-break'],block:['special-block'],enemy:['player-hit'],defense:['magic-charge'],barrier:['shield-impact']}};
export const SoundMap={tap:[660,.05],number:[740,.06],operator:[590,.07],reserved:[988,.15],wrong:[180,.12],roll:[440,.12],battle:[220,.15],whoosh:[110,.3],attack:[75,.18],enemy:[65,.25],windup:[130,.25],defense:[580,.22],barrier:[760,.25],block:[980,.4],collision:[210,.2],'scroll-open':[700,.4],charge:[900,.5],launch:[350,.3],magic:[60,.6],victory:[1046,.4],gameover:[90,.4],warning:[800,.1],steal:[150,.3],curse:[190,.4],web:[320,.3],poison:[100,.3],shift:[55,.4],stone:[70,.4],laugh:[260,.3],break:[80,.2]};
const assetURL=name=>new URL(`../assets/audio/${name}.wav`,import.meta.url).href;
export class AudioManager{
 constructor(factory=()=>new(window.AudioContext||window.webkitAudioContext)()){
  this.factory=factory;this.context=null;this.active=false;this.track=null;this.voices=new Set();this.channels={BGM:{enabled:true,volume:.25},SFX:{enabled:true,volume:.65},VOICE:{enabled:true,volume:.8}};this.gains={};this.music=null;this.diagnostics=[];this.buffers=new Map();this.loading=new Map();this.mood='input';this.history=[];this.previousVariation={};
 }
 async activate(){try{if(!this.context){const c=this.context=this.factory(),limit=c.createDynamicsCompressor();if(limit.threshold){limit.threshold.value=-12;limit.knee.value=12;limit.ratio.value=5;}limit.connect(c.destination);for(const key of Object.keys(this.channels)){const g=this.gains[key]=c.createGain();g.connect(limit);this.apply(key);}}await this.context.resume();this.active=true;if(this.track&&!this.music?.source)this.playBGM(this.track,true);if(this.context.decodeAudioData)for(const name of new Set(Object.values(AudioAssets.effects).flat()))this.load(name);}catch{this.diagnostics.push('audio-unavailable');}}
 apply(key){const ch=this.channels[key],g=this.gains[key];if(g){g.gain.cancelScheduledValues(this.context.currentTime);g.gain.setTargetAtTime(ch.enabled?ch.volume:0,this.context.currentTime,.05);}}
 configure(key,values){if(!this.channels[key])return;Object.assign(this.channels[key],values);this.channels[key].volume=Math.max(0,Math.min(1,Number(this.channels[key].volume)||0));this.apply(key);}
 async load(name){if(this.buffers.has(name))return this.buffers.get(name);if(this.loading.has(name))return this.loading.get(name);const task=(async()=>{try{const response=await fetch(assetURL(name));if(!response.ok)return null;const buffer=await this.context.decodeAudioData(await response.arrayBuffer());this.buffers.set(name,buffer);return buffer;}catch{return null;}finally{this.loading.delete(name);}})();this.loading.set(name,task);return task;}
 tone(frequency,duration,channel='SFX',type='sine',volume=.065){if(!this.active||!this.channels[channel].enabled||this.voices.size>=12)return;try{const c=this.context,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(frequency,c.currentTime);g.gain.setValueAtTime(.001,c.currentTime);g.gain.exponentialRampToValueAtTime(volume,c.currentTime+.006);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g).connect(this.gains[channel]);this.voices.add(o);o.onended=()=>{this.voices.delete(o);o.disconnect();g.disconnect();};o.start();o.stop(c.currentTime+duration);}catch{this.diagnostics.push('sound-unavailable');}}
 record(name,detail={}){this.history.push({name,time:this.context?.currentTime||0,...detail});if(this.history.length>80)this.history.shift();}
 bufferEffect(name,buffer,{grade='B',type,gainScale=1}={}){if(!this.active||!this.channels.SFX.enabled||this.voices.size>=12)return;try{const c=this.context,source=c.createBufferSource(),gain=c.createGain();source.buffer=buffer;source.playbackRate.value=.98+Math.random()*.04;const strength={C:.72,B:.86,A:1,S:1}[grade]||.86;const level={whoosh:.27,attack:.43,magic:.5,collision:.38,break:.32,block:.44,enemy:.32,charge:.22,launch:.32,'scroll-open':.2}[name]||.3;gain.gain.value=level*(['attack','whoosh'].includes(name)?strength:1)*gainScale;source.connect(gain).connect(this.gains.SFX);this.voices.add(source);source.onended=()=>{this.voices.delete(source);source.disconnect();gain.disconnect();};this.record(name,{grade,type,asset:true,gain:gain.gain.value});source.start();}catch{this.diagnostics.push('sound-unavailable');}}
 play(name,options={}){if(!this.active||!this.channels.SFX.enabled)return;const choices=name==='magic'&&ScrollData[options.type]?[ScrollData[options.type].sound]:AudioAssets.effects[name];if(choices&&this.context.createBufferSource){let index=Math.floor(Math.random()*choices.length);if(choices.length>1&&index===this.previousVariation[name])index=(index+1)%choices.length;this.previousVariation[name]=index;const asset=choices[index],buffer=this.buffers.get(asset);if(buffer)this.bufferEffect(name,buffer,options);else this.load(asset);return;}const [f,d]=SoundMap[name]||SoundMap.tap;this.record(name,{asset:false});this.tone(f,d);}
 duck(milliseconds=450){if(!this.context||!this.music?.gain)return;const g=this.music.gain,now=this.context.currentTime;g.gain.cancelScheduledValues(now);const resting=this.mood==='quiet'?.15:this.mood==='boss-final'?1.08:this.mood==='battle'?.92:.52;g.gain.setTargetAtTime(Math.min(.18,resting*.2),now,.025);g.gain.setTargetAtTime(resting,now+milliseconds/1000,.12);}
 playS35(cue,material,magic){const files={prepare:'magic-charge',motion:magic?'magic-launch':'sword-swing-3',impact:({stone:'shield-impact',metal:'sword-impact-3',leaf:'sword-impact-1',ember:'fire-explosion',scale:'sword-impact-2',arcane:'magic-shield',void:'magic-shield'})[material]||'sword-impact-3',low:'s35-low-impact'},names={prepare:'charge',motion:'whoosh',impact:'attack',low:'s35-low'},levels={prepare:.45,motion:.6,impact:.6,low:.35},buffer=this.buffers.get(files[cue]);if(buffer)this.bufferEffect(names[cue],buffer,{grade:'S',gainScale:levels[cue]});else this.load(files[cue]);}
 setMood(mood){this.mood=mood;const gain=this.music?.gain;if(gain)gain.gain.setTargetAtTime(mood==='quiet'?.15:mood==='boss-final'?1.08:mood==='battle'?.92:.52,this.context.currentTime,.7);}
 playBGM(name,force=false){const asset=AudioAssets.music[name]||AudioAssets.music.dungeon;this.track=name;if(this.music?.asset===asset&&!force)return;const old=this.music;if(old?.source){old.gain.gain.setTargetAtTime(0,this.context.currentTime,.35);try{old.source.stop(this.context.currentTime+2);}catch{}}const music=this.music={asset,source:null,gain:null};if(!this.active||!this.context.createBufferSource)return;
  this.load(asset).then(buffer=>{if(!buffer||this.music!==music||!this.active)return;try{const c=this.context,source=c.createBufferSource(),gain=c.createGain();source.buffer=buffer;source.loop=!['victory','gameover'].includes(name);source.connect(gain).connect(this.gains.BGM);gain.gain.setValueAtTime(0,c.currentTime);gain.gain.setTargetAtTime(this.mood==='quiet'?.15:this.mood==='boss-final'?1.08:this.mood==='battle'?.92:.52,c.currentTime,.8);source.onended=()=>{source.disconnect();gain.disconnect();if(this.music===music)music.source=null;};Object.assign(music,{source,gain});source.start();this.record('music',{asset});}catch{this.diagnostics.push('music-unavailable');}});
 }
 async playAsset(url,channel='SFX'){if(!url||!this.active)return false;try{const response=await fetch(url);if(!response.ok)return false;const buffer=await this.context.decodeAudioData(await response.arrayBuffer());if(!this.active||this.voices.size>=12)return false;const source=this.context.createBufferSource();source.buffer=buffer;source.connect(this.gains[channel]);this.voices.add(source);source.onended=()=>{this.voices.delete(source);source.disconnect();};source.start();return true;}catch{return false;}}
 dispose(){this.active=false;try{this.music?.source?.stop();}catch{}this.music=null;for(const voice of this.voices){try{voice.stop();}catch{}}this.voices.clear();}
}
