import {BossBattleData} from './BossBattleData.js';
import {evaluate} from './ExpressionEngine.js';
const fields=['enemies','scrollIndex','enemyTurn','turn','phase','dice','targets','duration','seconds','elapsed','actionQueue','actionsDone','player','resolutionIndex','resolutionStage','enemyResolutionIndex','totalDamage','scrollStop','scrollWeaken','specialBlocked','blockReserved','curse','shifted','blocked','blockedList','nextBlocked','nextBlockedList','stolen','stolenDuration','mineStatusResolved','choices','intent','hero','heatPoints'];
export function checkpointBoss(s){if(!s.enemies?.some(e=>e.boss)||!['playing','resolution','enemy'].includes(s.phase))return null;const snapshot={encounterIndex:s.encounterIndex};for(const k of fields)if(s[k]!==undefined)snapshot[k]=structuredClone(s[k]);for(const k of ['blockedIds','blockReservedIds'])snapshot[k]=[...(s[k]||[])];return snapshot;}
export function restoreBoss(s,cp){if(!cp||!validateBossCheckpoint(cp)||cp.encounterIndex!==s.encounterIndex||cp.enemies?.length!==s.enemies.length||cp.enemies.some((e,i)=>e.type!==s.enemies[i].type||e.id!==s.enemies[i].id||e.maxHP!==s.enemies[i].maxHP))return false;for(const k of fields)if(cp[k]!==undefined)s[k]=structuredClone(cp[k]);for(const k of ['blockedIds','blockReservedIds'])s[k]=new Set(cp[k]||[]);for(const a of s.actionQueue||[])if(a.scrollSlot)a.scrollSlot=s.scrolls.find(v=>v.type===a.scrollSlot.type)||null;for(const choice of Object.values(s.choices||{}))choice.actions=choice.actions.map(a=>s.actionQueue.find(v=>v.playerId===a.playerId&&v.actionType===a.actionType)||a);s.monsterHP=s.enemies.reduce((n,e)=>n+e.hp,0);s.monsterMaxHP=s.enemies.reduce((n,e)=>n+e.maxHP,0);return true;}
export function validateBossCheckpoint(cp){if(cp===undefined||cp===null)return true;const int=(v,a,b)=>Number.isSafeInteger(v)&&v>=a&&v<=b;
 if(JSON.stringify(cp).length>64000||!int(cp.encounterIndex,0,5)||!['playing','resolution','enemy'].includes(cp.phase)||!int(cp.enemyTurn,1,1e6)||!int(cp.turn,1,1e9)||!Array.isArray(cp.enemies)||cp.enemies.length!==1)return false;
 const e=cp.enemies[0],b=e.boss,d=BossBattleData[e.type];if(!d||!int(e.maxHP,1,10000)||!int(e.hp,0,e.maxHP)||!b||!int(b.phase,1,3)||!int(b.breakTurns,0,d.duration+1)||!int(b.seedTurns,0,2)||!int(b.seedCooldown,0,4)||!Number.isFinite(b.pressure)||b.pressure<0||b.pressure>d.limit||!Number.isFinite(b.seedPressure)||b.seedPressure<0||b.seedPressure>d.limit||!int(b.breaks,0,1e6)||!Array.isArray(b.announced)||b.announced.some(v=>!int(v,1,b.phase))||new Set(b.announced).size!==b.announced.length)return false;
 if(!cp.hero||!int(cp.hero.hp,0,10000)||!int(cp.hero.shield,0,1e9)||!Array.isArray(cp.actionQueue)||cp.actionQueue.length>4||cp.actionQueue.some(a=>!['attack','scroll','defense','block'].includes(a.actionType)||!['pending','resolved','cancelled'].includes(a.status)||a.playerId!==0)||!int(cp.resolutionIndex,0,4)||!['actions','total','victory','enemy','special','enemy-next','status','end',null].includes(cp.resolutionStage)||!Array.isArray(cp.targets)||cp.targets.length!==8||!Array.isArray(cp.dice)||cp.dice.length!==3)return false;
 if(!Array.isArray(cp.actionsDone)||cp.actionsDone.length!==1||cp.actionsDone.some(v=>typeof v!=='boolean')||!cp.choices||typeof cp.choices!=='object'||Array.isArray(cp.choices)||Object.values(cp.choices).some(c=>!c||!['attack','block'].includes(c.kind)||!Array.isArray(c.actions)||c.actions.length>2)||!int(cp.duration,1,60)||!int(cp.seconds,0,cp.duration)||!int(cp.enemyResolutionIndex??0,0,1)||cp.dice.some((v,i)=>!int(v,1,[8,10,12][i])))return false;
 if(!int(cp.scrollIndex??0,0,9)||!Number.isFinite(e.attackModifier)||e.attackModifier<0||e.attackModifier>3||!Number.isFinite(e.weaken)||e.weaken<0||e.weaken>1||!int(cp.hero.poison??0,0,3)||!int(cp.hero.burn??0,0,2))return false;
 if(cp.targets.some(t=>!t||!['attack','defense'].includes(t.side)||!['S','A','B','C'].includes(t.grade)||typeof t.used!=='boolean'||!int(t.position,0,3))||new Set(cp.targets.map(t=>t.side+t.grade)).size!==8)return false;
 try{for(const t of cp.targets)if(evaluate(cp.dice,t.solution.ids,t.solution.ops).value!==t.value)return false;}catch{return false;}
 for(const key of ['blockedIds','blockReservedIds'])if(!Array.isArray(cp[key])||cp[key].some(id=>id!==e.id))return false;
 return true;
}
