import {BossBattleData} from './BossBattleData.js';
import {evaluate} from './ExpressionEngine.js';
const fields=['enemies','scrollIndex','enemyTurn','turn','phase','dice','targets','duration','seconds','elapsed','actionQueue','actionsDone','player','resolutionIndex','resolutionStage','enemyResolutionIndex','totalDamage','scrollStop','scrollWeaken','specialBlocked','blockReserved','curse','shifted','blocked','blockedList','nextBlocked','nextBlockedList','stolen','stolenDuration','mineStatusResolved','choices','intent','hero','heatPoints','morale','moraleDefeated','darkBlessingTurn','chaos','chaosTurn','chaosTutorial'];
export function checkpointBoss(s){if(!(s.enemies?.some(e=>e.boss)||['black-fortress','chaos-tower','sky-canyon'].includes(s.battleContext?.dungeonId))||!['playing','resolution','enemy'].includes(s.phase))return null;const snapshot={...(s.battleContext?.dungeonId==='sky-canyon'?{canyon:true}:{}),...(s.battleContext?.dungeonId==='chaos-tower'?{tower:true}:{}),encounterIndex:s.encounterIndex,...(s.battleContext?.dungeonId==='black-fortress'?{fortress:true}:{})};for(const k of fields)if(s[k]!==undefined)snapshot[k]=structuredClone(s[k]);for(const k of ['blockedIds','blockReservedIds'])snapshot[k]=[...(s[k]||[])];if(s.canyon){snapshot.canyonState=structuredClone(s.canyon);snapshot.canyon=true;}return snapshot;}
export function restoreBoss(s,cp){if(!cp||!validateBossCheckpoint(cp)||cp.encounterIndex!==s.encounterIndex||cp.enemies?.length!==s.enemies.length||cp.enemies.some((e,i)=>e.type!==s.enemies[i].type||e.id!==s.enemies[i].id||e.maxHP!==s.enemies[i].maxHP))return false;for(const k of fields)if(cp[k]!==undefined)s[k]=structuredClone(cp[k]);if(cp.canyonState)s.canyon=structuredClone(cp.canyonState);for(const k of ['blockedIds','blockReservedIds'])s[k]=new Set(cp[k]||[]);for(const a of s.actionQueue||[])if(a.scrollSlot)a.scrollSlot=s.scrolls.find(v=>v.type===a.scrollSlot.type)||null;for(const choice of Object.values(s.choices||{}))choice.actions=choice.actions.map(a=>s.actionQueue.find(v=>v.playerId===a.playerId&&v.actionType===a.actionType)||a);s.monsterHP=s.enemies.reduce((n,e)=>n+e.hp,0);s.monsterMaxHP=s.enemies.reduce((n,e)=>n+e.maxHP,0);return true;}
export function validateBossCheckpoint(cp){if(cp===undefined||cp===null)return true;const int=(v,a,b)=>Number.isSafeInteger(v)&&v>=a&&v<=b;
 if(cp.tower!==undefined&&typeof cp.tower!=='boolean')return false;
 if(cp.chaosTutorial!==undefined&&typeof cp.chaosTutorial!=='boolean')return false;
 if(cp.tower){const c=cp.chaos,t=cp.chaosTurn;if(!c||!int(c.level,0,3)||!Array.isArray(c.defeated)||new Set(c.defeated).size!==c.defeated.length||c.defeated.some(id=>!cp.enemies?.some(e=>e.id===id))||['shuffle','prophecy','mask'].some(k=>typeof c[k]!=='boolean')||!int(c.timePenalty,0,5)||!t||!Array.isArray(t.maskIds)||t.maskIds.length>2||t.maskIds.some(id=>!cp.targets?.some(v=>v.id===id))||typeof t.prophecy!=='boolean'||t.body!==null&&!int(t.body,0,2))return false;}
 if(cp.fortress!==undefined&&typeof cp.fortress!=='boolean')return false;
 if(JSON.stringify(cp).length>64000||!int(cp.encounterIndex,0,5)||!['playing','resolution','enemy'].includes(cp.phase)||!int(cp.enemyTurn,1,1e6)||!int(cp.turn,1,1e9)||!Array.isArray(cp.enemies)||(cp.fortress||cp.tower||cp.canyon?cp.enemies.length<1||cp.enemies.length>3:cp.enemies.length!==1))return false;
 if(cp.canyon!==undefined&&typeof cp.canyon!=='boolean')return false;if(cp.canyon&&(!cp.canyonState||typeof cp.canyonState.threat!=='boolean'||!int(cp.canyonState.bloodTurn,0,1e9)||cp.canyonState.guardId!==null&&!cp.enemies?.some(e=>e.id===cp.canyonState.guardId)||cp.enemies.some(e=>!['dragonLizard','fireWyvern','dragonGuard','dragonShaman','dragonGuardian'].includes(e.type)||!int(e.hp,0,e.maxHP)||!int(e.maxHP,1,10000))))return false;const ordinary=cp.canyon&&cp.enemies.every(e=>['dragonLizard','fireWyvern','dragonGuard','dragonShaman'].includes(e.type)&&!e.boss)||cp.tower&&cp.enemies.every(e=>['bookSpirit','illusionist','chaosApostle','timeKeeper'].includes(e.type)&&!e.boss)||cp.fortress&&cp.enemies.every(e=>['demonSoldier','darkArcher','demonCommander','darkPriest'].includes(e.type)&&!e.boss);if(cp.fortress&&(!int(cp.morale,0,6)||!int(cp.darkBlessingTurn??0,0,1e9)||!Array.isArray(cp.moraleDefeated)||new Set(cp.moraleDefeated).size!==cp.moraleDefeated.length||cp.moraleDefeated.some(id=>!cp.enemies.some(e=>e.id===id))||cp.enemies.some(e=>!int(e.maxHP,1,10000)||!int(e.hp,0,e.maxHP)||!Number.isFinite(e.attackModifier)||e.attackModifier<0||e.attackModifier>3||!Number.isFinite(e.weaken)||e.weaken<0||e.weaken>1)))return false;
 if(cp.tower&&cp.enemies.some(e=>!['bookSpirit','illusionist','chaosApostle','timeKeeper','chaosMage'].includes(e.type)||!int(e.hp,0,e.maxHP)||!int(e.maxHP,1,10000)||!Number.isFinite(e.attackModifier)||e.attackModifier<0||e.attackModifier>3||!Number.isFinite(e.weaken)||e.weaken<0||e.weaken>1))return false;
 if(cp.tower&&cp.actionQueue?.some(a=>a.appearance!==undefined&&!int(a.appearance,0,2)))return false;
 const e=cp.enemies[0],b=e.boss,d=BossBattleData[e.type];if(!ordinary&&(!d||!int(e.maxHP,1,10000)||!int(e.hp,0,e.maxHP)||!b||!int(b.phase,1,3)||!int(b.breakTurns,0,d.duration+1)||!int(b.seedTurns,0,2)||!int(b.seedCooldown,0,4)||!Number.isFinite(b.pressure)||b.pressure<0||b.pressure>d.limit||!Number.isFinite(b.seedPressure)||b.seedPressure<0||b.seedPressure>d.limit||!int(b.breaks,0,1e6)||!Array.isArray(b.announced)||b.announced.some(v=>!int(v,1,b.phase))||new Set(b.announced).size!==b.announced.length))return false;
 if(e.type==='dragonGuardian'&&(!['GROUNDED','FLYING','BROKEN'].includes(b.stance)||!int(b.groundTurns,0,2)||!int(b.breathCharge,0,3)||!int(b.phaseTurn,0,1e9)||(!!b.breakTurns)!==(b.stance==='BROKEN')))return false;
 if(!cp.hero||!int(cp.hero.hp,0,10000)||!int(cp.hero.shield,0,1e9)||!Array.isArray(cp.actionQueue)||cp.actionQueue.length>4||cp.actionQueue.some(a=>!['attack','scroll','defense','block'].includes(a.actionType)||!['pending','resolved','cancelled'].includes(a.status)||a.playerId!==0)||!int(cp.resolutionIndex,0,4)||!['actions','total','victory','enemy','special','enemy-next','status','end',null].includes(cp.resolutionStage)||!Array.isArray(cp.targets)||cp.targets.length!==8||!Array.isArray(cp.dice)||cp.dice.length!==3)return false;
 if(!Array.isArray(cp.actionsDone)||cp.actionsDone.length!==1||cp.actionsDone.some(v=>typeof v!=='boolean')||!cp.choices||typeof cp.choices!=='object'||Array.isArray(cp.choices)||Object.values(cp.choices).some(c=>!c||!['attack','block'].includes(c.kind)||!Array.isArray(c.actions)||c.actions.length>2)||!int(cp.duration,1,60)||!int(cp.seconds,0,cp.duration)||!int(cp.enemyResolutionIndex??0,0,cp.enemies.length)||cp.dice.some((v,i)=>!int(v,1,[8,10,12][i])))return false;
 if(!int(cp.scrollIndex??0,0,9)||!Number.isFinite(e.attackModifier)||e.attackModifier<0||e.attackModifier>3||!Number.isFinite(e.weaken)||e.weaken<0||e.weaken>1||!int(cp.hero.poison??0,0,3)||!int(cp.hero.burn??0,0,2))return false;
 if(cp.targets.some(t=>!t||!['attack','defense'].includes(t.side)||!['S','A','B','C'].includes(t.grade)||typeof t.used!=='boolean'||!int(t.position,0,3))||new Set(cp.targets.map(t=>t.side+t.grade)).size!==8)return false;
 try{for(const t of cp.targets)if(evaluate(cp.dice,t.solution.ids,t.solution.ops).value!==t.value)return false;}catch{return false;}
 for(const key of ['blockedIds','blockReservedIds'])if(!Array.isArray(cp[key])||cp[key].some(id=>!cp.enemies.some(e=>e.id===id)))return false;
 return true;
}
