import {DragonRules as R} from './CanyonData.js';
import {takeDamage} from './DefenseSystem.js';
export const inCanyon=s=>s?.battleContext?.mode==='rpg'&&s.battleContext.dungeonId==='sky-canyon';
export function initCanyon(s){if(inCanyon(s))s.canyon={threat:[1,2,3].includes(s.encounterIndex),guardId:null,bloodTurn:0};}
export function canyonTurn(s){if(!inCanyon(s))return;const c=s.canyon;c.guardId=null;for(const e of s.enemies){if(e.hp<=0)continue;if(e.type==='fireWyvern')e.flight=true;if(e.type==='dragonGuard'&&e.intent.special==='dragonGuard')c.guardId=e.id;if(c.bloodTurn===s.enemyTurn)e.intent.attack+=R.bloodAttack;}if(c.threat&&s.enemyTurn===1)s.enemies.find(e=>e.hp>0).intent={...s.enemies.find(e=>e.hp>0).intent,special:'dragonThreat'};}
export function canyonDamage(s,e,grade,n){if(!inCanyon(s)||n<=0)return n;let mult=1;if((e.flight||e.boss?.stance==='FLYING')&&!['A','S'].includes(grade))mult*=R.flightDamage;const guard=s.enemies.find(v=>v.id===s.canyon.guardId&&v.hp>0);if(guard&&guard!==e)mult*=R.guardDamage;return Math.max(1,Math.round(n*mult));}
export function canyonSpecial(s,e,sp){if(!inCanyon(s))return false;if(sp==='dragonGuard')return true;if(sp==='dragonBlood'){s.canyon.bloodTurn=s.enemyTurn+1;return true;}const damage={quickClaw:2,smallBreath:3,dragonThreat:R.threatDamage,fireBombard:12,doomBreath:R.breathDamage}[sp];if(damage!==undefined){if(!e.boss?.breakTurns)takeDamage(s,damage,'enemy');return true;}return false;}
export function assistWings(e,n){const b=e?.boss;if(e?.type!=='dragonGuardian'||e.hp<=0||b.stance!=='FLYING'||b.breakTurns)return false;b.pressure=Math.min(R.assistCap,b.pressure+n);return true;}
export function scrollWings(s,action,scroll){if(!scroll||!['ice','iceStorm','lightning','meteor'].includes(action.scrollSlot?.type))return;for(const e of s.enemies||[])if(scroll.impacts?.some(i=>i.enemyId===e.id)||action.enemyId===e.id)assistWings(e,R.scrollPressure);}
export function canyonHint(s,e){if(e.boss)return '';if(e.type==='fireWyvern')return '비행 · C/B 검격 피해 75% · A/S와 두루마리는 정상 적중';if(e.type==='dragonGuard')return s.canyon?.guardId===e.id?'수호 태세 · 다른 적의 검격 피해 25% 감소':'방패를 다시 준비 중';if(e.type==='dragonShaman')return '용의 피 · 다음 턴 살아 있는 적의 일반 공격 +2';return '빠른 발톱 · 추가 피해 2';}
export function canyonHTML(s){if(!inCanyon(s))return '';return '<aside class="canyon-hud" role="status"><b>🐉 용을 추격 중 · '+s.encounter.name+'</b><span>'+(s.canyon.threat&&s.enemyTurn===1?'⚠ 용의 위협 · 이번 턴 끝 불길 +3 · 방어 S로 차단 가능':'용의 그림자를 따라 다음 지점으로 이동하세요')+'</span><small>수호병의 방패 · 주술사의 강화 · 비행 적의 날개를 관찰하세요.</small></aside>';}
