import {campaign} from './ActTwoSystem.js';
import {artHTML} from './AssetManifest.js';
import {equipmentById} from './EquipmentData.js';
import {equipmentCard} from './EquipmentView.js';
import {mercenaryById} from './MercenaryData.js';
import {relation} from './AffinitySystem.js';
import {ScrollData} from './ScrollData.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function finishCastleOpening(p){const c=campaign(p);if(p.run||!c.castleOpened)return false;c.actThreeSeen=true;if(!p.unlockedDungeons.includes('demon-castle'))p.unlockedDungeons.push('demon-castle');return true;}
export const castleRestPending=r=>r?.dungeonId==='demon-castle'&&r.pendingLoot?.encounterIndex===3&&r.pendingLoot.chosen&&!r.restDeparted;
export function restCastle(data){const r=data.progress.run,c=data.character;if(!castleRestPending(r)||r.restUsed)return false;const gain=Math.min(c.maxHP-c.hp,Math.round(c.maxHP*.35));c.hp+=gain;r.restUsed=true;r.restHeal=gain;return gain;}
export function finishCastleTruth(p){if(!castleRestPending(p.run))return false;campaign(p).eliaTruthSeen=true;p.run.castleTruthSeen=true;return true;}
export function reachThrone(p){if(p.run?.dungeonId!=='demon-castle'||p.run.status!=='clear'||!p.run.pendingLoot?.chosen)return false;campaign(p).throneSceneSeen=true;return true;}
const departure={rowen:'여기까지 왔는데 마지막까지 같이 가야지.',bram:'이번에는 반드시 지켜내겠다.',sera:'돌아오는 길까지 함께할게요.',luna:'마왕의 마력… 드디어 직접 확인할 수 있겠네.',kain:'마지막 상대인가.',elia:'……이제 숨길 수 없겠네.'};
function companionLine(p,rest=false){const m=mercenaryById(p.activeMercenary);if(!m)return '혼자 떠나도 계산으로 길을 열 수 있어요.';const level=relation(p,m.id).affinityLevel;return level===3?departure[m.id]:level===2&&rest?'여기까지 함께 쌓은 믿음이 있어. 마지막 길도 같이 가자.':rest?'조금 쉬었으면 함께 왕좌로 가자.':'드디어 마왕의 성이군. 꼭 돌아오자.';}
function supplies(session){const c=session.character,m=mercenaryById(session.data.progress.activeMercenary),stats=session.stats();return '<section class="castle-supplies"><h2>'+esc(c.name)+' · Lv.'+c.level+'</h2><p>HP '+c.hp+' / '+c.maxHP+' · 공격력 '+stats.attack+' · 방어력 '+stats.defense+'</p><div class="castle-equipment">'+['weapon','armor','accessory'].map((slot,i)=>'<span>'+['⚔ 무기','🛡 방어구','💍 장신구'][i]+' · '+esc(equipmentById(c.equipment[slot])?.name||'미장착')+'</span>').join('')+'</div><h3>보유 두루마리</h3><div class="castle-scrolls">'+(c.scrolls.map(s=>'<span>'+artHTML(s.type)+' '+ScrollData[s.type].name+' ×'+s.uses+'</span>').join('')||'보유 없음')+'</div><p>동행 · '+(m?artHTML(m.id)+esc(m.name)+' · 관계 '+relation(session.data.progress,m.id).affinityLevel:'혼자 모험')+'</p></section>';}
export function castlePreparationHTML(session){return '<main class="rpg-shell castle-preparation">'+artHTML('castleGate',{className:'castle-panorama',eager:true})+'<section class="castle-panel"><div class="eyebrow">제3막 · 최종 던전 · 권장 Lv.12+</div><h1>마왕의 성</h1><h2>왕좌까지 도달하라.</h2><p>4개 전투 → 봉인의 방에서 35% 회복 1회 → 2개 전투 → 왕좌의 문</p>'+supplies(session)+'<blockquote>“'+esc(companionLine(session.data.progress))+'”</blockquote><nav><button class="secondary" data-action="rpg-inventory">장비 변경</button><button class="secondary" data-action="rpg-mercenaries">용병 길드</button><button class="secondary" data-action="rpg-character">스크롤 확인</button><button class="primary" data-action="rpg-castle-depart">마왕의 성으로 →</button><button class="text-button" data-action="rpg-town">마을에 머무르기</button></nav></section></main>';}
const opening=[['제3막 · 마왕의 성','세 개의 봉인이 모두 사라졌어. 이제 마왕의 성으로 갈 수 있다.','길드 마스터'],['출발 전의 침묵','여기서부터는 우리가 도와줄 수 없어. 반드시 돌아와.','길드 마스터']];
const truth=[['말하지 못한 진실','네가 이곳에 온 것이 완전히 우연은 아니야. 나는 알고 있었어.','엘리아'],['뭘 알고 있었던 거야?','누군가가 다른 세계에서 이곳으로 불려올 거라는 걸. 하지만 그게 너일 줄은 몰랐어.','엘리아'],['수학 같은 거 필요 없어.','네가 그렇게 말한 순간 마법의 조건이 맞아 두 세계가 연결됐어. 이 세계의 숫자, 연산, 논리는 실제 마법의 법칙이야. 네 사칙연산 전투도 우연이 아니야.','엘리아'],['그럼 처음부터 알고 있었던 거야?','전부는 아니야. 확신이 없었고, 네가 나를 믿지 못할까 두려웠어. 미리 말하지 못해서 미안해. 마왕은 네가 성장할 가능성을 알고 있었어. 하지만 왜 너를 불렀는지는 나도 다 알지 못해.','엘리아'],['왕좌로 향하라','진실을 알고 싶다면 왕좌까지 가. 마왕이 직접 대답해야 할 일이니까.','엘리아']];
const throne=[['왕좌의 문','괴물의 발소리가 사라지고, 긴 복도에 숨소리만 남았습니다. 거대한 문이 천천히 열립니다.','용사'],['드디어 왔군','성장한 네가 이 왕좌에 도달했구나. 네 질문에 답할 때가 가까워졌다.','마왕'],['마지막 질문','왜 나를 이 세계로 불렀지? · 그 대답과 실제 마왕전은 v3.4에서 이어집니다.','용사']];
export const castleSceneLast=kind=>kind==='castle-opening'?1:kind==='castle-truth'?4:2;
export function castleSceneHTML(kind,index,p){const list=kind==='castle-opening'?opening:kind==='castle-truth'?truth:throne,i=Math.min(list.length-1,Math.max(0,index)),[title,line,speaker]=list[i],direct=p.activeMercenary==='elia',art=kind==='castle-opening'?'castleGate':kind==='castle-truth'?'sealChamber':i===1?'kingAwakens':'throneDoor';return '<main class="rpg-opening castle-scene">'+artHTML(art,{className:'castle-panorama',eager:true})+'<section class="opening-dialogue"><div class="eyebrow">'+(kind==='castle-truth'?(direct?'동행 엘리아의 고백':'기억의 수정 · 엘리아가 남긴 마법 기록'):'제3막 · 마왕의 성')+' · '+(i+1)+'/'+list.length+'</div><h1>'+title+'</h1><small>'+speaker+'</small>'+(kind==='castle-truth'&&[1,3].includes(i)?'<blockquote class="castle-hero-response">용사 · “'+(i===1?'뭘?':'그럼 처음부터 알고 있었던 거야?')+'”</blockquote>':'')+'<blockquote>“'+line+'”</blockquote><nav><button class="secondary" data-action="rpg-castle-scene-end" data-kind="'+kind+'">'+(kind==='castle-truth'?'기록 읽기 완료':'장면 마치기')+'</button><button class="primary" data-action="'+(i===list.length-1?'rpg-castle-scene-end':'rpg-castle-scene-next')+'" data-kind="'+kind+'" data-index="'+i+'">'+(i===list.length-1?'이야기 계속하기 →':'다음 이야기 →')+'</button></nav></section></main>';}
export function castleRestHTML(session){const r=session.run,p=session.data.progress,tab=session.castleRestTab||'supplies';return '<div class="overlay castle-overlay"><section class="modal castle-panel" role="dialog" aria-label="봉인의 방">'+artHTML('sealChamber',{className:'castle-rest-art',eager:true})+'<div class="eyebrow">안전한 휴식 · 마력 용광로 돌파</div><h1>봉인의 방</h1><p>마왕군의 힘이 닿지 않는 고대 공간. 상점과 새 보급은 없습니다.</p>'+supplies(session)+'<p role="status">'+(r.restUsed?'✓ 휴식 사용 완료 · HP +'+r.restHeal:'최대 HP의 35% 회복 · 이번 모험에 한 번')+'</p><nav><button class="primary" data-action="rpg-castle-rest" '+(r.restUsed?'disabled':'')+'>휴식하기</button><button class="secondary" data-action="rpg-castle-gear">보유 장비 교체</button><button class="secondary" data-action="rpg-castle-talk">동료와 대화</button><button class="secondary" data-action="rpg-castle-truth">'+(p.campaign.eliaTruthSeen?'엘리아의 진실 다시 읽기':'기억의 수정 · 엘리아의 진실')+'</button></nav>'+(tab==='gear'?'<div class="equipment-grid">'+session.character.inventory.items.map(id=>equipmentCard(equipmentById(id),true,session.character).replace(/<button class="secondary" data-action="rpg-sell"[\s\S]*?<\/button>/,'').replace('data-action="rpg-equip"','data-action="rpg-castle-equip"')).join('')+'</div>':tab==='talk'?'<blockquote>“'+esc(companionLine(p,true))+'”</blockquote>':'')+'<button class="primary" data-action="rpg-castle-rest-depart" '+(!r.restUsed||!p.campaign.eliaTruthSeen?'disabled':'')+'>왕좌로 향하라 → 용의 전당</button></section></div>';}
export function castleDoorHTML(session){return '<div class="overlay castle-overlay"><section class="modal castle-panel" role="dialog" aria-label="왕좌 앞 준비">'+artHTML('throneDoor',{className:'castle-rest-art',eager:true})+'<div class="eyebrow">왕좌의 수호자 격파 · 더 이상 몬스터 없음</div><h1>마왕의 왕좌</h1><h2>이 문 너머에 마왕이 있습니다.</h2>'+supplies(session)+'<nav><button class="secondary" data-action="rpg-return">마을로 돌아가기</button><button class="primary" data-action="rpg-castle-throne">준비를 마쳤다</button></nav><small>왕좌 입장 장면 · 실제 최종 전투는 v3.4에서 이어집니다.</small></section></div>';}
