import {campaign} from './ActTwoSystem.js';
import {artHTML} from './AssetManifest.js';
import {sealsHTML} from './ActTwoView.js';
export const chaosFlags=()=>({chaosOpeningSeen:false,towerInvestigated:false,mageDefeated:false,chaosSealSeen:false});
export function finishChaosOpening(p){if(p.run||!campaign(p).seals.darkness)return false;campaign(p).chaosOpeningSeen=true;return true;}
export function investigateTower(p){const c=campaign(p);if(p.run||!c.seals.darkness||!c.chaosOpeningSeen)return false;c.towerInvestigated=true;if(!p.unlockedDungeons.includes('chaos-tower'))p.unlockedDungeons.push('chaos-tower');return true;}
export function finishChaosSeal(p){const c=campaign(p);if(!c.mageDefeated||!p.clearedDungeons.includes('chaos-tower'))return false;c.chaosSealSeen=true;c.seals.chaos=true;return true;}
export function chaosStoryHTML(kind,index,p){const merc=p.activeMercenary||p.dungeonClearHistory.at(-1)?.mercenaryId;
 const opening=[['guild','서로 다른 기억','첫 번째 봉인이 사라졌어. 하지만 이상한 일이 생기고 있다. 마을 곳곳에서 같은 장소를 봤는데도 사람들의 기억이 서로 달라.','길드 마스터'],['tower','금지된 마력','공간 마법의 흔적이야. 혼돈의 마법사가 쓰는 마력은 루나가 연구했던 금지된 마법과 같은 계통이다.','루나의 연구 기록'],['tower','뒤틀린 공간','혼돈의 마력의 근원을 조사하세요. 길드에서 조사하면 혼돈의 마탑이 열립니다.','새 메인 목표']];
 const seal=[['mage','환영이 흩어지다','재미있군…… 하지만 진실을 알게 된 뒤에도 마왕을 쓰러뜨리고 싶을까?','혼돈의 마법사'],['circle','혼돈의 봉인','닫혀 가는 공간 균열 속에 거대한 마법진이 모습을 드러냅니다.','두 번째 봉인'],['crack','마법진의 균열','용사의 마지막 검격이 봉인에 닿습니다. 진실의 빛이 균열 사이로 번집니다.','봉인 파괴'],['shatter','혼돈의 봉인 파괴','환영이 하나씩 깨지고, 뒤틀린 공간이 제자리로 돌아옵니다.','두 번째 봉인 해제'],['map','두 개의 봉인을 넘어서','어둠의 봉인 ✓ · 혼돈의 봉인 ✓ · 용의 봉인 🔒','남은 봉인 1개'],['dragon','용의 수호자','두 봉인이 사라졌군. 이제 내가 직접 움직일 차례인가.','다음 목표 · 용의 봉인']];
 const cuts=kind==='chaos-seal'?seal:opening,i=Math.max(0,Math.min(cuts.length-1,index)),[scene,title,base,speaker]=cuts[i];let text=base;
 if(kind==='chaos-opening'&&i===0&&merc==='luna')text+=' “공간 마법의 흔적이야.” — 루나';if(kind==='chaos-opening'&&i===0&&merc==='elia')text+=' “아니… 이것은 단순한 공간 마법이 아니야. 혼돈의 마법사가 움직이기 시작했어.” — 엘리아';
 if(i===1&&kind==='chaos-opening'&&p.mercenaryRelations.luna.personalQuestCompleted)text+=' 루나는 개인 모험에서 마주했던 금지된 마력의 흔적을 떠올립니다.';
 if(scene==='mage'&&merc==='elia')text+=' 엘리아는 잠시 눈을 내리깝니다. “……아직은 말할 수 없어.”';
 return `<div class="act-two-scene chaos-story scene-${scene}" role="dialog" aria-modal="true" aria-label="혼돈의 마탑 이야기"><div class="act-scene-art">${artHTML(scene==='guild'?'guild':scene==='dragon'?'throne':'tower',{eager:true})}${scene==='mage'?'<div class="chaos-defeat-shapes">'+[0,1,2].map(n=>'<div class="mage-form form-'+n+'">'+artHTML(n===1?'mageDown':'chaosMage',{eager:true})+'</div>').join('')+'</div>':''}${['circle','crack','shatter'].includes(scene)?'<div class="chaos-seal-circle">✦</div>':''}${scene==='dragon'?'<svg class="dragon-teaser" viewBox="0 0 600 300" aria-label="멀리 떠오른 용의 그림자"><path d="M300 190 250 70 60 30 150 170 265 205 280 270 315 270 335 210 480 170 560 30 350 70 330 160 350 135 345 80 325 100 300 85 290 140Z"/></svg>':''}</div><section class="act-dialogue"><div class="eyebrow">${speaker} · ${i+1}/${cuts.length}</div><h1>${title}</h1><p>${text}</p>${scene==='map'?sealsHTML(p,'chaos'):''}${scene==='dragon'?'<p>거대한 포효가 멀리서 울립니다. 용의 둥지는 다음 이야기에서 열립니다. 지금은 입장할 수 없어요.</p>':''}<div class="opening-actions"><button class="secondary" data-action="rpg-act-skip" data-kind="${kind}">연출 건너뛰기</button><button class="primary" data-action="rpg-act-next" data-kind="${kind}" data-index="${i}">${i===cuts.length-1?'모험으로 →':'다음 이야기 →'}</button></div></section></div>`;
}
