import {createClassContext} from './BattleContext.js';
import {livingEnemies,syncEncounter} from './EncounterData.js';
import {bossData,pressureBoss} from './BossBattleSystem.js';
export const CoopDifficulties={easy:{name:'쉬움',hp:.78,attack:.78},normal:{name:'보통',hp:1,attack:1},hard:{name:'어려움',hp:1.18,attack:1.25}};
const enemy=(type,hpModifier=1,attackModifier=1)=>({type,hpModifier,attackModifier});
export function createCoopContext(players=4,difficulty='normal',route='golem'){
 if(!Number.isInteger(players)||players<2||players>4)throw new Error('협동전은 2~4명이 함께합니다.');const level=CoopDifficulties[difficulty]||CoopDifficulties.normal;
 const encounters=[{id:'coop-entry',name:'첫 연계 · 해골 문지기',enemies:[enemy('skeleton',1.05,.9)]},{id:'coop-twins',name:'목표 분배 · 고블린의 매복',enemies:[enemy('goblin',.48,.58),enemy('skeleton',.55,.85)]},{id:'coop-elite',name:'정예전 · 저주의 경비대',enemies:[enemy('orc',.55,.58),enemy('spider',.45,.5)]},{id:'coop-boss',name:route==='dragon'?'마지막 시험 · 용의 수호자':'마지막 문 · 거대한 골렘',enemies:[enemy(route==='dragon'?'dragonGuardian':'golem',route==='dragon'?.72:1.05,.7)]}].map(v=>({...v,rewardModifier:1,enemies:v.enemies.map(e=>({...e,hpModifier:e.hpModifier*level.hp*(players===2?.72:players===3?.9:1),attackModifier:e.attackModifier*level.attack}))}));
 return {...createClassContext(),coop:true,coopPlayers:players,coopDifficulty:difficulty,coopRoute:route,heroMaxHP:180,encounters};
}
export const isCoop=s=>s?.battleContext?.mode==='class'&&s.battleContext.coop===true;
export function initCoopRun(s){if(!isCoop(s))return; s.coopRun={buffs:{attack:0,defense:0,time:0},choices:[],comboDamage:0,perfectTurns:0};s.coopMeters={};}
export function beginCoopRound(s){if(!isCoop(s))return;s.coopRound={turn:s.turn,contributors:[],quality:'C',sCount:0,bonusRate:0,bonusDamage:0,committed:false,theft:false,secondsLeft:0,early:false,contributions:[]};}
export function prepareCoopResolution(s){if(!isCoop(s))return;const primary=s.actionQueue.filter(a=>['attack','defense'].includes(a.actionType)),contributors=[...new Set(primary.map(a=>a.playerId))],weights={C:1,B:2,A:3,S:4},mean=primary.reduce((n,a)=>n+weights[a.targetGrade],0)/Math.max(1,contributors.length);Object.assign(s.coopRound,{contributors,quality:mean>=3.25?'S':mean>=2.5?'A':mean>=1.5?'B':'C',sCount:primary.filter(a=>a.targetGrade==='S').length,bonusRate:contributors.length===s.players?(s.players===4?.12:.10):contributors.length>=3?.04:0,secondsLeft:s.seconds,early:s.seconds>0&&contributors.length===s.players});}
export function commitCoopCombo(s){if(!isCoop(s)||!s.coopRound||s.coopRound.committed)return null;const round=s.coopRound;round.committed=true;const requested=Math.floor(s.totalDamage*round.bonusRate);let remaining=requested,damage=0;for(const e of livingEnemies(s)){const hit=Math.min(e.hp,remaining);e.hp-=hit;remaining-=hit;damage+=hit;if(!remaining)break;}syncEncounter(s);s.totalDamage+=damage;round.bonusDamage=damage;s.coopRun.comboDamage+=damage;if(round.contributors.length===s.players)s.coopRun.perfectTurns++;return {damage,requested,contributors:round.contributors.length,playerIds:[...round.contributors],players:s.players,quality:round.quality,sCount:round.sCount,perfect:round.contributors.length===s.players};}
export function recordCoopContribution(s,event){if(!isCoop(s)||!s.coopRound||!event.action)return;const id=event.action.playerId;if(!Number.isInteger(id))return;let row=s.coopRound.contributions.find(v=>v.playerId===id);if(!row){row={playerId:id,damage:0,shield:0,blocked:false};s.coopRound.contributions.push(row);}if(['attack','magic'].includes(event.kind))row.damage+=event.damage||0;if(event.kind==='defense')row.shield+=event.shieldGain||0;}
export function chooseCoopBuff(s,id){if(!isCoop(s)||s.phase!=='reward'||s.coopRun.choices.some(v=>v.encounter===s.encounterIndex)||!['attack','defense','time'].includes(id))return false;const buffs=s.coopRun.buffs;if(id==='time')buffs.time=Math.min(15,buffs.time+5);else buffs[id]=Math.min(.3,Math.round((buffs[id]+.1)*10)/10);s.coopRun.choices.push({encounter:s.encounterIndex,id});s.lootChosen=true;return true;}
export function coopPressure(s,e,grade){if(!isCoop(s))return pressureBoss(e,grade);const d=bossData(e),b=e?.boss;if(!d||!b||e.hp<=0||b.breakTurns||b.phase<(d.activationPhase||1)||d.pressureWindow==='seed'&&!b.seedTurns||e.type==='dragonGuardian'&&b.stance!=='FLYING')return false;const meter=s.coopMeters[e.id]??={value:0,limit:s.players*4};meter.value=Math.min(meter.limit,meter.value+({C:1,B:2,A:3,S:4}[grade]||0));if(meter.value<meter.limit)return false;for(let i=0;i<16&&!b.breakTurns;i++)pressureBoss(e,'S');if(!b.breakTurns)return false;meter.value=0;return true;}
export function stealCoopTime(s,seconds){if(!isCoop(s)||!s.coopRound||s.coopRound.theft||s.phase!=='playing')return null;const thief=livingEnemies(s).find(e=>e.intent.special==='steal'&&!s.blockReservedIds.has(e.id));if(!thief)return null;s.coopRound.theft=true;const amount=Math.min(15,5+(s.encounterIndex>=2?5:0)+(s.battleContext.coopDifficulty==='hard'?5:0)),remaining=Math.max(0,seconds-amount);s.seconds=remaining;s.elapsed=s.duration-remaining;return {kind:'coop-time-theft',enemyId:thief.id,monster:thief.monsterIndex,amount:seconds-remaining,remaining,text:`시간 ${seconds-remaining}초를 빼앗겼어요! 함께 서둘러요.`};}
