import {CoreMercenaryData as MercenaryData,mercenaryById} from './MercenaryData.js';
import {relation,relationshipLabel,departureLine} from './AffinitySystem.js';
import {CompanionStories,CompanionSupportLines,personalQuestById,AffinityConfig} from './AffinityData.js';
import {questStatus} from './QuestSystem.js';
import {dungeonById} from './DungeonData.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const portrait=m=>`<img src="${m.portraitAsset}" alt="${m.name} · ${m.role}" width="480" height="720" loading="eager">`;
export function relationSummary(p,id){const r=relation(p,id);return `<div class="relationship-summary"><b>${relationshipLabel(p,id)}</b><small>${r.affinityLevel===1?'함께 모험하면 새로운 이야기가 열려요.':r.affinityLevel===2?'지원에 작은 신뢰 보너스 +1 · 개인 퀘스트로 진정한 동료가 돼요.':CompanionStories[id].skill+' · 각성 완료'}</small><div class="relation-track" aria-label="동료와 쌓은 신뢰"><i style="width:${r.affinityLevel===1?r.affinityProgress/AffinityConfig.trustedAt*100:100}%"></i></div></div>`;}
export function companionRecordsHTML(session,header,warning,id){
 const p=session.data.progress,m=mercenaryById(id);
 if(!m)return `<main class="rpg-shell companion-records">${header}<section class="companion-heading"><div class="eyebrow">여섯 동료, 여섯 이야기</div><h1>동료 기록</h1><p>함께 모험한 순간이 신뢰가 됩니다. 개인 이야기는 원하는 동료와 자유롭게 진행해요.</p><button class="secondary" data-action="rpg-mercenaries">용병 길드</button></section><div class="companion-record-grid">${MercenaryData.map(m=>`<button class="companion-record-card grade-${m.grade}" data-action="rpg-companion-record" data-mercenary="${m.id}">${portrait(m)}<h2>[${m.grade}] ${m.name} · ${m.role}</h2>${relationSummary(p,m.id)}<small>함께 클리어 ${relation(p,m.id).completedDungeonsTogether}회</small></button>`).join('')}</div>${warning}</main>`;
 if(!m.isCoreMercenary)return `<main class="rpg-shell companion-records">${header}<section class="companion-biography">${portrait(m)}<h1>${m.name} · ${m.role}</h1><p>${m.personality}</p><p>${m.description}</p><p>함께 클리어 ${relation(p,id).completedDungeonsTogether}회 · ${relationshipLabel(p,id)}</p><button data-action="rpg-mercenaries">용병 길드로</button></section>${warning}</main>`;const r=relation(p,id),story=CompanionStories[id],q=personalQuestById('personal-'+id),status=questStatus(p,q.id),v=p.questProgress[q.id]?.personal,ready=p.activeParty.includes(id)&&!session.run;
 return `<main class="rpg-shell companion-records">${header}<button class="text-button" data-action="rpg-companions">← 모든 동료 기록</button><section class="companion-biography grade-${m.grade}"><div class="companion-closeup">${portrait(m)}<span>[${m.grade}] ${m.role}</span></div><div class="companion-biography-copy"><div class="eyebrow">${story.theme}</div><h1>${m.name}의 이야기</h1>${relationSummary(p,id)}<p>함께한 던전 클리어 <b>${r.completedDungeonsTogether}회</b> · 영입 ${m.recruitCost}G · 출전 비용 없음</p><section class="companion-skill"><h2>${r.awakenedSkillUnlocked?story.skill:'지원 능력'}</h2><p>${r.awakenedSkillUnlocked?story.skillText:m.description+(r.affinityLevel===2?' · 신뢰 보너스 +1':'')}</p>${r.awakenedSkillUnlocked?'<details><summary>기본 지원기술</summary><p>'+m.description+'</p></details>':''}</section><div class="companion-chapters">${story.chapters.map((text,i)=>`<article class="${i<r.affinityLevel?'unlocked':'locked'}"><h2>${['첫 만남','신뢰의 이야기','진정한 동료'][i]}</h2><p>${i<r.affinityLevel?text:'??? · 함께한 모험 속에서 열리는 이야기'}</p></article>`).join('')}</div><section class="companion-personal-quest"><h2>${r.personalQuestUnlocked?q.name:'??? · 개인 퀘스트'}</h2>${r.personalQuestUnlocked?`<p>${q.description}</p><small>${dungeonById(q.dungeon).name} · 짧은 특별 모험 · EXP 40 / 60G / 지원기술 각성</small><p>${v?`준비 ${v.actions}/${q.needed} · ${v.won?'전투 승리 완료':'목표를 채우고 승리해요.'}`:'S 실패로 의뢰가 사라지지 않아요. 준비한 뒤 다시 도전할 수 있어요.'}</p>${status==='AVAILABLE'?`<button class="primary" data-action="rpg-quest-accept" data-quest="${q.id}" ${session.run?'disabled':''}>개인 퀘스트 수락</button>`:status==='ACTIVE'?`<button class="primary" data-action="rpg-personal-start" data-quest="${q.id}" ${ready?'':'disabled'}>동료와 특별 모험 출발 →</button>${!ready?`<p>${session.run?'진행 중 모험을 먼저 마쳐 주세요.':m.name+'과 계약 후 출발할 수 있어요.'}</p><button class="secondary" data-action="rpg-mercenaries">용병 길드에서 계약 준비</button>`:''}`:status==='COMPLETED'?`<button class="primary" data-action="rpg-quest-report" data-quest="${q.id}" ${session.run?'disabled':''}>완료 보고 · 진정한 동료 각성</button>`:'<p>✓ 이야기와 각성 완료</p>'}<button class="text-button" data-action="rpg-companion-replay" data-mercenary="${id}" data-chapter="start">시작 이야기 다시 보기</button>${r.personalQuestCompleted?`<button class="text-button" data-action="rpg-companion-replay" data-mercenary="${id}" data-chapter="finish">각성 이야기 다시 보기</button>`:''}`:'<p>동료와 실제로 던전을 클리어하면 신뢰가 쌓여요. 같은 지역 반복 보상은 줄어들어요.</p>'}</section><details><summary>해금된 동료 대사</summary>${[...story.departures.slice(0,r.affinityLevel),...CompanionSupportLines[id].slice(0,Math.max(0,r.affinityLevel-1))].map(line=>'<p>“'+line+'”</p>').join('')}</details><button class="secondary" data-action="rpg-mercenaries">용병 길드로</button></div></section>${warning}</main>`;
}
export function companionStoryHTML(id,chapter='start',depart=false){const m=mercenaryById(id),s=CompanionStories[id];if(!m)return '';const final=chapter==='finish';return `<div class="overlay companion-story-overlay"><section class="modal companion-story ${final?'is-awakened':''} grade-${m.grade}" role="dialog" aria-modal="true" aria-label="${m.name} ${final?'각성':'개인'} 이야기"><div class="companion-story-portrait">${portrait(m)}</div><div class="companion-story-copy"><div class="eyebrow">${final?'★★★ 진정한 동료':'함께 쓰는 개인 이야기'}</div><h2>${final?s.skill+' 각성!':personalQuestById('personal-'+id).name}</h2>${s[chapter].map(text=>'<p>“'+text+'”</p>').join('')}${final?'<div class="awakening-skill"><b>'+s.skill+'</b><p>'+s.skillText+'</p></div>':''}<button class="primary" data-action="${depart?'rpg-personal-intro-done':'rpg-companion-story-close'}">${depart?'함께 출발하기 →':'이야기 닫기'}</button><button class="text-button" data-action="${depart?'rpg-personal-intro-done':'rpg-companion-story-close'}">이야기 건너뛰기</button></div></section></div>`;}
