import {campaign} from './ActTwoSystem.js';
import {artHTML} from './AssetManifest.js';
import {sealsHTML} from './ActTwoView.js';
export function finishDragonOpening(p){if(p.run||!campaign(p).seals.chaos)return false;campaign(p).dragonOpeningSeen=true;return true;}
export function investigateCanyon(p){const c=campaign(p);if(p.run||!c.seals.chaos||!c.dragonOpeningSeen)return false;c.canyonInvestigated=true;if(!p.unlockedDungeons.includes('sky-canyon'))p.unlockedDungeons.push('sky-canyon');return true;}
export function finishDragonSeal(p){const c=campaign(p);if(!c.dragonDefeated||!p.clearedDungeons.includes('sky-canyon')||!c.seals.darkness||!c.seals.chaos)return false;c.dragonSealSeen=true;c.seals.dragon=true;c.castleOpened=true;return true;}
const opening=[['tower','하늘을 가르는 포효','혼돈의 마탑이 안정되자 멀리서 거대한 포효가 울렸습니다. 붉어진 하늘 위로 용의 그림자가 마을을 가로지릅니다.','제2막 최종편'],['canyon','마지막 봉인','“마지막 봉인의 수호자가 움직였어.” — 엘리아\n“놈이 향한 곳은 천공의 용암 협곡이야.” — 길드 마스터','새 메인 목표'],['canyon','거대한 용을 추격하라','길드에서 마지막 봉인을 조사하고 협곡으로 출발하세요. 날개 BREAK와 브레스 예고를 관찰하며 추격하세요.','마지막 봉인']];
const seal=[['dragonNest','수호자의 마지막 말','인간…… 네가 그분을 만날 자격이 있는지 직접 확인해 보아라. 그는 단순한 부하가 아니라 오래된 보호자였습니다.','용의 수호자'],['dragonNest','거대한 용의 제단','용이 물러난 자리에 마지막 봉인이 떠오릅니다. 용 문양의 빛이 세 봉인을 이어 줍니다.','세 번째 봉인'],['dragonNest','용 문양의 균열','정확한 계산으로 열어 온 길. 마지막 검격이 용 문양을 가르고 황금빛 균열이 번집니다.','봉인 파괴'],['dragonNest','용의 봉인 파괴','용 문양이 산산이 흩어졌습니다. 세 봉인의 빛이 모두 사라집니다.','세 번째 봉인 해제'],['canyon','세 개의 봉인을 넘어서','어둠의 봉인 ✓ · 혼돈의 봉인 ✓ · 용의 봉인 ✓','봉인 3 / 3'],['castleGate','마왕의 성이 열렸습니다','멀리 거대한 성이 모습을 드러냅니다. 세 봉인을 잃은 결계에 균열이 번지고, 하늘 전체를 감싸던 장벽이 부서집니다.','LOCK → OPEN'],['kingAwakens','기다리고 있었다','왕좌의 마왕이 천천히 눈을 뜹니다. “드디어 왔군.”','마왕'],['castleGate','제2막 종료','v3.3 👑 마왕의 성 · 원래 세계로 돌아가기 위한 마지막 여정이 시작됩니다. 성의 결계는 열렸지만, 입장 전투는 다음 업데이트에서 공개됩니다.','다음 이야기']];
export const pursuitCuts=[['용의 그림자','거대한 그림자가 협곡을 뒤덮습니다. 용이 머리 위를 스치고 불길이 돌다리를 가릅니다. 다음 지점: 용의 습격.'],['무너지는 절벽','브레스가 절벽을 쓸어 버립니다. 부서지는 돌다리를 넘어 용을 추격하세요.'],['고대 용족 유적','강한 바람 속에서 용족의 뼈와 오래된 유적이 드러납니다. 남은 수호병이 길을 막습니다.'],['용의 둥지','거대한 발자국. 갑자기 조용해진 바람. 머리 위의 포효와 함께 용이 내려앉아 날개를 펼칩니다. “두 봉인을 깨뜨린 인간이 너인가.”']];
export const pursuitPending=(s,session)=>s?.phase==='reward'&&session.run?.dungeonId==='sky-canyon'&&session.run.pendingLoot?.chosen&&!(session.run.pursuitSeen||[]).includes(s.encounterIndex);
export function dragonStoryHTML(kind,index,p){const cuts=kind==='dragon-seal'?seal:opening,i=Math.max(0,Math.min(cuts.length-1,index)),[art,title,base,speaker]=cuts[i];let text=base;if(kind==='dragon-opening'&&i===1&&p.activeMercenary==='elia')text+='\n엘리아는 붉은 하늘을 응시합니다. “이번에는 끝낼 거야.”';return '<div class="act-two-scene dragon-story dragon-scene-'+i+'" role="dialog" aria-modal="true" aria-label="용의 수호자 이야기"><div class="act-scene-art">'+(art==='kingAwakens'?'<div class="king-focus">'+artHTML(art,{eager:true})+'<span class="king-eyes" aria-hidden="true"></span></div>':artHTML(art,{eager:true}))+(kind==='dragon-opening'&&i===0?'<div class="dragon-flypast">'+artHTML('dragonGuardian',{eager:true})+'</div>':'')+(kind==='dragon-seal'&&i===0?'<div class="dragon-defeated">'+artHTML('dragonGuardian',{eager:true})+'</div>':'')+(kind==='dragon-seal'&&i>=1&&i<=3?'<div class="dragon-seal-crest">✦</div>':'')+'</div><section class="act-dialogue"><div class="eyebrow">'+speaker+' · '+(i+1)+' / '+cuts.length+'</div><h1>'+title+'</h1><p>'+text+'</p>'+(kind==='dragon-seal'&&i===4?sealsHTML(p,'dragon'):'')+'<div class="opening-actions"><button class="secondary" data-action="rpg-act-skip" data-kind="'+kind+'">연출 건너뛰기</button><button class="primary" data-action="rpg-act-next" data-kind="'+kind+'" data-index="'+i+'">'+(i===cuts.length-1?'모험으로 →':'다음 이야기 →')+'</button></div></section></div>';}
export function pursuitHTML(s,session){const [title,copy]=pursuitCuts[s.encounterIndex],repeat=session.data.progress.clearedDungeons.includes('sky-canyon');let text=copy;if(s.encounterIndex===3&&session.data.progress.activeMercenary==='elia')text+='\n용: “엘리아. 결국 인간을 여기까지 데려왔군.”\n엘리아: “이번에는 끝낼 거야.”\n용사: “무슨 이야기야?”\n엘리아: “……마왕의 성에 가면 알게 될 거야.”';return '<div class="overlay pursuit-overlay" role="dialog" aria-modal="true" aria-label="용 추격 연출" data-pursuit="'+s.encounterIndex+'" data-auto-ms="'+(repeat?3000:s.encounterIndex===3?8000:6000)+'"><section class="pursuit-stage">'+artHTML(s.encounterIndex===3?'dragonNest':'canyon',{eager:true})+'<div class="dragon-flypast">'+artHTML('dragonGuardian',{eager:true})+'</div><div class="pursuit-copy"><div class="eyebrow">추격 · 계산 타이머 정지</div><h1>'+title+'</h1><p>'+text+'</p><button class="primary" data-action="rpg-pursuit-end">'+(repeat?'추격 계속 →':'연출 건너뛰기 →')+'</button></div></section></div>';}
