import {equipmentById} from './EquipmentData.js';
import {characterStats} from './RPGConfig.js';
const slots=['weapon','armor','accessory'];
export function normalizeEquipment(character){character.equipment??={weapon:null,armor:null,accessory:null};for(const slot of slots)if(!(slot in character.equipment))character.equipment[slot]=null;character.inventory??={items:[],materials:[]};character.inventory.items=Array.isArray(character.inventory.items)?character.inventory.items.filter(id=>equipmentById(id)):[];for(const slot of slots){const alias=`equipped${slot[0].toUpperCase()}${slot.slice(1)}`;if(character.equipment[slot]===null&&character[alias])character.equipment[slot]=character[alias];character[alias]=character.equipment[slot]||null;}return character;}
export function equippedItems(character){normalizeEquipment(character);return slots.map(slot=>equipmentById(character.equipment[slot])).filter(Boolean);}
export function equipmentModifiers(character){const mods={attack:0,defense:0,maxHP:0};const effects=[];for(const item of equippedItems(character)){for(const key of Object.keys(mods))mods[key]+=item.statModifiers?.[key]||0;if(item.specialEffects?.effectType)effects.push(item.specialEffects);}return {mods,effects};}
export function finalStats(character){const base=characterStats(character.level);const {mods}=equipmentModifiers(character);return {maxHP:base.maxHP+mods.maxHP,attack:base.attack+mods.attack,defense:base.defense+mods.defense};}
export function effectBonus(character,effectType,trigger){return equipmentModifiers(character).effects.filter(e=>e.effectType===effectType&&(Array.isArray(e.trigger)?e.trigger.includes(trigger):e.trigger===trigger)).reduce((n,e)=>n+(e.value||0),0);}
export function equipItem(character,id){normalizeEquipment(character);const item=equipmentById(id);if(!item)return {ok:false,message:'장비를 찾을 수 없어요.'};const index=character.inventory.items.indexOf(id);if(index<0)return {ok:false,message:'인벤토리에 없는 장비예요.'};const old=character.equipment[item.type];character.inventory.items.splice(index,1);if(old)character.inventory.items.push(old);character.equipment[item.type]=id;character[`equipped${item.type[0].toUpperCase()}${item.type.slice(1)}`]=id;clampHP(character);return {ok:true,old,message:`${item.name}을(를) 장착했어요.`};}
export function unequipItem(character,slot){normalizeEquipment(character);if(!slots.includes(slot)||!character.equipment[slot])return {ok:false,message:'장착한 장비가 없어요.'};const id=character.equipment[slot];character.inventory.items.push(id);character.equipment[slot]=null;character[`equipped${slot[0].toUpperCase()}${slot.slice(1)}`]=null;clampHP(character);return {ok:true,id,message:'장비를 해제했어요.'};}
export function clampHP(character){const stats=finalStats(character);character.maxHP=stats.maxHP;character.hp=Math.min(character.hp,stats.maxHP);return stats;}
export function sellItem(character,id){normalizeEquipment(character);if(slots.some(slot=>character.equipment[slot]===id))return {ok:false,message:'장착 중인 장비는 먼저 해제해 주세요.'};const i=character.inventory.items.indexOf(id);const item=equipmentById(id);if(i<0||!item)return {ok:false,message:'판매할 장비가 없어요.'};character.inventory.items.splice(i,1);character.gold+=item.sellPrice;return {ok:true,gold:item.sellPrice,message:`${item.name}을(를) 판매했어요.`};}
