import {artHTML} from './AssetManifest.js';
import {mercenaryById,MercenaryData} from './MercenaryData.js';
import {relation} from './AffinitySystem.js';
import {collectionProgress} from './CollectionSystem.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const finalIntro=[['왕좌의 문','마왕','왔군. 네가 여기까지 올 수 있을지 보고 싶었다.','throneDoor'],['마지막 시험','용사','이제 집으로 돌려보내 줘.','kingAwakens'],['FINAL BATTLE','마왕','아직 마지막 시험이 남았다.','demonKing']];
export const finalEnding=[['조용해진 왕좌','마왕','…네가 해냈구나. 마력의 관이 깨지고, 마왕이 무릎을 꿇었습니다.','kingDown'],['수는 힘, 연산은 법칙','마왕','이 세계에서 수는 힘이고, 연산은 그 힘을 움직이는 법칙이다. 그 법칙이 무너지기 시작했다. 나 혼자서는 막을 수 없었다. 다른 세계에서 법칙을 새롭게 받아들일 가능성이 필요했다.','throneDoor'],['동의 없는 소환','용사','그래서 나를 멋대로 데려온 거야? 그건 잘못된 일이야.','hero'],['마왕의 선택','마왕','그래. 네 동의 없이 데려왔다. 그 선택은 잘못이었다. 용서를 구할 생각은 없다. 하지만 네가 여기까지 올 가능성에 걸었다.','demonKing'],['엘리아가 알던 것','엘리아','누군가 다른 세계에서 올 거라는 예언은 알았어. 네가 올 줄은 몰랐어. 마왕의 계획 전체를 알지도 못했어. 숨겼던 것은 미안해.','elia'],['처음의 질문','마왕','처음 이곳에 왔을 때 너는 수학을 버리고 싶다고 했지.','kingAwakens'],['나의 대답','용사','지금도 수학이 제일 좋은 건 아니야. 그래도… 못한다고 도망가지는 않을 거야.','hero'],['돌아갈 시간','마왕','약속은 지키겠다. 돌아갈 시간이다.','throneDoor'],['마지막 인사','동료','','mercenaries'],['평범한 교실','용사','빛이 걷히자 처음의 교실이었습니다. 책상 위에는 풀기 싫었던 수학 문제가 그대로 놓여 있었습니다. 시간은 거의 흐르지 않은 듯했습니다.','classroom'],['연필을 들다','용사','잠시 문제를 바라보던 용사는 연필을 들었습니다. 작은 미소가 떠올랐습니다.','classroom'],['던전탈출 사칙연산','THE END','모험을 완료했습니다.','classroom']];
const farewell={rowen:'다시 만나면 그땐 내가 먼저 한 수 가르쳐주지.',bram:'어디에 있든 굳건하게 살아라.',sera:'당신의 길에 빛이 함께하길.',luna:'다음에는 네 세계의 수학도 보여줘.',kain:'더 강해져라.',elia:'이번에는… 정말 안녕.'};
export function bestCompanions(p){const counts=Object.fromEntries(MercenaryData.map(m=>[m.id,p.dungeonClearHistory.filter(h=>(h.mercenaryIds||[h.mercenaryId]).includes(m.id)&&!h.defeated).length]));const max=Math.max(0,...Object.values(counts));return max?MercenaryData.filter(m=>counts[m.id]===max).map(m=>({id:m.id,name:m.name,runs:max})):[];}
export function adventureRecord(data){const p=data.progress,stats=structuredClone(p.stats),run=p.run?.stats;for(const side of ['attack','defense'])for(const grade of ['S','A','B','C'])stats[side][grade]+=run?.[side]?.[grade]||0;return {level:data.character.level,clears:p.completedRuns+(p.run?.status==='clear'?1:0),collection:collectionProgress(p),attackS:stats.attack.S,defenseS:stats.defense.S,quests:p.rewardedQuests.length,bosses:Object.entries(p.collection.defeatCounts).filter(([id])=>['golem','treeGuardian','flameGiant','darkKnight','chaosMage','dragonGuardian','demonKing'].includes(id)).reduce((n,[,v])=>n+v,0),companions:bestCompanions(p),highestAffinity:Math.max(1,...MercenaryData.map(m=>relation(p,m.id).affinityLevel)),finalBreaks:p.run?.finalBreaks||0};}
export function finalSceneHTML(kind,index,session){const list=kind==='intro'?finalIntro:finalEnding,i=Math.min(list.length-1,Math.max(0,index)),[title,speaker,raw,art]=list[i],p=session.data.progress,active=mercenaryById(p.activeMercenary||p.endingCompanion),best=active||mercenaryById(bestCompanions(p)[0]?.id),line=kind==='ending'&&i===8?best?(relation(p,best.id).affinityLevel===3?farewell[best.id]:'언젠가 다시 만나자. 네 모험을 기억할게.'): '함께한 모든 인연을 기억하며, 용사는 고개를 끄덕였습니다.':raw;return '<main class="final-scene" data-final-scene="'+kind+'" data-scene-index="'+i+'">'+(art==='classroom'?'<div class="opening-stage opening-classroom">'+artHTML('classroomReturn',{className:'return-classroom-art',eager:true})+'<div class="return-math-note">(3 + 4) × 2 = ?</div></div>':artHTML(art,{className:'final-scene-art',eager:true}))+'<section class="final-dialogue"><small>'+(kind==='intro'?'FINAL BATTLE':'최종 진실 · 현실 귀환')+' · '+(i+1)+'/'+list.length+'</small><h1>'+title+'</h1><b>'+esc(i===8&&best?best.name:speaker)+'</b><p>'+esc(line)+'</p><nav>'+(kind==='intro'?'<button class="secondary" data-action="rpg-final-cancel">마을에서 준비</button>':'')+'<button class="secondary" data-action="rpg-final-scene-skip" data-kind="'+kind+'">장면 건너뛰기</button><button class="primary" data-action="rpg-final-scene-next" data-kind="'+kind+'" data-index="'+i+'">'+(i===list.length-1?'계속하기 →':'다음 이야기 →')+'</button></nav></section></main>';}
export function endingRecordHTML(session){const p=session.data.progress,r=p.finalRecord||adventureRecord(session.data),c=r.collection;return '<main class="rpg-shell final-record"><div class="eyebrow">THE END · 1차 본편 완결</div><h1>모험 완료!</h1><h2>🏅 마왕을 넘어선 자</h2><h3>나의 모험 기록</h3><p>최초 본편 클리어 기록 · 현재 캐릭터로 계속 모험할 수 있습니다.</p><div class="final-record-grid">'+[['최종 Level',r.level],['던전 클리어',r.clears],['몬스터 도감',c.counts.monsters+' / '+c.totals.monsters],['장비 도감',c.counts.equipment+' / '+c.totals.equipment],['스크롤 도감',c.counts.scrolls+' / '+c.totals.scrolls],['Attack S',r.attackS],['Defense S',r.defenseS],['완료 보고 퀘스트',r.quests],['보스 처치',r.bosses],['최고 친밀도',r.highestAffinity],['최종전 BREAK',r.finalBreaks]].map(([label,value])=>'<span>'+label+'<b>'+value+'</b></span>').join('')+'</div><h3>최고의 동료</h3><div class="final-companions">'+(r.companions.length?r.companions.map(m=>'<div>'+artHTML(m.id,{eager:true})+'<b>'+m.name+' · '+m.runs+'회</b></div>').join(''):'혼자서도 끝까지 계산으로 길을 열었습니다.')+'</div><p>레벨·골드·장비·도감·친밀도·퀘스트 기록이 유지됩니다.</p><nav><button class="primary" data-action="rpg-postgame">계속 모험하기 →</button><button class="secondary" data-action="rpg-ending-replay">엔딩 다시 보기</button></nav></main>';}
export function finalFormulaHTML(s,notice=''){const f=s.kingFinal;if(!f)return '';return '<div class="overlay final-formula-overlay"><section class="final-formula" role="dialog" aria-modal="true" aria-label="마지막 수식"><small>FINAL PHASE · '+f.grade+' · 재시도 '+f.attempts+'</small><h1>마지막 수식</h1><p>네가 이 세계에서 얻은 힘이 진짜 네 힘인지 보여다오.</p><div class="final-dice">'+f.dice.map((v,i)=>'<button data-action="rpg-final-dice" data-die="'+i+'"><small>d'+[8,10,12][i]+'</small><b>'+v+'</b></button>').join('')+'</div><h2>마지막 수식을 완성하세요.</h2><div class="final-target">'+f.target.value+'</div><output id="final-expression" aria-live="polite">주사위 2개 또는 3개 · 각 한 번씩 사용</output><div class="final-operators">'+['+','−','×','÷'].map(op=>'<button data-action="rpg-final-op" data-op="'+op+'">'+op+'</button>').join('')+'</div><p role="status" class="final-notice">'+esc(notice)+'</p><nav><button data-action="rpg-final-clear" class="secondary">지우기</button><button data-action="rpg-final-submit" class="primary">마지막 공격 →</button><button data-action="rpg-final-retry" class="secondary">다른 수식으로 재도전</button><button data-action="rpg-final-hint" class="secondary">도움 받기</button></nav><small>시간 제한 없음 · 실패해도 HP/아이템 유지 · 좌→우 계산</small></section></div>';}
