import {inFinal,KingRegions} from './FinalBattleData.js';
import {generateTurn} from './TargetGenerator.js';
import {evaluate} from './ExpressionEngine.js';
import {takeDamage} from './DefenseSystem.js';
import {applyStatus} from './StatusEffectSystem.js';
import {syncEncounter} from './EncounterData.js';
export const kingFloor=e=>Math.ceil(e.maxHP*.08);
export function finalDamage(e,amount){return e?.type==='demonKing'?Math.max(0,Math.min(amount,e.hp-kingFloor(e))):amount;}
export function prepareKing(s,e){if(e.type!=='demonKing')return;s.king??={mode:null,regionTurn:0,regionIndex:0,orderTurn:0,swordTurn:0,opening:false,shuffleNext:false};const k=s.king;k.regionIndex??=0;k.swordTurn??=0;if(k.shuffleNext){for(const t of s.targets)t.position=(t.position+1)%4;k.shuffleNext=false;}s.hero.poison=0;s.hero.burn=0;s.heatPoints=0;s.morale=0;s.moraleDefeated=[];s.darkBlessingTurn=0;s.chaos={level:0,defeated:[],shuffle:false,prophecy:false,mask:false,timePenalty:0};s.chaosTurn=null;k.mode=null;k.opening=false;
 if(e.boss.phase===2&&!e.boss.breakTurns){const row=KingRegions[k.regionIndex%5];k.regionIndex++;k.mode=row[0];k.regionTurn=s.enemyTurn;if(k.mode==='heat')s.heatPoints=6;if(k.mode==='morale')s.morale=4;if(k.mode==='chaos')s.chaos.shuffle=true;}
 if(e.boss.phase===3&&k.swordTurn>0&&k.swordTurn===s.enemyTurn-1){k.opening=true;if(!e.boss.breakTurns)e.boss.pressure=Math.min(3.75,e.boss.pressure+1);}
}
export function kingIntent(s,e,intent){if(e.type!=='demonKing')return intent;let result={...intent,attack:intent.attack+(s.king?.orderTurn===s.enemyTurn?4:0)};if(e.boss.phase===2&&!e.boss.breakTurns){const row=KingRegions.find(r=>r[0]===s.king.mode);result={...result,special:row[2],bossLabel:row[1],extraDamage:s.king.mode==='breath'?10:0};}return result;}
export function clearDominion(s,e){if(e?.type!=='demonKing'||!e.boss.breakTurns)return;s.king.mode=null;s.hero.poison=0;s.hero.burn=0;s.heatPoints=0;s.morale=0;s.chaosTurn=null;}
export function kingSpecial(s,e,sp){if(e?.type!=='demonKing')return false;if(sp==='kingSword'||sp==='kingBreath'){if(sp==='kingSword'&&e.boss.phase===3)s.king.swordTurn=s.enemyTurn;takeDamage(s,e.intent.extraDamage||10,'enemy');return true;}if(sp==='magicStorm'){for(let i=0;i<3;i++)takeDamage(s,5,'enemy');return true;}if(sp==='lawCollapse'){applyStatus(s,'shift',e.intent);s.king.shuffleNext=true;return true;}if(sp==='absoluteOrder'){s.king.orderTurn=s.enemyTurn+1;return true;}return false;}
export function beginFinalFormula(s,rng=Math.random,attempts=0){if(!inFinal(s))return false;const generated=generateTurn(rng);const grade=attempts<1?'S':attempts<2?'A':attempts<3?'B':'C';s.kingFinal={attempts,status:'pending',dice:generated.dice,target:generated.targets.find(t=>t.side==='attack'&&t.grade===grade),grade,expression:null};s.enemies[0].boss.phase=4;s.enemies[0].bossPhase=4;s.king.mode=null;s.phase='playing';s.seconds=60;s.elapsed=0;s.actionsDone=[false];s.player=0;for(const a of s.actionQueue||[])if(a.status==='pending')a.status='cancelled';return true;}
export function finalGate(s,rng){const e=s.enemies?.find(e=>e.type==='demonKing');if(e&&!s.kingFinal&&e.hp<=kingFloor(e)){beginFinalFormula(s,rng);syncEncounter(s);return true;}return false;}
export function submitFinal(s,ids,ops,rng=Math.random){const f=s.kingFinal;if(!inFinal(s)||f?.status!=='pending')return {ok:false,message:'마지막 수식을 먼저 확인하세요.'};let expression;try{expression=evaluate(f.dice,ids,ops);}catch(err){return {ok:false,message:err.message};}if(expression.value!==f.target.value){beginFinalFormula(s,rng,f.attempts+1);return {ok:false,retry:true,message:'마왕의 장벽이 막았습니다. 아직 끝나지 않았습니다! 새 수식에 도전하세요.'};}f.status='won';f.damage=s.enemies[0].hp;s.totalDamage+=f.damage;f.expression=expression.expression+' = '+expression.value;s.enemies[0].hp=0;syncEncounter(s);s.phase='resolution';s.resolutionStage='victory';s.stats.attack[f.grade]++;return {ok:true,grade:f.grade,expression:f.expression};}
export function validateFinalFormula(f){if(f===undefined)return true;if(!f||!Number.isSafeInteger(f.attempts)||f.attempts<0||f.attempts>1e9||!['pending','won'].includes(f.status)||!['S','A','B','C'].includes(f.grade)||!Array.isArray(f.dice)||f.dice.length!==3||f.dice.some((n,i)=>!Number.isInteger(n)||n<1||n>[8,10,12][i])||f.target?.side!=='attack'||f.target.grade!==f.grade||!Number.isFinite(f.target.value)||f.status==='won'&&(typeof f.expression!=='string'||f.expression.length>120||!Number.isSafeInteger(f.damage)||f.damage<1||f.damage>10000))return false;try{return evaluate(f.dice,f.target.solution.ids,f.target.solution.ops).value===f.target.value;}catch{return false;}}
