import {presentationFor} from './MonsterPresentationData.js';
import {monsterAt} from './MonsterRegistry.js';
let observedStage=null,observer=null,lastState=null,lastFocus=null;
function draw(s,stage){const box=stage.getBoundingClientRect();if(!box.width||!box.height)return;const cards=[...stage.querySelectorAll('.enemy-card')],legacy=!cards.length&&stage.querySelector('.enemy-presence');const entries=cards.length?cards:legacy?[legacy]:[];const queue=[...(s.actionQueue||[])].reverse(),selected=queue.find(a=>a.enemyId)?.enemyId,live=entries.filter(e=>!e.classList.contains('fallen')),focus=live.find(e=>e.dataset.enemyId===selected)||live[Math.floor((live.length-1)/2)]||entries[0];stage.dataset.pov='v35';stage.dataset.enemyCount=entries.length;
for(const [i,card]of entries.entries()){const type=card.dataset.type||monsterAt(s.monsterIndex)?.id,p=presentationFor(type),image=card.querySelector('.monster-image'),body=card.querySelector('.enemy-body')||card;if(!image)continue;card.dataset.sizeClass=p.sizeClass;card.dataset.povFocus=String(card===focus);const n=entries.length,centers=n===1?[p.center]:n===2?[.29,.68]:[.23,.5,.77],front=n===3&&i===1;let height=p.height;if(s.battleContext?.coop&&!["BOSS","COLOSSAL"].includes(p.sizeClass))height*=1.25;if(n>1&&!['BOSS','COLOSSAL'].includes(p.sizeClass))height*=front?1.1:.98;const top=n>1&&!['BOSS','COLOSSAL'].includes(p.sizeClass)?.81-height:p.top,paint=p.art.paint,imgHeight=box.height*height/paint.h,imgWidth=imgHeight*p.art.width/p.art.height,cx=box.width*centers[i],left=cx-imgWidth*(paint.x+paint.w/2),y=box.height*top-imgHeight*paint.y;image.style.setProperty('--pov-image-h',imgHeight+'px');image.style.setProperty('--pov-image-w',imgWidth+'px');image.style.setProperty('--pov-image-x',left+'px');image.style.setProperty('--pov-image-y',y+'px');body.style.setProperty('--pov-depth',front?4:n>1?2:3);card.style.setProperty('--pov-status-x',(n===1?18:box.width*(i/n)+10)+'px');card.style.setProperty('--pov-status-w',(n===1?Math.min(320,box.width*.4):(box.width/n)-20)+'px');body.dataset.povCenter=String(cx);body.dataset.povHeight=String(height*box.height);body.style.setProperty('--pov-ground-x',cx+'px');body.style.setProperty('--pov-ground-w',Math.min(box.width*.7,imgWidth*paint.w*.75)+'px');
if(card===focus){stage.style.setProperty('--pov-focus-x',cx+'px');const targets=[...stage.querySelectorAll('.shared-attack-targets .combat-target.attack,.enemy-presence .combat-target.attack')];for(const t of targets){const grade=t.dataset.grade,target=s.targets.find(v=>v.side==='attack'&&v.grade===grade),point=p.attackPoints[target?.position??['S','A','B','C'].indexOf(grade)],x=Math.max(44,Math.min(box.width-44,cx+(point[0]-.5)*imgWidth*paint.w)),ty=Math.max(box.height*.25,Math.min(box.height*(box.width<700?.58:.72),box.height*top+point[1]*height*box.height));t.style.setProperty('--pov-target-x',x+'px');t.style.setProperty('--pov-target-y',ty+'px');}}
}
const focusId=focus?.dataset.enemyId||'legacy';if(lastFocus&&lastFocus!==focusId&&!document.documentElement.classList.contains('reduced-motion')){stage.querySelector('.enemy-roster')?.animate([{translate:'8px 0'},{translate:'0 0'}],{duration:220,easing:'ease-out'});}lastFocus=focusId;}
export function frameBattle(state){const stage=document.querySelector('.battle-stage');if(!stage)return;if(observedStage!==stage){observer?.disconnect();observedStage=stage;lastState=state;observer=new ResizeObserver(()=>{if(stage.isConnected)draw(lastState,stage);});observer.observe(stage);}lastState=state;draw(state,stage);}
export function clearCamera(){observer?.disconnect();observer=null;observedStage=null;lastState=null;lastFocus=null;}
export function attackAnchor(stage,action,state,includeFallen=false){const requested=stage.querySelector('[data-enemy-id="'+action.enemyId+'"]'),card=(requested&&(includeFallen||!requested.classList.contains('fallen'))?requested:null)||stage.querySelector('.enemy-card:not(.fallen)')||stage.querySelector('.enemy-presence'),type=card?.dataset.type||monsterAt(state.monsterIndex)?.id,p=presentationFor(type),image=card?.querySelector('.monster-image'),rect=image?.getBoundingClientRect(),box=stage.getBoundingClientRect(),point=p.attackPoints[['S','A','B','C'].indexOf(action.targetGrade)]||p.attackPoints[0];return {card,image,type,preset:p,x:Math.max(40,Math.min(box.width-40,(rect?.left||box.left)-box.left+(rect?.width||box.width)*(.5+(point[0]-.5)*p.art.paint.w))),y:Math.max(box.height*.2,Math.min(box.height*.72,(rect?.top||box.top)-box.top+(rect?.height||box.height)*(p.art.paint.y+point[1]*p.art.paint.h)))};}
