import {MineConfig as config} from './MineConfig.js';
export const inMine=s=>s.battleContext?.mode==='rpg'&&s.battleContext.dungeonId==='burning-mine';
export function heatStage(s){if(!inMine(s))return 0;let stage=0;config.thresholds.forEach((n,i)=>{if((s.heatPoints||0)>=n)stage=i});return stage;}
export function bossPhase(e){if(e.type!=='flameGiant')return 1;return e.hp<=e.maxHP*config.phases[2].at?3:e.hp<=e.maxHP*config.phases[1].at?2:1;}
export function raiseHeat(s,amount=1){if(!inMine(s))return;const before=heatStage(s);s.heatPoints=Math.min(config.maxHeat,(s.heatPoints||0)+amount);return {from:before,to:heatStage(s)};}
export function mineIntent(s,e,intent){if(!inMine(s))return intent;const phase=bossPhase(e);e.bossPhase=phase;return {...intent,attack:intent.attack+config.attackBonus[heatStage(s)]+(e.type==='flameGiant'?config.phases[phase-1].attackBonus:0),special:e.type==='flameGiant'?config.phases[phase-1].special:intent.special};}
export function mineAttackDamage(s,e,grade,amount){if(!inMine(s))return {amount,breakDamage:0};const core=e.type==='flameGiant'&&bossPhase(e)===3&&grade==='S';const breakDamage=core?config.coreBreakDamage:0;const reduced=e.magmaArmorTurns>0&&amount>0?Math.max(1,Math.round(amount*(1-config.armorReduction))):amount;return {amount:reduced+breakDamage,breakDamage};}
export function mineSpecial(s,e,sp){if(!inMine(s)||!e)return false;if(sp==='heatSpark')raiseHeat(s,1);else if(sp==='burn')s.hero.burn=config.burnDuration;else if(sp==='magmaArmor')e.magmaArmorTurns=config.armorTurns+1;else if(['pickBlast','flameFist','lavaSlam'].includes(sp)){const attack=config.specialDamage[sp];const absorbed=Math.min(s.hero.shield,attack);s.hero.shield-=absorbed;s.hero.hp=Math.max(0,s.hero.hp-attack+absorbed);}else return false;return true;}
export function tickMine(s){if(!inMine(s))return null;let burnDamage=0,heatDamage=0;if(s.hero.burn>0){s.hero.burn--;burnDamage=config.burnDamage+(heatStage(s)>=2?config.burnHotBonus:0);s.hero.hp=Math.max(0,s.hero.hp-burnDamage);}if(heatStage(s)===3){heatDamage=config.heatDamage;s.hero.hp=Math.max(0,s.hero.hp-heatDamage);}for(const e of s.enemies||[])if(e.magmaArmorTurns>0)e.magmaArmorTurns--;return burnDamage||heatDamage?{burnDamage,heatDamage,hpDamage:burnDamage+heatDamage}:null;}
export function heatForecast(s){const points=s.heatPoints||0,stage=heatStage(s),boss=(s.enemies||[]).find(e=>e.hp>0&&e.type==='flameGiant'),step=boss&&bossPhase(boss)>=2?2:1;const next=config.thresholds[stage+1];return {stage,points,next,nextTurns:next===undefined?null:Math.ceil((next-points)/step),rising:next!==undefined&&points+step+(s.scrollStop?0:(s.enemies||[]).filter(e=>e.hp>0&&e.intent?.special==='heatSpark'&&!s.blockReservedIds?.has(e.id)).length)>=next,step};}
