import {relationSummary} from './CompanionView.js';
import {departureLine,companionAbilityText} from './AffinitySystem.js';
import {artHTML} from './AssetManifest.js';
import {MercenaryData,mercenaryById} from './MercenaryData.js';
import {dungeonById} from './DungeonData.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=(m,kind='portrait')=>`<img class="mercenary-art" src="${kind==='portrait'?m.portraitAsset:m.battleAsset}" alt="${m.name} · ${m.role}" loading="${kind==='portrait'?'lazy':'eager'}" decoding="async" width="480" height="720">`;
export function mercenaryGuildHTML(session,header,warning){
 const p=session.data.progress,current=mercenaryById(p.activeMercenary);
 return `<main class="rpg-shell mercenary-guild">${header}<section class="mercenary-guild-intro">${artHTML("mercenaries",{className:"shop-environment",eager:true})}<div class="eyebrow">함께 떠나는 모험 · 용병 길드</div><h1>누구와 함께할까요?</h1><p>계산에 성공하면 동료가 힘을 보태요. 계약은 던전 1회 · 자동 전투 없음.</p><b>${current?'계약 중: ['+current.grade+'] '+current.name+' · '+(session.run?'동행 중':'출발 대기'):'현재 계약한 동료 없음'} · ${session.character.gold}G</b><p>교체 시 이전 고용비는 환불되지 않아요. 탐험 도중에는 교체할 수 없어요.</p></section>${warning}<button class="secondary" data-action="rpg-companions">동료 기록 · 개인 이야기 →</button><div class="mercenary-grid">${MercenaryData.map(m=>`<article class="mercenary-card grade-${m.grade}" data-mercenary="${m.id}"><span class="mercenary-grade">[${m.grade}]</span><button class="mercenary-portrait" data-action="rpg-mercenary-detail" data-mercenary="${m.id}" aria-label="${m.name} 상세보기">${image(m)}</button><div class="mercenary-card-copy"><h2>${m.name} <small>${m.role}</small></h2><p>${companionAbilityText(p,m.id)}</p>${relationSummary(p,m.id)}<b>${m.hireCost}G · 던전 1회</b><div class="mercenary-actions"><button class="secondary" data-action="rpg-companion-record" data-mercenary="${m.id}">동료 기록</button><button class="secondary" data-action="rpg-mercenary-detail" data-mercenary="${m.id}">상세보기</button><button class="primary" data-action="rpg-mercenary-hire" data-mercenary="${m.id}" ${p.run||p.activeMercenary===m.id?'disabled':''}>${p.activeMercenary===m.id?'계약 중':'고용하기'}</button></div></div></article>`).join('')}</div></main>`;
}
export function mercenaryDetailHTML(id){const m=mercenaryById(id);if(!m)return '';return `<div class="overlay mercenary-detail-overlay"><section class="modal mercenary-detail grade-${m.grade}" role="dialog" aria-modal="true" aria-label="${m.name} 상세"><div class="mercenary-detail-art">${image(m,'battle')}</div><div><span class="mercenary-grade">[${m.grade}]</span><h2>${m.name} · ${m.role}</h2><p>“${m.dialogue}”</p><h3>기본 지원 능력</h3><p>${m.description}</p><p><b>${m.hireCost}G · 계약: 던전 1회</b></p><button class="primary" data-action="rpg-mercenary-hire" data-mercenary="${m.id}">고용하기</button><button class="secondary" data-action="rpg-mercenary-close">닫기</button></div></section></div>`;}
export function replacementHTML(result,id){return `<div class="overlay mercenary-confirm-overlay"><section class="modal" role="dialog" aria-modal="true" aria-label="용병 교체 확인"><h2>동료를 교체할까요?</h2><p>${esc(result.message)}</p><button class="primary" data-action="rpg-mercenary-confirm" data-mercenary="${id}">이전 계약 해제 · 새 용병 고용</button><button class="secondary" data-action="rpg-mercenary-close">취소 · 기존 계약 유지</button></section></div>`;}
export function partyHTML(session,id,header,warning){const m=mercenaryById(session.data.progress.activeMercenary),d=dungeonById(id),c=session.character;return `<main class="rpg-shell">${header}<section class="party-preparation"><div class="eyebrow">출발 전 파티 확인</div><h1>${d.name}으로 떠납니다</h1><div class="party-members"><article><div class="party-hero">${artHTML("hero",{eager:true})}</div><h2>Lv.${c.level} ${esc(c.name)}</h2><p>HP ${c.hp}/${c.maxHP} · 계산을 이끄는 모험가</p></article><span class="party-plus">+</span><article class="grade-${m.grade}">${image(m,'battle')}<h2>[${m.grade}] ${m.name} · ${m.role}</h2><p>${companionAbilityText(session.data.progress,m.id)}</p></article></div><p class="companion-quote">“${esc(departureLine(session.data.progress,m.id,id))}”</p><p>고용비 지급 완료 · 새로고침해도 계약 유지 · 클리어/패배 후 귀환 시 종료</p><button class="primary" data-action="rpg-party-depart" data-dungeon="${id}">던전으로 출발하기 →</button><button class="secondary" data-action="rpg-dungeon">준비 화면으로 돌아가기</button></section>${warning}</main>`;}
export function companionHTML(session){const m=mercenaryById(session.data.progress.activeMercenary);return m?`<aside class="mercenary-companion grade-${m.grade}" aria-label="전투 동료">${image(m,'battle')}<div><strong>[${m.grade}] ${m.name} · ${m.role}</strong><small>${companionAbilityText(session.data.progress,m.id)}</small><span class="companion-quote">“${esc(Date.now()-(session.companionNoticeAt||0)<5000?session.companionNotice:departureLine(session.data.progress,m.id,session.run?.dungeonId))}”</span></div></aside>`:'';}
export function showMercenarySupport(event,host,audio,{reduced=false,scale=1}={}){
 const m=mercenaryById(event.mercenaryId);if(!m||!host)return 0;
 host.querySelector('.mercenary-support')?.remove();const duration=reduced?120:(event.compact?420:m.grade==='S'?780:620)*scale;
 const layer=document.createElement('div');layer.className=`mercenary-support support-${m.id} effect-${event.effect}`;layer.style.setProperty('--merc-time',duration+'ms');layer.innerHTML=`<div class="mercenary-actor">${image(m,'battle')}</div><div class="mercenary-projectile"></div><div class="mercenary-impact"></div><div class="mercenary-support-copy" role="status"><strong>${event.text}</strong><small>${esc(event.dialogue||m.dialogue)}</small></div>`;host.append(layer);audio?.play(event.effect==='shield'?'guard':event.effect==='damage'?'attack':'magic',{grade:m.grade,type:event.effect==='heal'?'heal':event.effect==='scroll'?'fire':'shield'});
 const target=event.enemyId&&host.querySelector(`[data-enemy-id="${event.enemyId}"] .enemy-body`);
 if(target){const stage=host.getBoundingClientRect(),box=target.getBoundingClientRect(),x=box.left+box.width/2-stage.left,y=box.top+box.height/2-stage.top;layer.querySelector('.mercenary-impact').style.left=(x-55)+'px';layer.querySelector('.mercenary-impact').style.top=(y-55)+'px';layer.querySelector('.mercenary-projectile').style.top=y+'px';layer.style.setProperty('--merc-distance',(x-stage.width*.28)+'px');target.classList.add('mercenary-hit');setTimeout(()=>target.classList.remove('mercenary-hit'),duration);}
 setTimeout(()=>layer.remove(),duration+80);return duration;
}
