import {monsterAttackSpec} from './MonsterAttackData.js';
import {monsterAt} from './MonsterRegistry.js';
export class MonsterAttackPresentation{
 constructor({settings=()=>({}),audio=null}={}){this.settings=settings;this.audio=audio;this.nodes=new Set();this.animations=new Set();this.variants=new Map();this.token=0;}
 clear(){this.token++;for(const a of this.animations)a.cancel();this.animations.clear();for(const n of this.nodes)n.remove();this.nodes.clear();if(this.origin){this.origin.image.style.transformOrigin=this.origin.value;this.origin=null;}document.querySelector('.hero-health')?.classList.remove('incoming-hp-hit');document.querySelector('.battle-stage')?.removeAttribute('data-enemy-attack');}
 animate(node,frames,options,limited){if(!node||limited)return;const a=node.animate(frames,options);a.finished.catch(()=>{});this.animations.add(a);return a;}
 async steal({event,wait,valid,scale=1}){
  this.clear();const token=this.token,stage=document.querySelector('.battle-stage'),clock=document.querySelector('.timer'),image=stage?.querySelector('[data-enemy-id="'+event.enemyId+'"] .monster-image');if(!stage)return;
  const root=document.createElement('div');root.className='enemy-attack time-theft-attack';root.dataset.phase='anticipation';root.innerHTML='<strong class="enemy-attack-tell">시간 훔치기!</strong><div class="time-theft-knife"></div><b class="enemy-attack-result">공동 시간 −'+event.amount+'초</b>';root.querySelector('strong').textContent=(monsterAt(event.monster)?.name||'도둑')+' · 시간 훔치기!';root.querySelector('b').textContent='공동 시간 −'+event.amount+'초';stage.append(root);this.nodes.add(root);
  const cut=document.createElement('i');cut.className='time-theft-slice';clock?.append(cut);this.nodes.add(cut);clock?.classList.add('time-theft-target');const limited=this.settings().reduced||this.settings().detail==='simple';
  try{this.animate(image,[{transform:'scale(1)'},{transform:'scale(1.25) translateX(-3%)'}],{duration:220*scale,fill:'forwards'},limited);await wait(220);if(token!==this.token||!valid())return;root.dataset.phase='attack';this.audio?.cue('motion',monsterAttackSpec('goblin'));await wait(180);if(token!==this.token||!valid())return;root.dataset.phase='hit';cut.classList.add('cut');const number=clock?.querySelector('b');if(number)number.textContent=String(event.remaining);this.audio?.cue('impact',monsterAttackSpec('goblin'));await wait(260);}finally{clock?.classList.remove('time-theft-target');if(token===this.token)this.clear();}
 }
 async play(ctx){
  this.clear();if(!ctx.valid())return null;const token=this.token,stage=document.querySelector('.battle-stage'),actor=ctx.actor,type=actor?.type||monsterAt(ctx.state.monsterIndex)?.id,variant=((this.variants.get(type)??-1)+1)%2;this.variants.set(type,variant);const spec=monsterAttackSpec(type,actor?.intent||ctx.state.intent,variant),prefs=this.settings(),limited=prefs.reduced||prefs.detail==='simple'||matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(!stage){const event=ctx.commit();if(event)ctx.update(event);return event;}
  const card=(actor&&stage.querySelector('[data-enemy-id="'+actor.id+'"]'))||stage.querySelector('.enemy-card:not(.fallen)')||stage.querySelector('.enemy-presence'),image=card?.querySelector('.monster-image'),root=document.createElement('div');root.className='enemy-attack';Object.assign(root.dataset,{archetype:spec.archetype,type,variant:String(variant),boss:String(spec.boss),material:spec.material});root.setAttribute('aria-hidden','true');stage.append(root);this.nodes.add(root);stage.dataset.enemyAttack=spec.archetype;
  const make=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls;if(text)n.textContent=text;root.append(n);return n;},tell=make('strong','enemy-attack-tell',spec.name),effect=make('div','enemy-attack-shape'),hit=make('div','enemy-attack-impact'),caption=make('b','enemy-attack-result');
  if(['MAGIC','FIRE'].includes(spec.archetype)){if(spec.archetype==='MAGIC')effect.classList.add('painted-enemy-magic');effect.innerHTML='<svg viewBox="0 0 100 100"><svg viewBox="'+(spec.archetype==='FIRE'?'0 0':variant?'100 0':'0 0')+' 100 100" width="100" height="100"><image href="assets/combat-v35/'+(spec.archetype==='FIRE'?'spellAtlas':'sigilAtlas')+'.webp" width="200" height="200" preserveAspectRatio="none"/></svg></svg>';}
  else if(['SLASH','CLAW'].includes(spec.archetype))effect.innerHTML=spec.archetype==='SLASH'?'<img src="assets/presentation-v35/slash.webp" alt="">':'<i></i><i></i><i></i>';
  else if(spec.archetype==='RANGED')effect.innerHTML='<svg viewBox="0 0 120 30"><path d="M8 15H96M83 3L115 15L83 27M8 15L2 5M8 15L2 25" fill="none" stroke="#dccb9a" stroke-width="5"/></svg>';
  else if(spec.archetype==='BITE')effect.innerHTML='<svg viewBox="0 0 160 100"><path d="M0 0L15 65L35 5L55 55L75 0M85 0L105 60L125 5L145 65L160 0M0 100L20 50L40 95L65 55L80 100M90 100L110 50L135 95L150 55L160 100" fill="#e1d9bf"/></svg>';
  else if(spec.archetype==='HEAVY'&&image){const limb=make('div','enemy-attack-limb'),copy=image.cloneNode();copy.removeAttribute('id');copy.className='enemy-limb-art';const r=image.getBoundingClientRect(),s=stage.getBoundingClientRect();Object.assign(copy.style,{position:'absolute',left:r.left-s.left+'px',top:r.top-s.top+'px',width:r.width+'px',height:r.height+'px'});limb.append(copy);}
  if(image){this.origin={image,value:image.style.transformOrigin};image.style.transformOrigin='50% 22%';}
  let event=null;const trace=[],started=performance.now(),valid=()=>token===this.token&&ctx.valid(),phases=['anticipation','attack','hit','reaction','recovery'];
  try{for(let i=0;i<phases.length;i++){
   if(!valid())return event;const phase=phases[i],ms=spec.timing[i];root.dataset.phase=phase;trace.push({phase,time:performance.now()-started});
   if(phase==='anticipation'){if(!ctx.skipped?.())this.audio?.cue('prepare',spec);this.animate(image,[{transform:'scale(1)'},{transform:spec.archetype==='HEAVY'?'translateY(-2%) scale(1.055) rotate(-2deg)':spec.archetype==='CHARGE'?'translateY(3%) scale(.96)':spec.archetype==='STAB'?'translateX(-2%) scale(1.03)':'scale(1.05)'}],{duration:ms*ctx.scale,fill:'forwards'},limited);}
   if(phase==='attack'){tell.style.opacity='0';if(!ctx.skipped?.())this.audio?.cue('motion',spec);const zoom=spec.boss?1.2:spec.archetype==='STAB'?1.3:spec.archetype==='HEAVY'?1.22:spec.archetype==='BITE'?1.35:1.14;this.animate(image,[{transform:'scale(1.05)'},{transform:'translateY(3%) scale('+zoom+')'}],{duration:ms*ctx.scale,fill:'forwards',easing:'cubic-bezier(.2,.8,.3,1)'},limited);this.animate(effect,[{opacity:0,transform:spec.archetype==='RANGED'?'translateX(-150px) scale(.2)':spec.archetype==='SLASH'?'rotate('+(variant?-45:30)+'deg) scale(.3)':'scale(.18)'},{opacity:1,transform:spec.archetype==='SLASH'?'rotate('+(variant?-45:30)+'deg) scale(1.4)':'scale(1.8)'}],{duration:ms*ctx.scale,fill:'forwards'},limited);const limb=root.querySelector('.enemy-attack-limb');this.animate(limb,[{transform:'translateY(-8%) scale(1)'},{transform:'translateY(14%) scale(1.45)'}],{duration:ms*ctx.scale,fill:'forwards',easing:'cubic-bezier(.5,0,.9,.5)'},limited);}
   if(phase==='hit'){stage.dataset.effect='enemy';event=ctx.commit();if(event)ctx.update(event);if(!ctx.skipped?.())this.audio?.cue('impact',spec);root.dataset.blocked=String((event?.absorbed||0)>0);hit.style.opacity='1';caption.textContent=event?.hpDamage?'HP −'+event.hpDamage+(event.absorbed?' · 방어막 '+event.absorbed+' 흡수':''):event?.absorbed?'방어막으로 막았습니다! · '+event.absorbed+' 흡수':'피해를 입지 않았습니다';if(event?.hpDamage>0)document.querySelector('.hero-health')?.classList.add('incoming-hp-hit');if(!limited){const recoil=spec.archetype==='HEAVY'?8:spec.archetype==='STAB'?3:spec.archetype==='MAGIC'?2:5;this.animate(stage,[{translate:'0 0'},{translate:'0 '+recoil+'px'},{translate:'0 0'}],{duration:180,fill:'none'},false);}}
   if(phase==='reaction'){effect.style.opacity='0';root.querySelector('.enemy-attack-limb')?.remove();hit.style.opacity='.55';}
   if(phase==='recovery'){hit.style.opacity='0';this.animate(image,[{transform:'scale(1.15)'},{transform:'scale(1)'}],{duration:ms*ctx.scale,fill:'forwards'},limited);}
   await ctx.wait(limited&&phase!=='hit'?ms*.65:ms);
  }return event;}finally{this.lastRun={...spec,elapsed:performance.now()-started,trace,commits:event?1:0,hpDamage:event?.hpDamage||0,absorbed:event?.absorbed||0};if(token===this.token)this.clear();}
 }
}
