import {specialPaintedArtwork} from './PaintedCombatEffects.js';
import {SpecialNames} from './MonsterAI.js';
import {MineConfig} from './MineConfig.js';
import {GameConfig} from './GameConfig.js';
export const PresentationTiming=GameConfig.presentation;
export class SequencePlayer{
 constructor({scale=()=>1,stage=()=>{},sound=()=>{}}={}){Object.assign(this,{scale,stage,sound});this.pending=new Set();this.cancelled=false;this.skipped=false;}
 wait(ms){if(this.skipped||this.cancelled)return Promise.resolve();return new Promise(resolve=>{const item={resolve};item.handle=setTimeout(()=>{this.pending.delete(item);resolve();},ms*this.scale());this.pending.add(item);});}
 advance(){for(const item of this.pending){clearTimeout(item.handle);item.resolve();}this.pending.clear();}
 skip(){this.skipped=true;this.advance();}
 cancel(){this.cancelled=true;this.advance();}
}
export class DialogueSystem{
 constructor(player,audio){this.player=player;this.audio=audio;}
 async show(line){if(!line||this.player.cancelled)return;const host=document.querySelector('.battle-stage');if(!host)return;const bubble=document.createElement('button');bubble.className='monster-dialogue';bubble.dataset.action='dialogue-next';const speaker=document.createElement('small'),text=document.createElement('strong');speaker.textContent=line.speaker;text.textContent=line.text;bubble.append(speaker,text);host.append(bubble);if(line.voiceAsset)this.audio.playAsset(line.voiceAsset,'VOICE');await this.player.wait(line.duration);bubble.remove();}
}
export class MonsterSpecialSequence{
 constructor(player,dialogue,audio){Object.assign(this,{player,dialogue,audio});}
 async play({state,monster,blocked,commit,compact=false}){
  const p=this.player,special=state.intent.special,actor=state.enemies?.[state.enemyResolutionIndex||0],beforeHP=actor?.hp,seedMaturing=actor?.boss?.seedTurns===1;if(special==='none'){if(!p.cancelled)commit();return;}
  p.stage('special-intro');if(!compact)await this.dialogue.show(monster.dialogues.special[special]);if(p.cancelled)return;
  const host=document.querySelector('.battle-stage'),layer=document.createElement('div');layer.className=`special-sequence special-${special}`;
  const names={kingSword:'왕의 검!',kingBreath:'협곡의 브레스!',lawCollapse:'법칙 붕괴!',magicStorm:'마력 폭풍 · 세 번의 충돌!',absoluteOrder:'절대 명령!',groundSmash:'지면 강타!',rootPrison:'뿌리 감옥!',regenSeed:'재생의 씨앗!',heatSpark:'불씨 장난!',pickBlast:'폭발 곡괭이!',burn:'화상 독침!',magmaArmor:'마그마 갑옷!',flameFist:'화염 주먹!',lavaSlam:'용암 강타!',guard:'덩굴 갑옷!',steal:'시간 훔치기!',curse:'숫자 저주!',web:'거미줄 함정!',poison:'독니 공격!',shift:'숫자 위치 변경!',stone:'석화!'};
  const title=document.createElement('h2'),visual=document.createElement('div'),result=document.createElement('strong');title.textContent=names[special]||SpecialNames[special]||'특수 능력';visual.className='special-object';visual.textContent={groundSmash:'💥',rootPrison:'🌿',regenSeed:'✧',heatSpark:'🔥',pickBlast:'⛏',burn:'🔥',magmaArmor:'🛡',flameFist:'👊',lavaSlam:'💥',guard:'🌿',steal:'60초',curse:'✧  ?  ✧',web:'🕸',poison:'☠',shift:'◆ ◆ ◆',stone:'▰ ▰ ▰'}[special]||({kingSword:'⚔',kingBreath:'🔥',lawCollapse:'◆ ◈ ◆',magicStorm:'✦ ✦ ✦',absoluteOrder:'♛'})[special]||'✧';const projectile=document.createElement("i");projectile.className="special-projectile";projectile.textContent={groundSmash:'◆',rootPrison:'🌿',regenSeed:'✧',heatSpark:'🔥',pickBlast:'⛏',burn:'🔥',magmaArmor:'🛡',flameFist:'👊',lavaSlam:'💥',guard:"🌿",steal:"†",curse:"✧",web:"🕸",poison:"☠",shift:"✊",stone:"◆"}[special];const painted=specialPaintedArtwork(special);if(painted){visual.innerHTML=painted;projectile.innerHTML=painted;visual.classList.add('painted-special');projectile.classList.add('painted-special');}layer.append(title,visual,result,projectile);host?.append(layer);let theftClock=null,theftCut=null,theftImage=null;if(special==='steal'&&!blocked){theftClock=document.querySelector('.timer');theftClock?.classList.add('time-theft-target');theftCut=document.createElement('i');theftCut.className='time-theft-slice';theftClock?.append(theftCut);theftImage=actor?host?.querySelector('[data-enemy-id="'+actor.id+'"] .monster-image'):host?.querySelector('.monster-image');theftImage?.setAttribute('data-steal-actor','true');}const cleanup=()=>{theftCut?.remove();theftClock?.classList.remove('time-theft-target');theftImage?.removeAttribute('data-steal-actor');layer.remove();};
  if(['web','stone'].includes(special)){visual.textContent=`${state.intent.slot+1}P`;const target=document.createElement('span');target.className='special-player';target.textContent=`${state.intent.slot+1}P`;layer.append(target);}
  if(special==='shift'||special==='lawCollapse'){const fragments=document.createElement('div');fragments.className='number-fragments';for(const [i,t] of state.targets.entries()){const tile=document.createElement('span');tile.textContent=t.value;tile.style.setProperty('--i',i);fragments.append(tile);}layer.append(fragments);}
  if(blocked){const barrier=document.createElement('div');barrier.className='special-barrier painted-special';barrier.innerHTML=specialPaintedArtwork('absoluteOrder');layer.append(barrier);}
  p.stage('special-windup');this.audio.play(special);await p.wait(compact?250:PresentationTiming.windup);if(p.cancelled){cleanup();return;}
  p.stage(blocked?'special-block':'special-impact');layer.classList.add(blocked?'blocked':'impact');theftCut?.classList.add('cut');this.audio.play(blocked?'block':'break');commit();
  result.textContent=blocked?'특수 공격 방어 성공!':{groundSmash:`지면 충격 · 추가 공격 ${state.intent.extraDamage} · 방어막 흡수 가능`,rootPrison:`뿌리 압박 · 추가 공격 ${state.intent.extraDamage} · 방어막 흡수 가능`,regenSeed:seedMaturing?`재생 완료 · HP +${Math.max(0,(actor?.hp||0)-(beforeHP||0))}`:'씨앗 준비 · 다음 턴 회복을 막으세요',heatSpark:'열기 +1 · 다음 단계를 확인하세요',pickBlast:'추가 공격 5 · 방어막으로 흡수 가능',burn:'화상! · 2턴, 정화로 제거 가능',magmaArmor:'2턴 동안 받는 피해 35% 감소',flameFist:'추가 공격 3 · 방어막으로 흡수 가능',lavaSlam:`추가 공격 ${MineConfig.specialDamage.lavaSlam} · 방어막으로 흡수 가능`,guard:'덩굴을 회복했어요 · HP +6',steal:`다음 턴 제한시간 ${state.intent.seconds||45}초!`,curse:'숫자의 기억이 가려졌습니다',web:`${state.intent.slot+1}P 거미줄에 묶임!`,poison:'중독! · 3턴 지속',shift:'숫자는 그대로 · 위치 재조립',stone:`${state.intent.slot+1}P 석화!`}[special]||SpecialNames[special]||'특수 능력';
  if(['web','stone'].includes(special)&&!blocked){const slots=(state.nextBlockedList||[]).map(b=>`${b.slot+1}P`).join(' · ');result.textContent=slots?`${slots} 행동 봉쇄 · 최소 1명은 행동 가능`:'최소 1명은 행동 가능 · 봉쇄 없음';}if(special==='steal')visual.textContent=blocked?'시간을 지켰어요!':`다음 턴 ${state.intent.seconds||45}초`;await p.wait(compact?450:PresentationTiming.result);if(!p.cancelled){if(special==='steal'&&!blocked)this.audio.play('laugh');await this.dialogue.show(blocked?monster.dialogues.blocked:null);}cleanup();
 }
}
