import {RPGConfig,RPGDungeonData,nextLevelExp,createRPGContext} from './RPGConfig.js';
import {ScrollData} from './ScrollData.js';
import {monsterArt,equipment} from './AssetManager.js';
import {EquipmentData,RarityNames,equipmentById} from './EquipmentData.js';
import {guildHTML,dungeonSelectorHTML,dropsHTML} from './AdventureView.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const facilities=[['dungeon','🚪','던전 입구','오래된 지하감옥','모험을 떠날 준비'],['character','👤','내 캐릭터','능력치와 성장','나의 모험 기록'],['shop-weapon','⚔','무기점','장비를 사요','상점 열기'],['shop-armor','🛡','방어구점','장비를 사요','상점 열기'],['shop-accessory','💍','장신구 상점','장비를 사요','상점 열기'],['inventory','🎒','인벤토리','장비를 관리해요','열기'],['guild','📜','모험가 길드','의뢰와 완료 보고','목표 고르기']];
export function modeSelectHTML(){return `<main class="mode-home"><div class="mode-home-shade"></div><section class="mode-home-content"><div class="eyebrow">세 개의 주사위로 여는 두 가지 모험</div><h1>던전탈출<span>사칙연산</span></h1><p>계산으로 싸우고, 함께 혹은 나만의 모험을 떠나세요.</p><div class="play-mode-cards"><button class="play-mode-card class-card" data-action="setup"><span>👥</span><small>1~4인 · 한 판의 협동 전투</small><h2>함께하기</h2><p>친구들과 힘을 합쳐<br>던전을 탈출하세요!</p><b>함께 시작하기 →</b></button><button class="play-mode-card adventure-card" data-action="rpg-enter"><span>⚔</span><small>1인 · 이어지는 성장과 모험</small><h2>모험하기</h2><p>나만의 용사를 키우며<br>던전을 탐험하세요!</p><b>나의 모험으로 →</b></button></div><div class="mode-home-footer">전자칠판의 협동 전투 · 개인 패드의 성장 모험</div></section></main>`;}
function statusHTML(session){const c=session.character;return `<div class="rpg-status"><button class="character-badge" data-action="rpg-character"><span class="hero-avatar">♙</span><span><strong>${esc(c.name)}</strong><small>레벨 ${c.level} · 모험가</small></span></button><div class="rpg-resource"><b>♥ HP ${c.hp} / ${c.maxHP}</b><div class="resource-track"><i style="width:${c.hp/c.maxHP*100}%"></i></div></div><div class="rpg-resource exp-resource"><b>⭐ 경험치 ${c.exp} / ${nextLevelExp(c.level)||'최고 레벨'}</b><div class="resource-track"><i style="width:${nextLevelExp(c.level)?c.exp/nextLevelExp(c.level)*100:100}%"></i></div></div><div class="gold-badge">💰 <strong>${c.gold}</strong> 골드</div></div>`;}
function warningHTML(session,notice='',nameDraft=''){const text=[...new Set([notice,!session.saveInfo.ok?session.saveInfo.message:session.loadInfo.message].filter(Boolean))].join(' · ');return text?`<p class="rpg-notice" role="status">${esc(text)}</p>`:'';}
export function renderRPGScreen(screen,session,notice='',nameDraft=''){
 const c=session.character,warning=warningHTML(session,notice),back='<button class="text-button" data-action="title">← 모드 선택</button>';
 if(screen==='rpg-create')return `<main class="rpg-entry"><section class="rpg-entry-card">${back}<div class="eyebrow">첫 번째 모험의 이름</div><div class="entry-emblem">${equipment('shield')}</div><h1>나만의 용사를 만들어 보세요</h1><p>레벨 1 모험가로 시작합니다.<br>계산으로 던전을 돌파하고 함께 성장해요.</p><form id="character-form"><label for="character-name">용사의 이름</label><input id="character-name" name="name" value="${esc(nameDraft)}" maxlength="${RPGConfig.maxNameLength}" autocomplete="off" placeholder="예: 지승의 용사" aria-describedby="name-guide"><small id="name-guide">글자와 숫자 · 최대 ${RPGConfig.maxNameLength}자</small><button class="primary" type="submit" data-action="rpg-create-submit">용사 만들기 →</button></form>${warning}<p class="local-save-note">모험은 현재 브라우저에 저장돼요.<br>다른 기기와 자동으로 연결되지는 않아요.</p></section></main>`;
 if(screen==='rpg-gate'||screen==='rpg-reset'){const resetting=screen==='rpg-reset';return `<main class="rpg-entry"><section class="rpg-entry-card">${back}<div class="eyebrow">${resetting?'새 모험':'저장된 나의 모험'}</div><h1>${resetting?'새 모험을 시작할까요?':'모험 계속하기'}</h1>${c?`<div class="saved-character"><span>♙</span><strong>${esc(c.name)}</strong><b>레벨 ${c.level} · ${c.gold} 골드</b><small>경험치 ${c.exp} · HP ${c.hp} / ${c.maxHP}</small></div>`:''}${resetting?'<p>현재 모험 기록이 초기화됩니다.<br>정말 새로 시작할까요?</p><button class="primary danger-confirm" data-action="rpg-reset-confirm">새 모험 시작 확인</button><button class="secondary" data-action="rpg-reset-cancel">취소 · 기존 모험 유지</button>':`${c?'<button class="primary" data-action="rpg-continue">계속하기 →</button>':''}<button class="secondary" data-action="rpg-new">새 모험 시작</button>`}${warning}<p class="local-save-note">${c?'새 이름을 만들기 전까지 기존 기록을 보존합니다.':'기록을 덮어쓰려면 새 모험 시작을 확인해 주세요.'}</p></section></main>`;}
 const header=`<header class="rpg-header"><button class="text-button" data-action="title">⚔ 던전탈출 사칙연산</button><span>나의 모험</span><div><button class="secondary" data-action="rpg-save">모험 저장</button><button class="text-button" data-action="rpg-town">마을로</button></div></header>${statusHTML(session)}`;
 if(screen==='rpg-town')return `<main class="rpg-shell town-shell">${header}<section class="town-scene" aria-label="모험가 마을"><div class="town-intro"><div class="eyebrow">바람빛 마을</div><h1>${esc(c.name)}, 다시 모험을 떠날까요?</h1><p>${session.run?.pendingLoot?'받지 못한 전리품이 기다리고 있어요.':session.run?.status==='active'?'중단한 던전에서 모험을 이어갈 수 있어요.':'종탑 아래, 새로운 모험이 시작됩니다.'}</p></div><div class="town-landmarks" aria-hidden="true"><span>모험가 길드</span><span>무기점</span><span>방어구점</span><span>마법 상점 · 준비 중</span><span>던전 입구</span></div><div class="town-hint">함께하기의 기록과 능력치는 서로 영향을 주지 않아요.</div></section><nav class="town-facilities" aria-label="마을 시설">${facilities.map(([action,icon,name,sub,tag])=>`<button data-action="rpg-${action}" class="facility ${action==='future'?'future-facility':''}"><span>${icon}</span><div><strong>${name}</strong><small>${action==='dungeon'&&session.run?.pendingLoot?'전리품 마저 고르기':action==='dungeon'&&session.run?.status==='active'?'중단한 던전 이어가기':action==='guild'&&session.data.progress.completedQuests.length?`${session.data.progress.completedQuests.length}개 완료 보고 가능`:sub}</small></div><b>${tag}</b></button>`).join('')}</nav>${warning}<footer class="rpg-footer"><span>${session.saveInfo.ok?'✓ 자동 저장 사용 중':'⚠ 현재 기록이 저장되지 않았어요'}</span><span>첫 번째 모험 · 오래된 지하감옥</span></footer></main>`;
 if(screen==='rpg-character'){const ctx=createRPGContext(c);return `<main class="rpg-shell">${header}<section class="character-sheet"><div class="character-art"><div class="character-halo"></div>${equipment('sword')}${equipment('shield')}<b>레벨 ${c.level}</b></div><div class="character-detail"><div class="eyebrow">나만의 용사</div><h1>${esc(c.name)}의 모험가</h1><p>수학으로 싸우며 성장하는 모험가</p><dl><div><dt>♥ 현재 HP</dt><dd>${c.hp} / ${c.maxHP}</dd></div><div><dt>⚔ 공격력</dt><dd>${session.stats().attack}</dd></div><div><dt>🛡 방어력</dt><dd>${session.stats().defense}</dd></div><div><dt>⭐ 경험치</dt><dd>${c.exp} / ${nextLevelExp(c.level)||'최고 레벨'}</dd></div><div><dt>💰 골드</dt><dd>${c.gold}</dd></div><div><dt>🚪 던전 클리어</dt><dd>${session.data.progress.completedRuns||0}회</dd></div></dl><p class="battle-modifier-note">검격 등급 피해 +${ctx.attackBonus} · 일반 반격 최대 ${ctx.defenseMitigation} 감소<br>공격과 방어 목표를 해결하는 힘은 항상 중요해요.</p><div class="equipment-slots">${['weapon','armor','accessory'].map(slot=>{const id=c.equipment?.[slot],item=equipmentById(id);return `<div><b>${slot==='weapon'?'무기':slot==='armor'?'방어구':'장신구'}</b><span>${item?`${item.icon} ${esc(item.name)}`:'비어 있음'}</span>${item?`<button class="secondary" data-action="rpg-unequip" data-slot="${slot}">해제</button>`:''}</div>`}).join('')}</div><div class="character-scrolls"><h3>보유 두루마리</h3>${c.scrolls.map(s=>`<span>${ScrollData[s.type].icon} ${esc(ScrollData[s.type].name)} ×${s.uses}</span>`).join('')||'<span>보유 두루마리 없음</span>'}</div><button class="primary" data-action="rpg-town">마을로 돌아가기 →</button></div></section>${warning}</main>`;}
 if(screen==='rpg-inventory'){const ids=session.character.inventory?.items||[];return `<main class="rpg-shell shop-shell">${header}<section class="shop-panel"><div class="eyebrow">내 장비 가방</div><h1>인벤토리</h1><p>장비를 장착하거나 골드로 판매할 수 있어요.</p><div class="equipment-grid">${ids.length?ids.map(id=>equipmentCard(equipmentById(id),true)).join(''):'<p class="empty-queue">아직 가진 장비가 없어요.</p>'}</div></section>${warning}</main>`;}
 if(screen.startsWith('rpg-shop-')){const type=screen.slice(9),items=EquipmentData.filter(item=>item.type===type);return `<main class="rpg-shell shop-shell">${header}<section class="shop-panel"><div class="eyebrow">${type==='weapon'?'무기점':type==='armor'?'방어구점':'장신구 상점'}</div><h1>장비를 골라 보세요</h1><p>현재 골드 ${c.gold}G · 구매한 장비는 인벤토리에 들어갑니다.</p><div class="equipment-grid">${items.map(item=>equipmentCard(item,false)).join('')}</div></section>${warning}</main>`;}
 if(screen==='rpg-guild')return guildHTML(session,header,warning);
 if(screen==='rpg-dungeon')return dungeonSelectorHTML(session,header,warning);
 if(screen==='rpg-dungeon-legacy')return `<main class="rpg-shell">${header}<section class="dungeon-entry-card"><div class="eyebrow">첫 번째 던전 · 권장 레벨 ${RPGDungeonData.recommendedLevel} 이상</div><h1>${RPGDungeonData.name}</h1><p>${RPGDungeonData.description}</p><div class="dungeon-enemies">${['skeleton','goblin','orc'].map((type,i)=>`<div>${monsterArt(type)}<strong>${['스켈레톤','고블린','오크 주술사'][i]}</strong><small>${i+1}번째 전투</small></div>`).join('')}</div><div class="dungeon-reward-preview">던전 클리어 추가 보상 · ⭐ 경험치 ${RPGDungeonData.clearReward.exp} · 💰 ${RPGDungeonData.clearReward.gold} 골드</div><p class="dungeon-rules">HP는 다음 전투로 이어지고, 방어막은 0으로 시작합니다.<br>정상 클리어 또는 패배 후 마을 귀환 시 HP를 회복합니다.</p>${session.run?.status==='active'?'<p class="resume-note">중단한 전투는 처음부터 다시 시작합니다. 현재 HP와 사용한 두루마리는 유지됩니다.</p>':''}<div class="entry-actions"><button class="secondary" data-action="rpg-town">마을에 머무르기</button><button class="primary" data-action="rpg-dungeon-start">${session.run?.pendingLoot?'전리품 선택 계속하기':session.run?.status==='active'?'중단한 던전 이어가기':'던전 입장 →'}</button></div></section>${warning}</main>`;
 return '';
}
function equipmentCard(item,owned){if(!item)return '';return `<article class="equipment-card rarity-${item.rarity}"><div class="equipment-icon">${item.icon}</div><span class="rarity-label">[${RarityNames[item.rarity]}]</span><h3>${esc(item.name)}</h3><small>${item.type==='weapon'?'무기':item.type==='armor'?'방어구':'장신구'} · ${esc(item.description)}</small>${owned?`<button class="primary" data-action="rpg-equip" data-item="${item.id}">장착</button><button class="secondary" data-action="rpg-sell" data-item="${item.id}">${item.sellPrice}G에 판매</button>`:`<b class="price">${item.buyPrice}G</b><button class="primary" data-action="rpg-buy" data-item="${item.id}">구매</button>`}</article>`;}
export function renderRPGResult(state,session,scrollCard){
 const c=session.character,r=session.receipt,pending=session.run?.pendingLoot,warning=warningHTML(session);
 if(state.phase==='gameover')return `<div class="overlay"><section class="modal rpg-result" role="dialog" aria-modal="true" aria-label="전투 패배"><div class="medal">♜</div><h2>전투 패배</h2><p>용사가 잠시 쓰러졌어요.<br>마을에서 힘을 회복하고 다시 도전해 보세요.</p><div class="rpg-reward-grid"><span>레벨 ${c.level} 유지</span><span>경험치 ${c.exp} 유지</span><span>골드 ${c.gold} 유지</span></div><p>캐릭터와 이미 받은 보상은 사라지지 않아요.</p>${warning}<button class="primary" data-action="rpg-return">마을로 귀환 →</button></section></div>`;
 if(!['reward','clear'].includes(state.phase))return '';
 const up=r?.levelUp||{from:c.level,to:c.level},final=state.phase==='clear';
 return `<div class="overlay"><section class="modal rpg-result" role="dialog" aria-modal="true" aria-label="${final?'던전 클리어':'전투 승리'}"><div class="medal">✦</div><h2>${final?'던전 클리어!':'전투 승리!'}</h2><p>${esc(r?.enemyNames?.join(' · ')||state.encounter.name)}을 물리쳤습니다.</p><div class="rpg-reward-grid"><div>⭐ 경험치<b>+${r?.reward.exp||0}</b></div><div>💰 골드<b>+${r?.reward.gold||0}</b></div></div>${final?`<div class="dungeon-bonus">던전 클리어 추가 보상 · 경험치 +${r?.bonus.exp||0} · 골드 +${r?.bonus.gold||0}</div>`:''}${up.to>up.from?`<section class="level-up-banner" role="status"><span>✧</span><h3>레벨 업!</h3><b>레벨 ${up.from} → ${up.to}</b><p>최대 HP +${up.maxHP} · 공격력 +${up.attack} · 방어력 +${up.defense}</p></section>`:''}<p>현재 레벨 ${c.level} · 경험치 ${c.exp} · 골드 ${c.gold}<br>현재 HP ${c.hp} / ${c.maxHP}</p>${dropsHTML(r?.drops)}<h3>추가 두루마리 · 세 가지 중 하나를 선택하세요</h3><div class="scroll-cards loot-cards">${state.lootChosen?`<div class="reward-scroll">${ScrollData[state.lootAcquired]?.icon||'📜'} ${esc(ScrollData[state.lootAcquired]?.name)} 획득!</div>`:state.lootCandidates.map((type,i)=>scrollCard(type,i,'loot-choice')).join('')}</div>${warning}<button class="primary" data-action="${final?'rpg-return':'next-monster'}" ${!pending?.chosen?'disabled':''}>${final?'마을로 귀환 →':'다음 전투로 →'}</button></section></div>`;
}
